/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.servicios;

import controlador.acciones.servicios.ControladorRecordatorio;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.JOptionPane;
import modelo.recordatorio.Recordatorio;
import vista.modelo.Calendario;
import vista.modelo.ImagenJPanel;
import vista.modelo.Mensaje;

/**
 *
 * @author jenny
 */
public class DialogoCreaRecordatorio extends javax.swing.JDialog {

    private Calendar fecha;
    private Recordatorio record;
    private GestorControladorRecordatorio gcr;
    private ControladorRecordatorio cr;
    int indice;

//    public DialogoCreaRecordatorio(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
//        initComponents();
//        gcr = new GestorControladorRecordatorio();
//        cr = new ControladorRecordatorio(this);
//        poneAcciones();
//    }

    public DialogoCreaRecordatorio(java.awt.Frame parent, boolean modal, Calendar fecha) {
        super(parent, modal);
        initComponents();
        this.fecha = fecha;
        gcr = new GestorControladorRecordatorio();
        cr = new ControladorRecordatorio(this);
        poneFecha();
        poneAcciones();
    }

    private void poneFecha() {
        String fechita = Calendario.diasCalendario[fecha.get(Calendar.DAY_OF_WEEK) - 1]
                + " " + fecha.get(Calendar.DAY_OF_MONTH) + " de "
                + Calendario.mesesCalendario[fecha.get(Calendar.MONTH)].toLowerCase()
                + " del " + fecha.get(Calendar.YEAR);
        getTxtFecha().setText(fechita);
    }

    private void poneAcciones() {
        btnCancelar.addActionListener(gcr);
        btnGuardar.addActionListener(gcr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        spHora = new javax.swing.JSpinner();
        spMinuto = new javax.swing.JSpinner();
        LblSep = new javax.swing.JLabel();
        lblRecordar = new javax.swing.JLabel();
        cbRecord = new javax.swing.JComboBox();
        txtEvento = new javax.swing.JTextField();
        lblEvento = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        scrollDescripcion = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1  = new  ImagenJPanel ("quejas.jpg");
        jPanel1.setLayout(null);

        lblFecha.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblFecha.setText("Fecha :");
        jPanel1.add(lblFecha);
        lblFecha.setBounds(20, 10, 90, 30);

        txtFecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtFecha);
        txtFecha.setBounds(80, 10, 390, 30);

        lblHora.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblHora.setText("  Hora:");
        jPanel1.add(lblHora);
        lblHora.setBounds(10, 40, 90, 30);

        spHora.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        jPanel1.add(spHora);
        spHora.setBounds(80, 40, 50, 30);

        spMinuto.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        jPanel1.add(spMinuto);
        spMinuto.setBounds(160, 40, 50, 30);

        LblSep.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        LblSep.setText("  :");
        jPanel1.add(LblSep);
        LblSep.setBounds(130, 40, 20, 30);

        lblRecordar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblRecordar.setText("Recordar:");
        jPanel1.add(lblRecordar);
        lblRecordar.setBounds(230, 40, 90, 30);

        cbRecord.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5 min antes", "10 min antes", "30 min antes", "1 hora antes" }));
        jPanel1.add(cbRecord);
        cbRecord.setBounds(300, 40, 170, 30);
        jPanel1.add(txtEvento);
        txtEvento.setBounds(80, 70, 390, 30);

        lblEvento.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblEvento.setText(" Evento:");
        jPanel1.add(lblEvento);
        lblEvento.setBounds(10, 70, 70, 30);

        lblDescripcion.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblDescripcion.setText(" Descripcion:");
        jPanel1.add(lblDescripcion);
        lblDescripcion.setBounds(10, 100, 110, 30);

        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        scrollDescripcion.setViewportView(txtDescripcion);

        jPanel1.add(scrollDescripcion);
        scrollDescripcion.setBounds(10, 120, 460, 110);

        btnCancelar.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/button_cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(250, 250, 110, 30);

        btnGuardar.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(130, 250, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 310);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-526)/2, (screenSize.height-351)/2, 526, 351);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblSep;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cbRecord;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEvento;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblRecordar;
    private javax.swing.JScrollPane scrollDescripcion;
    private javax.swing.JSpinner spHora;
    private javax.swing.JSpinner spMinuto;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtEvento;
    private javax.swing.JLabel txtFecha;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the spHora
     */
    public javax.swing.JSpinner getSpHora() {
        return spHora;
    }

    /**
     * @return the spMinuto
     */
    public javax.swing.JSpinner getSpMinuto() {
        return spMinuto;
    }

    /**
     * @return the txtDescripcion
     */
    public javax.swing.JTextArea getTxtDescripcion() {
        return txtDescripcion;
    }

    /**
     * @return the txtEvento
     */
    public javax.swing.JTextField getTxtEvento() {
        return txtEvento;
    }

    /**
     * @return the txtFecha
     */
    public javax.swing.JLabel getTxtFecha() {
        return txtFecha;
    }

    /**
     * @return the cbRecord
     */
    public javax.swing.JComboBox getCbRecord() {
        return cbRecord;
    }
    
    

    class GestorControladorRecordatorio implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == btnCancelar) {
                dispose();
            } else if (e.getSource() == btnGuardar) {
                if (!cr.hayVacios()) {
                    int n = JOptionPane.showConfirmDialog(null, "¿Desea guardar el recordatorio?", "Guardar", JOptionPane.YES_NO_OPTION);
                    if (n == JOptionPane.YES_OPTION) {
                        cr.guardaRecordatorio();
                    }
                } else {
                    Mensaje.camposVacios();
                }

            }
        }
    }
}
