/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.usuario;

/**
 *
 * @author francisco
 */
public class DialogActivarEvaluacion extends javax.swing.JDialog {

    private static DialogActivarEvaluacion dae;

    /**
     * Creates new form DialogActivarEvaluacion
     */
    private DialogActivarEvaluacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public synchronized static DialogActivarEvaluacion getInstance(java.awt.Frame parent, boolean modal) {
        if (dae == null) {
            dae = new DialogActivarEvaluacion(parent, modal);
            dae.setVisible(true);
        }
        return dae;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Activacion Evaluacion");
        getContentPane().setLayout(null);

        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(56, 30, 80, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jefe", "Jefe RRHH" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(140, 30, 210, 30);

        jLabel2.setText("Activar evaluacion para: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 80, 140, 17);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Servidores", "Jefe" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(60, 110, 290, 27);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 150, 100, 40);

        jButton2.setText("Aceptar");
        getContentPane().add(jButton2);
        jButton2.setBounds(89, 150, 100, 40);

        setSize(new java.awt.Dimension(413, 235));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
