/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.usuario;

import controlador.acciones.usuario.ControladorConocUsuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import modelo.pregunta.Seccion;
import modelo.proceso.Rol;
import vista.modelo.ImagenJPanel;
import vista.modelo.Mensaje;

/**
 *
 * @author francisco
 */
public class DialogConocUsuario extends javax.swing.JDialog {

    private ControladorConocUsuario ccu;
    private GestorControladorConocUsuario gccu;
    private Rol rol;
    /**
     * Creates new form DialogConocUsuario
     */
    public DialogConocUsuario(java.awt.Frame parent, boolean modal, Rol rol) {
        super(parent, modal);
        initComponents();
        this.rol=rol;
        ccu = new ControladorConocUsuario(this);
        gccu = new GestorControladorConocUsuario();
        ccu.listarSeccion();
        ccu.poneLstConocDisp();
        ccu.poneLstConocAsig();
        poneEventos();
    }

    private void poneEventos() {
        btnAceptar.addActionListener(gccu);
        btnAgregarConocimiento.addActionListener(gccu);
        btnQuitarConocimiento.addActionListener(gccu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollDisponibles = new javax.swing.JScrollPane();
        lstConocimientosDisp = new javax.swing.JList();
        scrollAsignadas = new javax.swing.JScrollPane();
        lstConocimientosAsignados = new javax.swing.JList();
        btnAgregarConocimiento = new javax.swing.JButton();
        btnQuitarConocimiento = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1  = new  ImagenJPanel ("cono.jpg");
        jPanel1.setLayout(null);

        scrollDisponibles.setViewportView(lstConocimientosDisp);

        jPanel1.add(scrollDisponibles);
        scrollDisponibles.setBounds(10, 20, 310, 180);

        scrollAsignadas.setViewportView(lstConocimientosAsignados);

        jPanel1.add(scrollAsignadas);
        scrollAsignadas.setBounds(440, 20, 310, 180);

        btnAgregarConocimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/list-add.png"))); // NOI18N
        btnAgregarConocimiento.setText("Agregar");
        jPanel1.add(btnAgregarConocimiento);
        btnAgregarConocimiento.setBounds(330, 60, 100, 30);

        btnQuitarConocimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/salir_1.png"))); // NOI18N
        btnQuitarConocimiento.setText("Quitar");
        jPanel1.add(btnQuitarConocimiento);
        btnQuitarConocimiento.setBounds(330, 110, 100, 30);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/acepta.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        jPanel1.add(btnAceptar);
        btnAceptar.setBounds(570, 260, 110, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 760, 300);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-777)/2, (screenSize.height-338)/2, 777, 338);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregarConocimiento;
    private javax.swing.JButton btnQuitarConocimiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JList lstConocimientosAsignados;
    private javax.swing.JList lstConocimientosDisp;
    private javax.swing.JScrollPane scrollAsignadas;
    private javax.swing.JScrollPane scrollDisponibles;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the lstConocimientosAsignados
     */
    public javax.swing.JList getLstConocimientosAsignados() {
        return lstConocimientosAsignados;
    }

    /**
     * @return the lstConocimientosDisp
     */
    public javax.swing.JList getLstConocimientosDisp() {
        return lstConocimientosDisp;
    }

    /**
     * @return the rol
     */
    public Rol getRol() {
        return rol;
    }

    
    class GestorControladorConocUsuario implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == btnAgregarConocimiento) {
                if (lstConocimientosDisp.getSelectedIndex() != -1) {
                    Seccion s = ccu.getConocimientosDisponibles().get(lstConocimientosDisp.getSelectedIndex());
                    ccu.agregaItemConocAsignados(s);
                } else {
                    if (ccu.getConocimientosDisponibles().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Lista de Conocimientos Disponibles vacia");
                    } else {
                        Mensaje.filaNoSeleccionada();
                    }
                }
            } else if (e.getSource() == btnQuitarConocimiento) {
                if (lstConocimientosAsignados.getSelectedIndex() != -1) {
                    Seccion s = ccu.getConocimientosAsignados().get(lstConocimientosAsignados.getSelectedIndex());
                    ccu.quitaItemConocAsignados(s);
                } else {
                    if (ccu.getConocimientosAsignados().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Lista de Conocimientos Asignados vacia");
                    } else {
                        Mensaje.filaNoSeleccionada();
                    }
                }
            }else if(e.getSource()==btnAceptar){
                ccu.guardaConocUsuario();
                dispose();
            }
        }
    }
}
