/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.usuario;

import controlador.acciones.usuario.ControladorDestrezaUsuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import modelo.proceso.Rol;
import vista.modelo.Mensaje;

/**
 *
 * @author francisco
 */
public class DialogCompetTecnica extends javax.swing.JDialog {

    private ControladorDestrezaUsuario cdu;
    private GestorControladorDestrezaUsuario gcdu;
    private Rol rol;

    /**
     * Creates new form DialogDestrezaUsuario
     */
    public DialogCompetTecnica(java.awt.Frame parent, boolean modal, Rol rol) {
        super(parent, modal);
        initComponents();
        this.rol = rol;
        cdu = new ControladorDestrezaUsuario(this);
        gcdu = new GestorControladorDestrezaUsuario();
        cdu.listarDestreza();
        cdu.poneLstDestrezasDisp();
        cdu.poneLstDestrezasAsig();
        poneEventos();
    }

    private void poneEventos() {
        btnAgregarDestreza.addActionListener(gcdu);
        btnQuitarDestreza.addActionListener(gcdu);
        btnAceptar.addActionListener(gcdu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollDisponibles = new javax.swing.JScrollPane();
        lstDestrezasDisponibles = new javax.swing.JList();
        btnAgregarDestreza = new javax.swing.JButton();
        btnQuitarDestreza = new javax.swing.JButton();
        scrollAsignadas = new javax.swing.JScrollPane();
        lstDestrezasAsignadas = new javax.swing.JList();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        scrollDisponibles.setViewportView(lstDestrezasDisponibles);

        getContentPane().add(scrollDisponibles);
        scrollDisponibles.setBounds(20, 20, 310, 180);

        btnAgregarDestreza.setText("Agregar");
        getContentPane().add(btnAgregarDestreza);
        btnAgregarDestreza.setBounds(340, 60, 80, 30);

        btnQuitarDestreza.setText("Quitar");
        getContentPane().add(btnQuitarDestreza);
        btnQuitarDestreza.setBounds(340, 110, 80, 30);

        scrollAsignadas.setViewportView(lstDestrezasAsignadas);

        getContentPane().add(scrollAsignadas);
        scrollAsignadas.setBounds(430, 20, 310, 180);

        btnAceptar.setText("Aceptar");
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(320, 240, 110, 40);

        setSize(new java.awt.Dimension(771, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregarDestreza;
    private javax.swing.JButton btnQuitarDestreza;
    private javax.swing.JList lstDestrezasAsignadas;
    private javax.swing.JList lstDestrezasDisponibles;
    private javax.swing.JScrollPane scrollAsignadas;
    private javax.swing.JScrollPane scrollDisponibles;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the rol
     */
    public Rol getRol() {
        return rol;
    }

    /**
     * @return the lstDestrezasAsignadas
     */
    public javax.swing.JList getLstDestrezasAsignadas() {
        return lstDestrezasAsignadas;
    }

    /**
     * @return the lstDestrezasDisponibles
     */
    public javax.swing.JList getLstDestrezasDisponibles() {
        return lstDestrezasDisponibles;
    }

    class GestorControladorDestrezaUsuario implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == btnAgregarDestreza) {
                if (lstDestrezasDisponibles.getSelectedIndex() != -1) {
                    cdu.agregaItemDestrezaAsignados();
                } else {
                    Mensaje.campoNoSeleccionado("Destreza");
                }
            } else if (e.getSource() == btnQuitarDestreza) {
                if (lstDestrezasAsignadas.getSelectedIndex() != -1) {
                    cdu.quitaItemDestrezaAsignados();
                } else {
                    Mensaje.campoNoSeleccionado("Destreza");
                }

            } else if (e.getSource() == btnAceptar) {
                cdu.guardaDestrezaUsuario();
                dispose();
            }
        }
    }
}
