/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.usuario;

import controlador.acciones.usuario.ControladorDestrezaUsuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import modelo.proceso.Rol;
import vista.modelo.ImagenJPanel;
import vista.modelo.Mensaje;

/**
 *
 * @author jenny
 */
public class DialogCompetTecnica extends javax.swing.JDialog {

    private ControladorDestrezaUsuario cdu;
    private GestorControladorDestrezaUsuario gcdu;
    private Rol rol;

    /**
     * Creates new form DialogDestrezaUsuario
     */
    public DialogCompetTecnica(java.awt.Frame parent, boolean modal, Rol rol) {
        super(parent, modal);
        initComponents();
        this.rol = rol;
        cdu = new ControladorDestrezaUsuario(this);
        gcdu = new GestorControladorDestrezaUsuario();
        cdu.listarDestreza();
        cdu.poneLstDestrezasDisp();
        cdu.poneLstDestrezasAsig();
        poneEventos();
    }

    private void poneEventos() {
        btnAgregarDestreza.addActionListener(gcdu);
        btnQuitarDestreza.addActionListener(gcdu);
        btnAceptar.addActionListener(gcdu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollDisponibles = new javax.swing.JScrollPane();
        lstDestrezasDisponibles = new javax.swing.JList();
        scrollAsignadas = new javax.swing.JScrollPane();
        lstDestrezasAsignadas = new javax.swing.JList();
        btnAgregarDestreza = new javax.swing.JButton();
        btnQuitarDestreza = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1  = new  ImagenJPanel ("quejas.jpg");
        jPanel1.setLayout(null);

        scrollDisponibles.setViewportView(lstDestrezasDisponibles);

        jPanel1.add(scrollDisponibles);
        scrollDisponibles.setBounds(10, 40, 310, 180);

        scrollAsignadas.setViewportView(lstDestrezasAsignadas);

        jPanel1.add(scrollAsignadas);
        scrollAsignadas.setBounds(430, 40, 310, 180);

        btnAgregarDestreza.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnAgregarDestreza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/list-add.png"))); // NOI18N
        btnAgregarDestreza.setText("Agregar");
        btnAgregarDestreza.setToolTipText("Agregar Competencias Tecnicas");
        jPanel1.add(btnAgregarDestreza);
        btnAgregarDestreza.setBounds(330, 50, 99, 30);

        btnQuitarDestreza.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnQuitarDestreza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/regresar.png"))); // NOI18N
        btnQuitarDestreza.setText("Quitar");
        btnQuitarDestreza.setToolTipText("Quitar competencia");
        jPanel1.add(btnQuitarDestreza);
        btnQuitarDestreza.setBounds(330, 100, 100, 30);

        btnAceptar.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/acepta.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setToolTipText("Aceptar para guardar la información ");
        jPanel1.add(btnAceptar);
        btnAceptar.setBounds(520, 240, 110, 40);

        btnCerrar.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/exit.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.setToolTipText("Cancelar para salir sin guardar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar);
        btnCerrar.setBounds(630, 240, 110, 40);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setText("Competencias Técnicas agregadas");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(460, 20, 260, 21);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setText("Competencias Técnicas a agregar:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 270, 21);

        jLabel3.setText("<html>Seleccione de esta lista las destrzas <br>que seran agregadas al usuario o servidor seleccionado</html>");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 230, 250, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 310);

        setSize(new java.awt.Dimension(762, 345));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed

        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregarDestreza;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnQuitarDestreza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JList lstDestrezasAsignadas;
    private javax.swing.JList lstDestrezasDisponibles;
    private javax.swing.JScrollPane scrollAsignadas;
    private javax.swing.JScrollPane scrollDisponibles;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the rol
     */
    public Rol getRol() {
        return rol;
    }

    /**
     * @return the lstDestrezasAsignadas
     */
    public javax.swing.JList getLstDestrezasAsignadas() {
        return lstDestrezasAsignadas;
    }

    /**
     * @return the lstDestrezasDisponibles
     */
    public javax.swing.JList getLstDestrezasDisponibles() {
        return lstDestrezasDisponibles;
    }

    class GestorControladorDestrezaUsuario implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == btnAgregarDestreza) {
                if (lstDestrezasDisponibles.getSelectedIndex() != -1) {
                    cdu.agregaItemDestrezaAsignados();
                } else {
                    Mensaje.campoNoSeleccionado("Destreza");
                }
            } else if (e.getSource() == btnQuitarDestreza) {
                if (lstDestrezasAsignadas.getSelectedIndex() != -1) {
                    cdu.quitaItemDestrezaAsignados();
                } else {
                    Mensaje.campoNoSeleccionado("Destreza");
                }

            } else if (e.getSource() == btnAceptar) {
                int opc = JOptionPane.showConfirmDialog(null, "¿Desea Guardar los datos?", "Guardar", JOptionPane.YES_NO_OPTION);
                if (opc == JOptionPane.YES_OPTION) {
                    cdu.guardaDestrezaUsuario();
                }
                dispose();
            }
        }
    }
}
