/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.usuario;

import controlador.acciones.proceso.ControladorInformeActiv;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author francisco
 */
public class DialogInformeActiv extends javax.swing.JDialog {

    private ControladorInformeActiv cia;
    private GestorControlInfAct gcia;

    public DialogInformeActiv(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cia = new ControladorInformeActiv(this);
        gcia = new GestorControlInfAct();
        poneEventos();
        cia.llenaPnlDatosInf();
    }

    private void poneEventos() {
        btnSeleccAct.addActionListener(gcia);
        btnCerrar.addActionListener(gcia);
        btnGuardar.addActionListener(gcia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlAbajo = new javax.swing.JPanel();
        btnSeleccAct = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        pnlMedio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        scrollActiv = new javax.swing.JScrollPane();
        pnlDatosInf = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlAbajo.setPreferredSize(new java.awt.Dimension(10, 50));
        pnlAbajo.setLayout(null);

        btnSeleccAct.setText("Seleccion Actividades");
        pnlAbajo.add(btnSeleccAct);
        btnSeleccAct.setBounds(10, 5, 160, 40);

        btnGuardar.setText("Guardar");
        pnlAbajo.add(btnGuardar);
        btnGuardar.setBounds(480, 5, 100, 40);

        pnlPrincipal.add(pnlAbajo, java.awt.BorderLayout.SOUTH);

        pnlMedio.setBorder(null);
        pnlMedio.setLayout(null);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INFORME DE ACTIVIDADES DEL MES DE ");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMedio.add(jLabel2);
        jLabel2.setBounds(10, 10, 980, 40);

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ACTIVIDADES");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMedio.add(jLabel3);
        jLabel3.setBounds(10, 50, 440, 60);

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INDICADOR");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMedio.add(jLabel4);
        jLabel4.setBounds(450, 50, 200, 60);

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("META");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMedio.add(jLabel5);
        jLabel5.setBounds(650, 50, 70, 60);

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SEMANA");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMedio.add(jLabel7);
        jLabel7.setBounds(720, 50, 200, 30);

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TOTAL");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMedio.add(jLabel8);
        jLabel8.setBounds(920, 50, 70, 60);

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("1");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMedio.add(jLabel9);
        jLabel9.setBounds(720, 80, 50, 30);

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("2");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMedio.add(jLabel10);
        jLabel10.setBounds(770, 80, 50, 30);

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("3");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMedio.add(jLabel11);
        jLabel11.setBounds(820, 80, 50, 30);

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("4");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMedio.add(jLabel12);
        jLabel12.setBounds(870, 80, 50, 30);

        scrollActiv.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlDatosInf.setLayout(new javax.swing.BoxLayout(pnlDatosInf, javax.swing.BoxLayout.Y_AXIS));
        scrollActiv.setViewportView(pnlDatosInf);

        pnlMedio.add(scrollActiv);
        scrollActiv.setBounds(10, 110, 980, 380);

        pnlPrincipal.add(pnlMedio, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(10, 50));
        jPanel2.setLayout(null);

        btnCerrar.setText("Cerrar");
        jPanel2.add(btnCerrar);
        btnCerrar.setBounds(900, 5, 90, 40);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(1010, 627));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSeleccAct;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlAbajo;
    private javax.swing.JPanel pnlDatosInf;
    private javax.swing.JPanel pnlMedio;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JScrollPane scrollActiv;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the pnlDatosInf
     */
    public javax.swing.JPanel getPnlDatosInf() {
        return pnlDatosInf;
    }

    class GestorControlInfAct implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == btnSeleccAct) {
                cia.abreDialogoEscActiv();
            } else if (e.getSource() == btnCerrar) {
                dispose();
            } else if (e.getSource() == btnGuardar) {
            }
        }
    }
}
