/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.usuario;

import controlador.acciones.usuario.ControladorUsuario;
import controlador.basedatos.OperacionesBD;
import java.util.ArrayList;
import modelo.proceso.Actividad;
import modelo.usuario.Usuario;

/**
 *
 * @author jenny
 */
public class DialogUsuarios extends javax.swing.JDialog {

    private Usuario usuarioNuevo;
    private Usuario usuarioAnterior;
    private ArrayList<Usuario> usuarios;
    public DialogUsuarios(java.awt.Frame parent, boolean modal, Usuario us) {
        super(parent, modal);
        initComponents();
        ControladorUsuario.listar();
        usuarioAnterior = us;
        llenaComboUsuarios();
    }

    private void llenaComboUsuarios() {
        cbUsuarios.removeAllItems();
        usuarios= new ArrayList<>();
        int i = 0;
        for (Usuario u : ControladorUsuario.usuarios) {
            if (!u.equals(usuarioAnterior)) {
                String s = u.getNombre() + " - " + ControladorUsuario.roles.get(i).getCargo();
                cbUsuarios.addItem(s);
                usuarios.add(u);
            }
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbUsuarios = new javax.swing.JComboBox();
        lblMensaje = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(cbUsuarios);
        cbUsuarios.setBounds(20, 50, 380, 30);

        lblMensaje.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblMensaje.setText("Escoja el servidor al que desea pasar las actividades:");
        getContentPane().add(lblMensaje);
        lblMensaje.setBounds(30, 10, 390, 30);

        btnCancelar.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/salir_1.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar para salir ");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(220, 90, 110, 40);

        btnAceptar.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Select.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setToolTipText("Aceptar para actualizar la información");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(90, 90, 110, 40);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-442)/2, (screenSize.height-186)/2, 442, 186);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        int i = cbUsuarios.getSelectedIndex();        
        usuarioNuevo = usuarios.get(i);
        int rol = usuarioNuevo.getRol().getIdRol();
        ArrayList<Actividad> act = (ArrayList<Actividad>) OperacionesBD.listarconCondicion("Actividad", "rol_idRol", String.valueOf(rol));
        for (Actividad a : act) {
            a.setRol(usuarioNuevo.getRol());
            if(OperacionesBD.modificar(a)){
                System.out.println("si se modifica");
            }else{
                System.out.println("no se modifica");
            }
        }
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cbUsuarios;
    private javax.swing.JLabel lblMensaje;
    // End of variables declaration//GEN-END:variables

}
