/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.usuario;

import modelo.proceso.Actividad;

/**
 *
 * @author jenny
 */
public class PnlInfActiv extends javax.swing.JPanel {

    public PnlInfActiv(Actividad a) {
        initComponents();
        txtActividad.setText(a.getDescripcion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollIndicador = new javax.swing.JScrollPane();
        txtIndicador = new javax.swing.JTextArea();
        txtPrimSemana = new javax.swing.JTextField();
        txtSegundaSemana = new javax.swing.JTextField();
        txtTerceraSemana = new javax.swing.JTextField();
        txtCuartaSemana = new javax.swing.JTextField();
        txtMeta = new javax.swing.JTextField();
        txtTotalMensual = new javax.swing.JTextField();
        scrollActividades = new javax.swing.JScrollPane();
        txtActividad = new javax.swing.JTextArea();

        setLayout(null);

        txtIndicador.setColumns(20);
        txtIndicador.setLineWrap(true);
        txtIndicador.setRows(5);
        scrollIndicador.setViewportView(txtIndicador);

        add(scrollIndicador);
        scrollIndicador.setBounds(440, 2, 200, 60);

        txtPrimSemana.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        txtPrimSemana.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtPrimSemana);
        txtPrimSemana.setBounds(710, 0, 50, 60);

        txtSegundaSemana.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        txtSegundaSemana.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtSegundaSemana);
        txtSegundaSemana.setBounds(760, 0, 50, 60);

        txtTerceraSemana.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        txtTerceraSemana.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtTerceraSemana);
        txtTerceraSemana.setBounds(810, 0, 50, 60);

        txtCuartaSemana.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        txtCuartaSemana.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtCuartaSemana);
        txtCuartaSemana.setBounds(860, 0, 50, 60);

        txtMeta.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        txtMeta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtMeta);
        txtMeta.setBounds(640, 0, 70, 60);

        txtTotalMensual.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        txtTotalMensual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtTotalMensual);
        txtTotalMensual.setBounds(910, 0, 70, 60);

        txtActividad.setEditable(false);
        txtActividad.setColumns(20);
        txtActividad.setLineWrap(true);
        txtActividad.setRows(5);
        scrollActividades.setViewportView(txtActividad);

        add(scrollActividades);
        scrollActividades.setBounds(0, 0, 430, 62);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollActividades;
    private javax.swing.JScrollPane scrollIndicador;
    private javax.swing.JTextArea txtActividad;
    private javax.swing.JTextField txtCuartaSemana;
    private javax.swing.JTextArea txtIndicador;
    private javax.swing.JTextField txtMeta;
    private javax.swing.JTextField txtPrimSemana;
    private javax.swing.JTextField txtSegundaSemana;
    private javax.swing.JTextField txtTerceraSemana;
    private javax.swing.JTextField txtTotalMensual;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the txtActividad
     */
    public javax.swing.JTextArea getTxtActividad() {
        return txtActividad;
    }

    /**
     * @return the txtCuartaSemana
     */
    public javax.swing.JTextField getTxtCuartaSemana() {
        return txtCuartaSemana;
    }

    /**
     * @return the txtIndicador
     */
    public javax.swing.JTextArea getTxtIndicador() {
        return txtIndicador;
    }

    /**
     * @return the txtMeta
     */
    public javax.swing.JTextField getTxtMeta() {
        return txtMeta;
    }

    /**
     * @return the txtPrimSemana
     */
    public javax.swing.JTextField getTxtPrimSemana() {
        return txtPrimSemana;
    }

    /**
     * @return the txtSegundaSemana
     */
    public javax.swing.JTextField getTxtSegundaSemana() {
        return txtSegundaSemana;
    }

    /**
     * @return the txtTerceraSemana
     */
    public javax.swing.JTextField getTxtTerceraSemana() {
        return txtTerceraSemana;
    }

    /**
     * @return the txtTotalMensual
     */
    public javax.swing.JTextField getTxtTotalMensual() {
        return txtTotalMensual;
    }
}
