/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.operaciones;

import controlador.acciones.operaciones.ControladorCompetenciasTecnicas;
import controlador.acciones.operaciones.ControladorCompetenciasUniversales;
import controlador.acciones.operaciones.ControladorPreguntas;
import controlador.acciones.operaciones.ControladorTrabajoEquipo;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.EtchedBorder;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import vista.modelo.ImagenJPanel;
import vista.modelo.Mensaje;

/**
 *
 * @author jenny
 */
public class PnlOperaciones extends javax.swing.JPanel {

    private ControladorPreguntas cp;
    private ControladorCompetenciasTecnicas cctp;
    private ControladorCompetenciasUniversales ccu;
    private ControladorTrabajoEquipo cte;
    private GestorControladorOperaciones gco;

    /**
     * Creates new form PnlNuevaPregunta
     */
    public PnlOperaciones() {
        initComponents();
        cp = new ControladorPreguntas(this);
        gco = new GestorControladorOperaciones();
        cctp = new ControladorCompetenciasTecnicas(this);
        ccu = new ControladorCompetenciasUniversales(this);
        cte = new ControladorTrabajoEquipo(this);
        cp.poneCbSeccion();
        cctp.poneEnables(false);
        ccu.poneEnablesUniv(false);
        cte.poneEnablesTrabEquip(false);
        poneAcciones();

    }

    private void poneAcciones() {
        btnNuevaSeccion.addActionListener(gco);
        btnAplicar.addActionListener(gco);
        btnGuardarPregunta.addActionListener(gco);
        tabbedOperaciones.addChangeListener(gco);
        cbSeccionLstPreg.addActionListener(gco);
        btnEliminar.addActionListener(gco);
        btnNuevaCompetencia.addActionListener(gco);
        btnGuardarCompetencia.addActionListener(gco);
        btnEditarCompetencias.addActionListener(gco);
        btnEliminarCompetencias.addActionListener(gco);
        btnNuevaCompetenciaUniversal.addActionListener(gco);
        btnGuardarCompetenciaUniversal.addActionListener(gco);
        btnEditarCompetenciaUniversal.addActionListener(gco);
        btnEliminarCompetenciaUniversal.addActionListener(gco);
        btnNuevoTrabajoEq.addActionListener(gco);
        btnGuardarTrabEquipo.addActionListener(gco);
        btnEditTrabEq.addActionListener(gco);
        btnElimTrabEq.addActionListener(gco);
        btnEditarSeccion.addActionListener(gco);
        btnCancelarPreg.addActionListener(gco);
        getBtnCancelarTecnicas().addActionListener(gco);
        getBtnCancelarUniversales().addActionListener(gco);
        getBtnCancelarTrabajo().addActionListener(gco);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedOperaciones = new javax.swing.JTabbedPane();
        pnlUno = new javax.swing.JPanel();
        pnlNuevaPregunta = new javax.swing.JPanel();
        lblNuevaPreg = new javax.swing.JLabel();
        txtNuevaPregunt = new javax.swing.JTextField();
        lblNroResp = new javax.swing.JLabel();
        spNroPreg = new javax.swing.JSpinner();
        btnGuardarPregunta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlRespuestas = new javax.swing.JPanel();
        btnAplicar = new javax.swing.JButton();
        lblEscogerSeccion = new javax.swing.JLabel();
        cbSeccion = new javax.swing.JComboBox();
        btnNuevaSeccion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCancelarPreg = new javax.swing.JButton();
        pnlDos = new javax.swing.JPanel();
        pnlListaPregunta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbSeccionLstPreg = new javax.swing.JComboBox();
        btnEditarSeccion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPreguntas = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pnlTres = new javax.swing.JPanel();
        pnlCompTecPuesto = new javax.swing.JPanel();
        txtDestreza = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAlta = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMedia = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtBaja = new javax.swing.JTextArea();
        btnGuardarCompetencia = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblCompetencias = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnEliminarCompetencias = new javax.swing.JButton();
        btnNuevaCompetencia = new javax.swing.JButton();
        btnEditarCompetencias = new javax.swing.JButton();
        btnCancelarTecnicas = new javax.swing.JButton();
        pnlCuatro = new javax.swing.JPanel();
        pnlCompUniv = new javax.swing.JPanel();
        btnNuevaCompetenciaUniversal = new javax.swing.JButton();
        btnEditarCompetenciaUniversal = new javax.swing.JButton();
        btnEliminarCompetenciaUniversal = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblCompetenciasUniversales = new javax.swing.JTable();
        txtDestrezaCompUniv = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtMediaCompUniv = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtAltaCompUniv = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtBajaCompUniv = new javax.swing.JTextArea();
        btnGuardarCompetenciaUniversal = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnCancelarUniversales = new javax.swing.JButton();
        pnlCinco = new javax.swing.JPanel();
        pnlTrabajoEquipo = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblTrabajoEquipo = new javax.swing.JTable();
        btnNuevoTrabajoEq = new javax.swing.JButton();
        btnEditTrabEq = new javax.swing.JButton();
        btnElimTrabEq = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtDescripcionTrabEq = new javax.swing.JTextField();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtAltaTrabEquipo = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtMediaTrabEquipo = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtBajaTrabEquipo = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnGuardarTrabEquipo = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        btnCancelarTrabajo = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnlUno  = new  ImagenJPanel ("zzz.jpg");

        pnlNuevaPregunta.setOpaque(false);
        pnlNuevaPregunta.setPreferredSize(new java.awt.Dimension(760, 450));
        pnlNuevaPregunta.setLayout(null);

        lblNuevaPreg.setText("  Ingrese la nueva pregunta:");
        pnlNuevaPregunta.add(lblNuevaPreg);
        lblNuevaPreg.setBounds(30, 80, 200, 30);
        pnlNuevaPregunta.add(txtNuevaPregunt);
        txtNuevaPregunt.setBounds(230, 80, 450, 30);

        lblNroResp.setText("Escoja el nro de respuestas:");
        pnlNuevaPregunta.add(lblNroResp);
        lblNroResp.setBounds(30, 120, 200, 30);

        spNroPreg.setModel(new javax.swing.SpinnerNumberModel(2, 2, 5, 1));
        pnlNuevaPregunta.add(spNroPreg);
        spNroPreg.setBounds(230, 120, 80, 30);

        btnGuardarPregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Save.png"))); // NOI18N
        btnGuardarPregunta.setText("Guardar");
        btnGuardarPregunta.setToolTipText("Guardar informacion de test ");
        pnlNuevaPregunta.add(btnGuardarPregunta);
        btnGuardarPregunta.setBounds(270, 400, 110, 40);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlRespuestas.setLayout(new java.awt.GridLayout(5, 0));
        jScrollPane1.setViewportView(pnlRespuestas);

        pnlNuevaPregunta.add(jScrollPane1);
        jScrollPane1.setBounds(30, 160, 710, 220);

        btnAplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/add.png"))); // NOI18N
        btnAplicar.setText("Aplicar");
        btnAplicar.setToolTipText("Ingresar las respuestas a la pregunta");
        pnlNuevaPregunta.add(btnAplicar);
        btnAplicar.setBounds(320, 110, 100, 40);

        lblEscogerSeccion.setText("                Escoja Seccion:");
        pnlNuevaPregunta.add(lblEscogerSeccion);
        lblEscogerSeccion.setBounds(40, 43, 190, 30);
        pnlNuevaPregunta.add(cbSeccion);
        cbSeccion.setBounds(230, 40, 360, 30);

        btnNuevaSeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Edit.png"))); // NOI18N
        btnNuevaSeccion.setText("Nueva");
        btnNuevaSeccion.setToolTipText("Ingresar nueva seccion");
        pnlNuevaPregunta.add(btnNuevaSeccion);
        btnNuevaSeccion.setBounds(591, 40, 100, 30);

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("AGREGAR NUEVA PREGUNTA");
        pnlNuevaPregunta.add(jLabel6);
        jLabel6.setBounds(230, 0, 280, 30);

        btnCancelarPreg.setText("Cancelar");
        pnlNuevaPregunta.add(btnCancelarPreg);
        btnCancelarPreg.setBounds(390, 400, 120, 40);

        pnlUno.add(pnlNuevaPregunta);

        tabbedOperaciones.addTab("NUEVA PREGUNTA", pnlUno);

        pnlDos  = new  ImagenJPanel ("zzz.jpg");

        pnlListaPregunta.setOpaque(false);
        pnlListaPregunta.setPreferredSize(new java.awt.Dimension(760, 350));
        pnlListaPregunta.setLayout(null);

        jLabel4.setText("Seccion:");
        pnlListaPregunta.add(jLabel4);
        jLabel4.setBounds(40, 70, 110, 30);
        pnlListaPregunta.add(cbSeccionLstPreg);
        cbSeccionLstPreg.setBounds(110, 70, 380, 30);

        btnEditarSeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/AGENDA1.png"))); // NOI18N
        btnEditarSeccion.setText("Editar Sección");
        btnEditarSeccion.setToolTipText("Actualizar seccion");
        pnlListaPregunta.add(btnEditarSeccion);
        btnEditarSeccion.setBounds(500, 70, 140, 30);

        tblPreguntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblPreguntas);

        pnlListaPregunta.add(jScrollPane2);
        jScrollPane2.setBounds(40, 110, 590, 220);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/salir_1.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("Quitar pregunta/as de la seccion");
        pnlListaPregunta.add(btnEliminar);
        btnEliminar.setBounds(630, 110, 110, 40);

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LISTA DE PREGUNTAS");
        pnlListaPregunta.add(jLabel5);
        jLabel5.setBounds(240, 0, 280, 30);

        pnlDos.add(pnlListaPregunta);

        tabbedOperaciones.addTab("LISTA PREGUNTAS", pnlDos);

        pnlTres  = new  ImagenJPanel ("zzz.jpg");

        pnlCompTecPuesto.setOpaque(false);
        pnlCompTecPuesto.setPreferredSize(new java.awt.Dimension(770, 490));
        pnlCompTecPuesto.setLayout(null);
        pnlCompTecPuesto.add(txtDestreza);
        txtDestreza.setBounds(110, 300, 270, 30);

        jLabel7.setText("Destreza:");
        pnlCompTecPuesto.add(jLabel7);
        jLabel7.setBounds(40, 300, 110, 30);

        jLabel8.setText("       Alta:");
        pnlCompTecPuesto.add(jLabel8);
        jLabel8.setBounds(380, 310, 110, 20);

        txtAlta.setColumns(20);
        txtAlta.setLineWrap(true);
        txtAlta.setRows(5);
        jScrollPane3.setViewportView(txtAlta);

        pnlCompTecPuesto.add(jScrollPane3);
        jScrollPane3.setBounds(450, 280, 280, 70);

        jLabel9.setText("   Media:");
        pnlCompTecPuesto.add(jLabel9);
        jLabel9.setBounds(40, 390, 110, 20);

        txtMedia.setColumns(20);
        txtMedia.setLineWrap(true);
        txtMedia.setRows(5);
        jScrollPane4.setViewportView(txtMedia);

        pnlCompTecPuesto.add(jScrollPane4);
        jScrollPane4.setBounds(110, 360, 260, 70);

        jLabel10.setText("    Baja:");
        pnlCompTecPuesto.add(jLabel10);
        jLabel10.setBounds(390, 390, 110, 20);

        txtBaja.setColumns(20);
        txtBaja.setLineWrap(true);
        txtBaja.setRows(5);
        jScrollPane5.setViewportView(txtBaja);

        pnlCompTecPuesto.add(jScrollPane5);
        jScrollPane5.setBounds(450, 360, 280, 70);

        btnGuardarCompetencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Save.png"))); // NOI18N
        btnGuardarCompetencia.setText("Guardar");
        btnGuardarCompetencia.setToolTipText("Guardar informacion del Competencias");
        pnlCompTecPuesto.add(btnGuardarCompetencia);
        btnGuardarCompetencia.setBounds(290, 440, 110, 40);

        tblCompetencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(tblCompetencias);

        pnlCompTecPuesto.add(jScrollPane6);
        jScrollPane6.setBounds(40, 40, 700, 180);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("COMPETENCIAS TÉCNICAS DEL PUESTO");
        pnlCompTecPuesto.add(jLabel11);
        jLabel11.setBounds(230, 10, 340, 20);

        btnEliminarCompetencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/salir_1.png"))); // NOI18N
        btnEliminarCompetencias.setText("Eliminar");
        btnEliminarCompetencias.setToolTipText("Quitar Competencias Tecnicas del Sistema");
        pnlCompTecPuesto.add(btnEliminarCompetencias);
        btnEliminarCompetencias.setBounds(260, 230, 100, 40);

        btnNuevaCompetencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Edit.png"))); // NOI18N
        btnNuevaCompetencia.setText("Nuevo");
        btnNuevaCompetencia.setToolTipText("Ingresar Competencias Tecnicas de Puesto");
        pnlCompTecPuesto.add(btnNuevaCompetencia);
        btnNuevaCompetencia.setBounds(40, 230, 100, 40);

        btnEditarCompetencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/AGENDA1.png"))); // NOI18N
        btnEditarCompetencias.setText("Editar");
        btnEditarCompetencias.setToolTipText("Actualizar informacio de Competencias Tecnicas");
        pnlCompTecPuesto.add(btnEditarCompetencias);
        btnEditarCompetencias.setBounds(150, 230, 100, 40);

        btnCancelarTecnicas.setText("Cancelar");
        pnlCompTecPuesto.add(btnCancelarTecnicas);
        btnCancelarTecnicas.setBounds(410, 440, 100, 40);

        pnlTres.add(pnlCompTecPuesto);

        tabbedOperaciones.addTab("COMPETENCIAS TÉCNICAS DEL PUESTO", pnlTres);

        pnlCuatro  = new  ImagenJPanel ("zzz.jpg");

        pnlCompUniv.setOpaque(false);
        pnlCompUniv.setPreferredSize(new java.awt.Dimension(770, 490));
        pnlCompUniv.setLayout(null);

        btnNuevaCompetenciaUniversal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Edit.png"))); // NOI18N
        btnNuevaCompetenciaUniversal.setText("Nuevo");
        btnNuevaCompetenciaUniversal.setToolTipText("Agregar nuevas competencias universales");
        pnlCompUniv.add(btnNuevaCompetenciaUniversal);
        btnNuevaCompetenciaUniversal.setBounds(40, 230, 100, 40);

        btnEditarCompetenciaUniversal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/AGENDA1.png"))); // NOI18N
        btnEditarCompetenciaUniversal.setText("Editar");
        btnEditarCompetenciaUniversal.setToolTipText("Actualizar datos de Competencias Universales");
        pnlCompUniv.add(btnEditarCompetenciaUniversal);
        btnEditarCompetenciaUniversal.setBounds(150, 230, 100, 40);

        btnEliminarCompetenciaUniversal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/salir_1.png"))); // NOI18N
        btnEliminarCompetenciaUniversal.setText("Eliminar");
        pnlCompUniv.add(btnEliminarCompetenciaUniversal);
        btnEliminarCompetenciaUniversal.setBounds(260, 230, 100, 40);

        tblCompetenciasUniversales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(tblCompetenciasUniversales);

        pnlCompUniv.add(jScrollPane7);
        jScrollPane7.setBounds(40, 40, 700, 180);
        pnlCompUniv.add(txtDestrezaCompUniv);
        txtDestrezaCompUniv.setBounds(110, 300, 270, 30);

        txtMediaCompUniv.setColumns(20);
        txtMediaCompUniv.setLineWrap(true);
        txtMediaCompUniv.setRows(5);
        jScrollPane8.setViewportView(txtMediaCompUniv);

        pnlCompUniv.add(jScrollPane8);
        jScrollPane8.setBounds(110, 360, 260, 70);

        txtAltaCompUniv.setColumns(20);
        txtAltaCompUniv.setLineWrap(true);
        txtAltaCompUniv.setRows(5);
        jScrollPane9.setViewportView(txtAltaCompUniv);

        pnlCompUniv.add(jScrollPane9);
        jScrollPane9.setBounds(450, 280, 280, 70);

        txtBajaCompUniv.setColumns(20);
        txtBajaCompUniv.setLineWrap(true);
        txtBajaCompUniv.setRows(5);
        jScrollPane10.setViewportView(txtBajaCompUniv);

        pnlCompUniv.add(jScrollPane10);
        jScrollPane10.setBounds(450, 360, 280, 70);

        btnGuardarCompetenciaUniversal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Save.png"))); // NOI18N
        btnGuardarCompetenciaUniversal.setText("Guardar");
        btnGuardarCompetenciaUniversal.setToolTipText("Guardar informacion de  Competencias Universales");
        pnlCompUniv.add(btnGuardarCompetenciaUniversal);
        btnGuardarCompetenciaUniversal.setBounds(290, 440, 110, 40);

        jLabel12.setText("Destreza:");
        pnlCompUniv.add(jLabel12);
        jLabel12.setBounds(40, 300, 110, 30);

        jLabel13.setText("   Media:");
        pnlCompUniv.add(jLabel13);
        jLabel13.setBounds(40, 390, 110, 20);

        jLabel14.setText("    Baja:");
        pnlCompUniv.add(jLabel14);
        jLabel14.setBounds(390, 390, 110, 20);

        jLabel15.setText("       Alta:");
        pnlCompUniv.add(jLabel15);
        jLabel15.setBounds(380, 310, 110, 20);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("COMPETENCIAS UNIVERSALES");
        pnlCompUniv.add(jLabel16);
        jLabel16.setBounds(230, 10, 340, 20);

        btnCancelarUniversales.setText("Cancelar");
        pnlCompUniv.add(btnCancelarUniversales);
        btnCancelarUniversales.setBounds(410, 440, 100, 40);

        pnlCuatro.add(pnlCompUniv);

        tabbedOperaciones.addTab("COMPETENCIAS UNIVERSALES", pnlCuatro);

        pnlCinco  = new  ImagenJPanel ("zzz.jpg");

        pnlTrabajoEquipo.setOpaque(false);
        pnlTrabajoEquipo.setPreferredSize(new java.awt.Dimension(770, 490));
        pnlTrabajoEquipo.setLayout(null);

        tblTrabajoEquipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane11.setViewportView(tblTrabajoEquipo);

        pnlTrabajoEquipo.add(jScrollPane11);
        jScrollPane11.setBounds(40, 40, 700, 180);

        btnNuevoTrabajoEq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Edit.png"))); // NOI18N
        btnNuevoTrabajoEq.setText("Nuevo");
        btnNuevoTrabajoEq.setToolTipText("Agregar Destrezas de Trabajo enj equipo");
        pnlTrabajoEquipo.add(btnNuevoTrabajoEq);
        btnNuevoTrabajoEq.setBounds(40, 230, 100, 40);

        btnEditTrabEq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/AGENDA1.png"))); // NOI18N
        btnEditTrabEq.setText("Editar");
        btnEditTrabEq.setToolTipText("Actualizar informacion de Trabajo en Equipo");
        pnlTrabajoEquipo.add(btnEditTrabEq);
        btnEditTrabEq.setBounds(150, 230, 100, 40);

        btnElimTrabEq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/salir_1.png"))); // NOI18N
        btnElimTrabEq.setText("Eliminar");
        btnElimTrabEq.setToolTipText("Eliminar destrezas de Trabaipojo en Equ");
        pnlTrabajoEquipo.add(btnElimTrabEq);
        btnElimTrabEq.setBounds(260, 230, 100, 40);

        jLabel17.setText("Descripcion:");
        pnlTrabajoEquipo.add(jLabel17);
        jLabel17.setBounds(20, 300, 110, 20);
        pnlTrabajoEquipo.add(txtDescripcionTrabEq);
        txtDescripcionTrabEq.setBounds(110, 300, 280, 30);

        txtAltaTrabEquipo.setColumns(20);
        txtAltaTrabEquipo.setLineWrap(true);
        txtAltaTrabEquipo.setRows(5);
        jScrollPane12.setViewportView(txtAltaTrabEquipo);

        pnlTrabajoEquipo.add(jScrollPane12);
        jScrollPane12.setBounds(450, 280, 280, 70);

        txtMediaTrabEquipo.setColumns(20);
        txtMediaTrabEquipo.setLineWrap(true);
        txtMediaTrabEquipo.setRows(5);
        jScrollPane13.setViewportView(txtMediaTrabEquipo);

        pnlTrabajoEquipo.add(jScrollPane13);
        jScrollPane13.setBounds(110, 360, 260, 70);

        txtBajaTrabEquipo.setColumns(20);
        txtBajaTrabEquipo.setLineWrap(true);
        txtBajaTrabEquipo.setRows(5);
        jScrollPane14.setViewportView(txtBajaTrabEquipo);

        pnlTrabajoEquipo.add(jScrollPane14);
        jScrollPane14.setBounds(450, 360, 280, 70);

        jLabel18.setText("    Baja:");
        pnlTrabajoEquipo.add(jLabel18);
        jLabel18.setBounds(390, 390, 110, 20);

        jLabel19.setText("       Alta:");
        pnlTrabajoEquipo.add(jLabel19);
        jLabel19.setBounds(380, 310, 110, 20);

        jLabel20.setText("   Media:");
        pnlTrabajoEquipo.add(jLabel20);
        jLabel20.setBounds(40, 390, 110, 20);

        btnGuardarTrabEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Save.png"))); // NOI18N
        btnGuardarTrabEquipo.setText("Guardar");
        pnlTrabajoEquipo.add(btnGuardarTrabEquipo);
        btnGuardarTrabEquipo.setBounds(290, 440, 110, 40);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("TRABAJO EN EQUIPO");
        pnlTrabajoEquipo.add(jLabel21);
        jLabel21.setBounds(230, 10, 340, 20);

        btnCancelarTrabajo.setText("Cancelar");
        pnlTrabajoEquipo.add(btnCancelarTrabajo);
        btnCancelarTrabajo.setBounds(410, 440, 100, 40);

        pnlCinco.add(pnlTrabajoEquipo);

        tabbedOperaciones.addTab("TRABAJO EN EQUIPO", pnlCinco);

        add(tabbedOperaciones, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnCancelarPreg;
    private javax.swing.JButton btnCancelarTecnicas;
    private javax.swing.JButton btnCancelarTrabajo;
    private javax.swing.JButton btnCancelarUniversales;
    private javax.swing.JButton btnEditTrabEq;
    private javax.swing.JButton btnEditarCompetenciaUniversal;
    private javax.swing.JButton btnEditarCompetencias;
    private javax.swing.JButton btnEditarSeccion;
    private javax.swing.JButton btnElimTrabEq;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarCompetenciaUniversal;
    private javax.swing.JButton btnEliminarCompetencias;
    private javax.swing.JButton btnGuardarCompetencia;
    private javax.swing.JButton btnGuardarCompetenciaUniversal;
    private javax.swing.JButton btnGuardarPregunta;
    private javax.swing.JButton btnGuardarTrabEquipo;
    private javax.swing.JButton btnNuevaCompetencia;
    private javax.swing.JButton btnNuevaCompetenciaUniversal;
    private javax.swing.JButton btnNuevaSeccion;
    private javax.swing.JButton btnNuevoTrabajoEq;
    public static javax.swing.JComboBox cbSeccion;
    public static javax.swing.JComboBox cbSeccionLstPreg;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblEscogerSeccion;
    private javax.swing.JLabel lblNroResp;
    private javax.swing.JLabel lblNuevaPreg;
    private javax.swing.JPanel pnlCinco;
    private javax.swing.JPanel pnlCompTecPuesto;
    private javax.swing.JPanel pnlCompUniv;
    private javax.swing.JPanel pnlCuatro;
    private javax.swing.JPanel pnlDos;
    private javax.swing.JPanel pnlListaPregunta;
    private javax.swing.JPanel pnlNuevaPregunta;
    private javax.swing.JPanel pnlRespuestas;
    private javax.swing.JPanel pnlTrabajoEquipo;
    private javax.swing.JPanel pnlTres;
    private javax.swing.JPanel pnlUno;
    private javax.swing.JSpinner spNroPreg;
    private javax.swing.JTabbedPane tabbedOperaciones;
    private javax.swing.JTable tblCompetencias;
    public static javax.swing.JTable tblCompetenciasUniversales;
    public static javax.swing.JTable tblPreguntas;
    public static javax.swing.JTable tblTrabajoEquipo;
    private javax.swing.JTextArea txtAlta;
    private javax.swing.JTextArea txtAltaCompUniv;
    private javax.swing.JTextArea txtAltaTrabEquipo;
    private javax.swing.JTextArea txtBaja;
    private javax.swing.JTextArea txtBajaCompUniv;
    private javax.swing.JTextArea txtBajaTrabEquipo;
    private javax.swing.JTextField txtDescripcionTrabEq;
    private javax.swing.JTextField txtDestreza;
    private javax.swing.JTextField txtDestrezaCompUniv;
    private javax.swing.JTextArea txtMedia;
    private javax.swing.JTextArea txtMediaCompUniv;
    private javax.swing.JTextArea txtMediaTrabEquipo;
    private javax.swing.JTextField txtNuevaPregunt;
    // End of variables declaration//GEN-END:variables
    //**********************************************
    //*         PANEL DE PREGUNTAS                 *
    //**********************************************

    /**
     * @return the txtNuevaPregunt
     */
    public javax.swing.JTextField getTxtNuevaPregunt() {
        return txtNuevaPregunt;
    }

    /**
     * @return the cbSeccion
     */
    public javax.swing.JComboBox getCbSeccion() {
        return cbSeccion;
    }

    /**
     * @return the spNroPreg
     */
    public javax.swing.JSpinner getSpNroPreg() {
        return spNroPreg;
    }

    /**
     * @return the pnlRespuestas
     */
    public javax.swing.JPanel getPnlRespuestas() {
        return pnlRespuestas;
    }

    /**
     * @return the cbSeccionLstPreg
     */
    public javax.swing.JComboBox getCbSeccionLstPreg() {
        return cbSeccionLstPreg;
    }

    /**
     * @return the tblPreguntas
     */
    public javax.swing.JTable getTblPreguntas() {
        return tblPreguntas;
    }

    //**********************************************
    //*   PANEL COMPETENCIAS TECNICAS              *
    //**********************************************
    /**
     * @return the btnGuardarCompetencia
     */
    public javax.swing.JButton getBtnGuardarCompetencia() {
        return btnGuardarCompetencia;
    }

    /**
     * @return the txtAlta
     */
    public javax.swing.JTextArea getTxtAlta() {
        return txtAlta;
    }

    /**
     * @return the txtBaja
     */
    public javax.swing.JTextArea getTxtBaja() {
        return txtBaja;
    }

    /**
     * @return the txtDestreza
     */
    public javax.swing.JTextField getTxtDestreza() {
        return txtDestreza;
    }

    /**
     * @return the txtMedia
     */
    public javax.swing.JTextArea getTxtMedia() {
        return txtMedia;
    }

    /**
     * @return the tblCompetencias
     */
    public javax.swing.JTable getTblCompetencias() {
        return tblCompetencias;
    }

    //**********************************************
    //*   PANEL COMPETENCIAS UNIVERSALES           *
    //**********************************************
    /**
     * @return the btnGuardarCompetenciaUniversal
     */
    public javax.swing.JButton getBtnGuardarCompetenciaUniversal() {
        return btnGuardarCompetenciaUniversal;
    }

    /**
     * @return the btnGuardarTrabEquipo
     */
    public javax.swing.JButton getBtnGuardarTrabEquipo() {
        return btnGuardarTrabEquipo;
    }

    /**
     * @return the txtAltaCompUniv
     */
    public javax.swing.JTextArea getTxtAltaCompUniv() {
        return txtAltaCompUniv;
    }

    /**
     * @return the txtBajaCompUniv
     */
    public javax.swing.JTextArea getTxtBajaCompUniv() {
        return txtBajaCompUniv;
    }

    /**
     * @return the txtDestrezaCompUniv
     */
    public javax.swing.JTextField getTxtDestrezaCompUniv() {
        return txtDestrezaCompUniv;
    }

    /**
     * @return the txtMediaCompUniv
     */
    public javax.swing.JTextArea getTxtMediaCompUniv() {
        return txtMediaCompUniv;
    }

    /**
     * @return the tblCompetenciasUniversales
     */
    public javax.swing.JTable getTblCompetenciasUniversales() {
        return tblCompetenciasUniversales;
    }

    //**********************************************
    //*   PANEL TRABAJO EN EQUIPO                  *
    //**********************************************
    /**
     * @return the txtAltaTrabEquipo
     */
    public javax.swing.JTextArea getTxtAltaTrabEquipo() {
        return txtAltaTrabEquipo;
    }

    /**
     * @return the txtBajaTrabEquipo
     */
    public javax.swing.JTextArea getTxtBajaTrabEquipo() {
        return txtBajaTrabEquipo;
    }

    /**
     * @return the txtDescripcionTrabEq
     */
    public javax.swing.JTextField getTxtDescripcionTrabEq() {
        return txtDescripcionTrabEq;
    }

    /**
     * @return the txtMediaTrabEquipo
     */
    public javax.swing.JTextArea getTxtMediaTrabEquipo() {
        return txtMediaTrabEquipo;
    }

    /**
     * @return the tblTrabajoEquipo
     */
    public javax.swing.JTable getTblTrabajoEquipo() {
        return tblTrabajoEquipo;
    }

    /**
     * @return the pnlCompTecPuesto
     */
    public javax.swing.JPanel getPnlCompTecPuesto() {
        return pnlCompTecPuesto;
    }

    /**
     * @return the pnlCompUniv
     */
    public javax.swing.JPanel getPnlCompUniv() {
        return pnlCompUniv;
    }

    /**
     * @return the pnlTrabajoEquipo
     */
    public javax.swing.JPanel getPnlTrabajoEquipo() {
        return pnlTrabajoEquipo;
    }

    /**
     * @return the btnCancelarPreg
     */
    public javax.swing.JButton getBtnCancelarPreg() {
        return btnCancelarPreg;
    }

    /**
     * @return the btnCancelarTecnicas
     */
    public javax.swing.JButton getBtnCancelarTecnicas() {
        return btnCancelarTecnicas;
    }

    /**
     * @return the btnCancelarTrabajo
     */
    public javax.swing.JButton getBtnCancelarTrabajo() {
        return btnCancelarTrabajo;
    }

    /**
     * @return the btnCancelarUniversales
     */
    public javax.swing.JButton getBtnCancelarUniversales() {
        return btnCancelarUniversales;
    }
    
    

    class GestorControladorOperaciones implements ActionListener, ChangeListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            //**********************************************
            //*         PANEL DE PREGUNTAS                 *
            //**********************************************
            if (e.getSource() == btnNuevaSeccion) {
                cp.guardaSeccion();
            } else if (e.getSource() == btnAplicar) {
                ControladorPreguntas.btnPresionado = true;
                int val = Integer.parseInt(String.valueOf(getSpNroPreg().getValue()));
                cp.ponePosibleRptas(val);
            } else if (e.getSource() == btnGuardarPregunta) {
                if (cbSeccion.getSelectedIndex() != -1) {
                    if (!getTxtNuevaPregunt().getText().isEmpty()) {
                        JTextField t = new JTextField();
                        getTxtNuevaPregunt().setBorder(t.getBorder());
                        if (ControladorPreguntas.btnPresionado) {
                            if (cp.compruebatextos()) {
                                if (cp.compruebaSeleccionados()) {
                                    int i = JOptionPane.showConfirmDialog(null, "¿Desea guardar la pregunta?", "Guardar", JOptionPane.YES_NO_OPTION);
                                    if (i == JOptionPane.YES_OPTION) {
                                        cp.guardaPregunta();
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "Debe seleccionar una opcion para la respuesta");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Existen respuestas sin especificar");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Debe describir las opciones de respuesta para la pregunta");
                        }
                        t = null;
                    } else {
                        getTxtNuevaPregunt().setBorder(new EtchedBorder(Color.red, Color.pink));
                        JOptionPane.showMessageDialog(null, "Debe ingresar la pregunta");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No hay seccion seleccionada");
                }
            } else if (e.getSource() == cbSeccionLstPreg) {
                cp.selecSeccion();
            } else if (e.getSource() == btnEditarSeccion) {
                cp.editaSeccion();
            } else if (e.getSource() == btnEliminar) {
                if (cp.isRowSelectedTblPreg()) {
                    int i = JOptionPane.showConfirmDialog(null, "¿Desea eliminar la pregunta seleccionada?", "Eliminar", JOptionPane.YES_NO_OPTION);
                    if (i == JOptionPane.YES_OPTION) {
                        cp.eliminarPregunta();
                    }
                } else {
                    Mensaje.filaNoSeleccionada();
                }
            }else if(e.getSource()== btnCancelarPreg){
                cp.cancelaPregunta();
            } 
            //**********************************************
            //*   PANEL COMPETENCIAS TECNICAS              *
            //**********************************************
            else if (e.getSource() == btnNuevaCompetencia) {
                cctp.nuevaCompetenciaTecnica();
            } else if (e.getSource() == btnGuardarCompetencia) {
                if (!cctp.hayVacios()) {
                    if (btnGuardarCompetencia.getText().equals("Guardar")) {
                        int i = JOptionPane.showConfirmDialog(null, "¿Desea guardar la Competencia Tecnica?", "Guardar", JOptionPane.YES_NO_OPTION);
                        if (i == JOptionPane.YES_OPTION) {
                            cctp.guardaCompetenciaTecnica();
                        }
                    } else if (btnGuardarCompetencia.getText().equals("Modificar")) {
                        int i = JOptionPane.showConfirmDialog(null, "¿Desea modificar la Competencia Tecnica?", "Modificar", JOptionPane.YES_NO_OPTION);
                        if (i == JOptionPane.YES_OPTION) {
                            cctp.editarCompetenciaTecnica();
                        }
                    }
                } else {
                    Mensaje.camposVacios();
                }
            } else if (e.getSource() == btnEditarCompetencias) {
                if (cctp.isRowSelectedCompTec()) {
                    cctp.getCompetenciaTecnica();
                } else {
                    Mensaje.filaNoSeleccionada();
                }
            } else if (e.getSource() == btnEliminarCompetencias) {
                int i = JOptionPane.showConfirmDialog(null, "¿Desea eliminar la Competencia Técnica?", "Eliminar", JOptionPane.YES_NO_OPTION);
                if (i == JOptionPane.YES_OPTION) {
                    cctp.eliminarCompetenciaTecnica();
                }
            } else if(e.getSource()==btnCancelarTecnicas){
                cctp.nuevaCompetenciaTecnica();
                cctp.poneEnables(false);
                btnGuardarCompetencia.setText("Guardar");
            }
            
            //**********************************************
            //*   PANEL COMPETENCIAS UNIVERSAL             *
            //**********************************************
            else if (e.getSource() == btnNuevaCompetenciaUniversal) {
                ccu.nuevaCompetenciaUniversal();
            } else if (e.getSource() == btnGuardarCompetenciaUniversal) {
                if (!ccu.hayVaciosUniv()) {
                    if (btnGuardarCompetenciaUniversal.getText().equals("Guardar")) {
                        int i = JOptionPane.showConfirmDialog(null, "¿Desea guardar la Competencia Universal?", "Guardar", JOptionPane.YES_NO_OPTION);
                        if (i == JOptionPane.YES_OPTION) {
                            ccu.guardaCompetenciaUniversal();
                        }
                    } else if (btnGuardarCompetenciaUniversal.getText().equals("Modificar")) {
                        int i = JOptionPane.showConfirmDialog(null, "¿Desea modificar la Competencia Universal?", "Modificar", JOptionPane.YES_NO_OPTION);
                        if (i == JOptionPane.YES_OPTION) {
                            ccu.editarCompetenciaUniversal();
                        }
                    }
                } else {
                    Mensaje.camposVacios();
                }
            } else if (e.getSource() == btnEditarCompetenciaUniversal) {
                if (ccu.isRowSelectedCompUniver()) {
                    ccu.getCompetenciaUniversal();
                } else {
                    Mensaje.filaNoSeleccionada();
                }
            } else if (e.getSource() == btnEliminarCompetenciaUniversal) {
                int i = JOptionPane.showConfirmDialog(null, "¿Desea eliminar la Competencia Universal?", "Eliminar", JOptionPane.YES_NO_OPTION);
                if (i == JOptionPane.YES_OPTION) {
                    ccu.eliminarCompetenciaUniversal();
                }
            }else if(e.getSource()== btnCancelarUniversales){
                ccu.nuevaCompetenciaUniversal();
                ccu.poneEnablesUniv(false);
                btnGuardarCompetenciaUniversal.setText("Guardar");
            }
            //**********************************************
            //*   PANEL TRABAJO EN EQUIPO                  *
            //**********************************************
            else if (e.getSource() == btnNuevoTrabajoEq) {
                cte.nuevoTrabajoEquipo();
            } else if (e.getSource() == btnGuardarTrabEquipo) {
                if (!cte.hayVaciosTrab()) {
                    if (btnGuardarTrabEquipo.getText().equals("Guardar")) {
                        int i = JOptionPane.showConfirmDialog(null, "¿Desea guardar el Trabajo de Equipo?", "Guardar", JOptionPane.YES_NO_OPTION);
                        if (i == JOptionPane.YES_OPTION) {
                            cte.guardaTrabEquipo();
                        }
                    } else if (btnGuardarTrabEquipo.getText().equals("Modificar")) {
                        int i = JOptionPane.showConfirmDialog(null, "¿Desea modificar el Trabajo de Equipo?", "Modificar", JOptionPane.YES_NO_OPTION);
                        if (i == JOptionPane.YES_OPTION) {
                            cte.editarTrabajoEquipo();
                        }
                    }
                } else {
                    Mensaje.camposVacios();
                }
            } else if (e.getSource() == btnEditTrabEq) {
                if (cte.isRowSelectedTrabEquipo()) {
                    cte.getTrabajoEquipo();
                } else {
                    Mensaje.filaNoSeleccionada();
                }
            } else if (e.getSource() == btnElimTrabEq) {
                int i = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el Trabajo en Equipo?", "Eliminar", JOptionPane.YES_NO_OPTION);
                if (i == JOptionPane.YES_OPTION) {
                    cte.eliminarTrabajoEquipo();
                }
            }else if(e.getSource() == btnCancelarTrabajo){
                cte.nuevoTrabajoEquipo();
                cte.poneEnablesTrabEquip(false);
                btnGuardarTrabEquipo.setText("Guardar");
            }
        }

        @Override
        public void stateChanged(ChangeEvent e) {
            if (tabbedOperaciones.getSelectedIndex() == 1) {
                cp.poneCbSeccionLst();
            } else if (tabbedOperaciones.getSelectedIndex() == 2) {
                cctp.actualizaTabla();
            } else if (tabbedOperaciones.getSelectedIndex() == 3) {
                ccu.actualizaTablaUnivers();
            } else if (tabbedOperaciones.getSelectedIndex() == 4) {
                cte.actualizaTablaTrabEquipo();
            }
        }
    }
}