/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.servicios;

import controlador.acciones.servicios.ControladorRecordatorio;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import vista.FrmPrincipal;
import vista.modelo.Calendario;
import vista.modelo.OperacionesVarias;
import static vista.paneles.servicios.PnlServicios.lblMes;

/**
 *
 * @author francisco
 */
public class DialogoCalendarioRecor extends javax.swing.JDialog {

    private static DialogoCalendarioRecor dcr;
    private ControladorRecordatorio cr;
    private GestorEventosCalendario gec;

    /**
     * Creates new form DialogoCalendarioRecor
     */
    private DialogoCalendarioRecor() {
        initComponents();
        poneFechaHora();
        OperacionesVarias.ponerTablaCalendario(tblDiasMes, lblMes);
        cr = new ControladorRecordatorio(this);
        gec = new GestorEventosCalendario();
        poneEventos();
    }

    public static DialogoCalendarioRecor getInstance() {
        if (dcr == null) {
            dcr = new DialogoCalendarioRecor();
        }
        return dcr;
    }

    private void poneEventos() {
        btnAtras.addActionListener(gec);
        btnSiguiente.addActionListener(gec);
        tblDiasMes.addMouseListener(gec);
    }

    private void poneFechaHora() {
        String s = FrmPrincipal.lblHora.getText();
        String l[] = s.split(",");
        String fecha = l[0].trim();
        String hora = l[1].trim();
        lblFecha.setText(fecha);
        lblHora.setText(hora);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCalendario = new javax.swing.JPanel();
        lblTxtFecha = new javax.swing.JLabel();
        scrollCalendario = new javax.swing.JScrollPane();
        tblDiasMes = new javax.swing.JTable();
        lblMes = new javax.swing.JLabel();
        lblTxtHora = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        pnlCalendario.setOpaque(false);
        pnlCalendario.setPreferredSize(new java.awt.Dimension(700, 400));
        pnlCalendario.setLayout(null);

        lblTxtFecha.setText("Fecha Actual:");
        pnlCalendario.add(lblTxtFecha);
        lblTxtFecha.setBounds(110, 300, 120, 40);

        tblDiasMes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        tblDiasMes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Domingo", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDiasMes.setRowHeight(25);
        tblDiasMes.setRowSelectionAllowed(false);
        scrollCalendario.setViewportView(tblDiasMes);

        pnlCalendario.add(scrollCalendario);
        scrollCalendario.setBounds(60, 120, 590, 180);

        lblMes.setBackground(new java.awt.Color(51, 51, 255));
        lblMes.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        lblMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlCalendario.add(lblMes);
        lblMes.setBounds(140, 70, 440, 40);

        lblTxtHora.setText("Hora:");
        pnlCalendario.add(lblTxtHora);
        lblTxtHora.setBounds(470, 300, 60, 40);

        btnSiguiente.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btnSiguiente.setText(">>");
        btnSiguiente.setToolTipText("Siguiente");
        pnlCalendario.add(btnSiguiente);
        btnSiguiente.setBounds(590, 70, 66, 40);

        btnAtras.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btnAtras.setText("<<");
        btnAtras.setToolTipText("Anterior");
        pnlCalendario.add(btnAtras);
        btnAtras.setBounds(60, 70, 75, 40);

        lblHora.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        pnlCalendario.add(lblHora);
        lblHora.setBounds(510, 300, 140, 40);

        lblFecha.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        pnlCalendario.add(lblFecha);
        lblFecha.setBounds(220, 300, 240, 40);

        btnCerrar.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/button_cancel.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        pnlCalendario.add(btnCerrar);
        btnCerrar.setBounds(310, 357, 100, 40);

        getContentPane().add(pnlCalendario);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-736)/2, (screenSize.height-441)/2, 736, 441);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    public static javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblTxtFecha;
    private javax.swing.JLabel lblTxtHora;
    private javax.swing.JPanel pnlCalendario;
    private javax.swing.JScrollPane scrollCalendario;
    private javax.swing.JTable tblDiasMes;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tblDiasMes
     */
    public javax.swing.JTable getTblDiasMes() {
        return tblDiasMes;
    }

    class GestorEventosCalendario extends MouseAdapter implements ActionListener {

        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getClickCount() == 2) {
                cr.abreDialogoRecord();
            }
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == btnAtras) {
                Calendario.mesAnterior(getTblDiasMes(), lblMes);
            } else if (e.getSource() == btnSiguiente) {
                Calendario.mesSiguiente(getTblDiasMes(), lblMes);
            }
        }
    }
}
