package vista.paneles.evaluacion;

import controlador.propiedades.Propiedades;
import java.util.Properties;
import modelo.usuario.Queja;

/**
 *
 * @author jenny
 */
public class PnlQuejas extends javax.swing.JPanel {

    private int porcentaje = 0;

    /**
     * Creates new form PnlQuejas
     */
    public PnlQuejas(Queja q) {
        initComponents();
        txtNombPersona.setText(q.getNombreDenun());
        txtDescrip.setText(q.getDetalle());
        txtNroForm.setText(q.getNroForm());
        txtAplicDesc.setText("SI");
        Propiedades p = new Propiedades();
        Properties prop = p.getProperties("controlador/propiedades/factores.properties");
        txtPorcentaje.setText(prop.getProperty("APLICA"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPorcentaje = new javax.swing.JTextField();
        txtNombPersona = new javax.swing.JTextField();
        txtDescrip = new javax.swing.JTextField();
        txtNroForm = new javax.swing.JTextField();
        txtAplicDesc = new javax.swing.JTextField();

        setLayout(null);

        txtPorcentaje.setEditable(false);
        add(txtPorcentaje);
        txtPorcentaje.setBounds(790, 0, 120, 30);

        txtNombPersona.setEditable(false);
        add(txtNombPersona);
        txtNombPersona.setBounds(0, 0, 180, 30);

        txtDescrip.setEditable(false);
        add(txtDescrip);
        txtDescrip.setBounds(180, 0, 350, 30);

        txtNroForm.setEditable(false);
        add(txtNroForm);
        txtNroForm.setBounds(530, 0, 90, 30);
        add(txtAplicDesc);
        txtAplicDesc.setBounds(620, 0, 170, 30);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtAplicDesc;
    private javax.swing.JTextField txtDescrip;
    private javax.swing.JTextField txtNombPersona;
    private javax.swing.JTextField txtNroForm;
    private javax.swing.JTextField txtPorcentaje;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the porcentaje
     */
    public int getPorcentaje() {
        return porcentaje;
    }

    /**
     * @return the cbAplicDesc
     */
    public javax.swing.JTextField getCbAplicDesc() {
        return txtAplicDesc;
    }

    /**
     * @return the txtDescrip
     */
    public javax.swing.JTextField getTxtDescrip() {
        return txtDescrip;
    }

    /**
     * @return the txtNombPersona
     */
    public javax.swing.JTextField getTxtNombPersona() {
        return txtNombPersona;
    }

    /**
     * @return the txtNroForm
     */
    public javax.swing.JTextField getTxtNroForm() {
        return txtNroForm;
    }

    /**
     * @return the txtPorcentaje
     */
    public javax.swing.JTextField getTxtPorcentaje() {
        return txtPorcentaje;
    }

}
