/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.evaluacion;

import controlador.basedatos.OperacionesBD;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.evaluacion.Efectos;
import vista.modelo.Mensaje;

/**
 *
 * @author francisco
 */
public class DialogEfectos extends javax.swing.JDialog {

    private static DialogEfectos de = null;
    private Efectos efec;
    private ArrayList<Efectos> efectos;
    private String nombreEf;

    /**
     * Creates new form DialogEfectos
     */
    private DialogEfectos() {
        this.setModal(true);
        this.initComponents();
        this.llenaCombo();
    }

    public static DialogEfectos getInstance() {
        if (de == null) {
            de = new DialogEfectos();
        }
        return de;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIneficienteCalificacion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBuenaCalificacion = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDeficienteCalificacion = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbNombres = new javax.swing.JComboBox();
        btnNuevoNombre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("INEFICIENTE CALIFICACIÓN:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 310, 170, 17);

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        jLabel2.setText("EFECTOS EVALUACIÓN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 10, 140, 17);

        jLabel3.setText("BUENA CALIFICACIÓN:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 90, 140, 17);

        jLabel4.setText("DEFICIENTE CALIFICACIÓN:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 200, 170, 17);

        txtIneficienteCalificacion.setColumns(20);
        txtIneficienteCalificacion.setRows(5);
        jScrollPane1.setViewportView(txtIneficienteCalificacion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 330, 380, 87);

        txtBuenaCalificacion.setColumns(20);
        txtBuenaCalificacion.setRows(5);
        jScrollPane2.setViewportView(txtBuenaCalificacion);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 110, 380, 87);

        txtDeficienteCalificacion.setColumns(20);
        txtDeficienteCalificacion.setRows(5);
        jScrollPane3.setViewportView(txtDeficienteCalificacion);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 220, 380, 87);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(200, 430, 100, 40);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(90, 430, 100, 40);

        jLabel5.setText("NOMBRE:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(9, 37, 70, 30);

        cbNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNombresActionPerformed(evt);
            }
        });
        getContentPane().add(cbNombres);
        cbNombres.setBounds(80, 40, 220, 30);

        btnNuevoNombre.setText("N");
        btnNuevoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoNombreActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevoNombre);
        btnNuevoNombre.setBounds(310, 40, 50, 30);

        setSize(new java.awt.Dimension(410, 512));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (nombreEscogido()) {
            if (!hayVacios()) {
                if (!OperacionesBD.existe("Efecto", "nombre", nombreEf)) {
                    efec = new Efectos();
                    efec.setNombre(nombreEf);
                    efec.setBueno(txtBuenaCalificacion.getText());
                    efec.setDeficiente(txtDeficienteCalificacion.getText());
                    efec.setIneficiente(txtIneficienteCalificacion.getText());
                    if (OperacionesBD.guardar(efec)) {
                        Mensaje.datosGuardados();
                    }
                } else {
                    efec = efectos.get(cbNombres.getSelectedIndex());
                    efec.setNombre(nombreEf);
                    efec.setBueno(txtBuenaCalificacion.getText());
                    efec.setDeficiente(txtDeficienteCalificacion.getText());
                    efec.setIneficiente(txtIneficienteCalificacion.getText());
                    if (OperacionesBD.modificar(efec)) {
                        Mensaje.datosGuardados();
                    }
                }
            } else {
                Mensaje.camposVacios();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe escoger el nombre del Efecto");
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        //despues del dispose al parecer llama al constructor de nuevo
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoNombreActionPerformed
        nombreEf = JOptionPane.showInputDialog("Ingrese el nombre del Efecto");
        cbNombres.addItem(nombreEf);
    }//GEN-LAST:event_btnNuevoNombreActionPerformed

    private void cbNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNombresActionPerformed
        if (cbNombres.getSelectedIndex() != -1) {
            nombreEf = cbNombres.getSelectedItem().toString();
        }
    }//GEN-LAST:event_cbNombresActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevoNombre;
    private javax.swing.JComboBox cbNombres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtBuenaCalificacion;
    private javax.swing.JTextArea txtDeficienteCalificacion;
    private javax.swing.JTextArea txtIneficienteCalificacion;
    // End of variables declaration//GEN-END:variables

    private void llenaCombo() {
        efectos = (ArrayList<Efectos>) OperacionesBD.listar("Efectos");
        cbNombres.removeAllItems();
        cbNombres.addItem("Sin Efecto");
        if (!efectos.isEmpty()) {
            for (Efectos e : efectos) {
                cbNombres.addItem(e.getNombre());
            }
        }
    }

    private boolean hayVacios() {
        if (txtBuenaCalificacion.getText().isEmpty()
                || txtDeficienteCalificacion.getText().isEmpty()
                || txtIneficienteCalificacion.getText().isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean nombreEscogido() {
        if (cbNombres.getSelectedIndex() == 0) {
            return false;
        }
        return true;
    }
}
