/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.evaluacion;

import controlador.acciones.evaluaciones.ControladorTest;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import modelo.pregunta.Pregunta;
import vista.modelo.ImagenJPanel;

/**
 *
 * @author francisco
 */
public class DialogTest extends javax.swing.JDialog {

    private final ArrayList<Pregunta> preguntas;
    private final ControladorTest ct;
    private final GestorControladorTest gct;

  

    /**
     * Creates new form DialogTest
     *
     * @param preg
     */
    public DialogTest(ArrayList<Pregunta> preg) {
        
        initComponents();
        setModal(true);
        preguntas = preg;
        ct = new ControladorTest(this);
        gct = new GestorControladorTest();
        ct.ponePreguntas();
        ct.llenaPaneles();
        
        poneEventos();
         
        
    }

    private void poneEventos() {
        btnCalificar.addActionListener(gct);
        btnCancelar.addActionListener(gct);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTest = new javax.swing.JScrollPane();
        pnlTest = new javax.swing.JPanel();
        btnCalificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        scrollTest.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlTest.setBackground(new java.awt.Color(254, 254, 254));
        pnlTest.setVerifyInputWhenFocusTarget(false);
        pnlTest.setLayout(new javax.swing.BoxLayout(pnlTest, javax.swing.BoxLayout.Y_AXIS));
        scrollTest.setViewportView(pnlTest);

        getContentPane().add(scrollTest);
        scrollTest.setBounds(20, 17, 1000, 510);

        btnCalificar.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnCalificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Select.png"))); // NOI18N
        btnCalificar.setText("Calificar");
        btnCalificar.setToolTipText("Presione calificar para mostrar los resultados del Test seleccionado");
        btnCalificar.setPreferredSize(new java.awt.Dimension(100, 35));
        getContentPane().add(btnCalificar);
        btnCalificar.setBounds(400, 540, 120, 40);

        btnCancelar.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/salir_1.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("");
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(530, 540, 120, 40);

        setSize(new java.awt.Dimension(1045, 617));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalificar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel pnlTest;
    private javax.swing.JScrollPane scrollTest;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnCalificar
     */
    public javax.swing.JButton getBtnCalificar() {
        return btnCalificar;
    }

    /**
     * @return the pnlTest
     */
    public javax.swing.JPanel getPnlTest() {
        return pnlTest;
    }

    /**
     * @return the preguntas
     */
    public ArrayList<Pregunta> getPreguntas() {
        return preguntas;
    }

    class GestorControladorTest implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == btnCalificar) {
                ct.califica();
            } else if (e.getSource() == btnCancelar) {
                dispose();
            }
        }
    }

}
