/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista.paneles.evaluacion;

/**
 *
 * @author francisco
 */
public class DialogResultTest extends javax.swing.JDialog {

    /**
     * Creates new form DialogResultEval
     */
    public DialogResultTest() {        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTestResult = new javax.swing.JScrollPane();
        pnlTestResult = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        scrollTestResult.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlTestResult.setOpaque(false);
        pnlTestResult.setVerifyInputWhenFocusTarget(false);
        pnlTestResult.setLayout(new javax.swing.BoxLayout(pnlTestResult, javax.swing.BoxLayout.Y_AXIS));
        scrollTestResult.setViewportView(pnlTestResult);

        getContentPane().add(scrollTestResult);
        scrollTestResult.setBounds(20, 17, 1000, 510);

        btnAceptar.setText("Aceptar");
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(480, 534, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JPanel pnlTestResult;
    private javax.swing.JScrollPane scrollTestResult;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the pnlTestResult
     */
    public javax.swing.JPanel getPnlTestResult() {
        return pnlTestResult;
    }

}
