/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.evaluacion;

/**
 *
 * @author francisco
 */
public class FrmEvalOld extends javax.swing.JDialog {

    /**
     * Creates new form FrmEvalOld
     */
    public FrmEvalOld(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosServidor = new javax.swing.JPanel();
        lblEscServid = new javax.swing.JLabel();
        cbServidores = new javax.swing.JComboBox();
        pnlIntDatosServ = new javax.swing.JPanel();
        lblPuestoDesemp = new javax.swing.JLabel();
        txtPuestoDesemp = new javax.swing.JTextField();
        lblApellNomb = new javax.swing.JLabel();
        txtApellidosNombres = new javax.swing.JTextField();
        lblTituloProf = new javax.swing.JLabel();
        txttituloProf = new javax.swing.JTextField();
        lblApellNombJefe = new javax.swing.JLabel();
        cbJefeInmediato = new javax.swing.JComboBox();
        btnGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        pnlDatosServidor.setOpaque(false);
        pnlDatosServidor.setPreferredSize(new java.awt.Dimension(750, 500));
        pnlDatosServidor.setLayout(null);

        lblEscServid.setText("Escoja el servidor:");
        pnlDatosServidor.add(lblEscServid);
        lblEscServid.setBounds(130, 90, 140, 12);
        pnlDatosServidor.add(cbServidores);
        cbServidores.setBounds(260, 80, 400, 30);

        pnlIntDatosServ.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DEL SERVIDOR"));
        pnlIntDatosServ.setOpaque(false);
        pnlIntDatosServ.setLayout(null);

        lblPuestoDesemp.setText("  Puesto que desempeña:");
        pnlIntDatosServ.add(lblPuestoDesemp);
        lblPuestoDesemp.setBounds(80, 50, 200, 30);
        pnlIntDatosServ.add(txtPuestoDesemp);
        txtPuestoDesemp.setBounds(270, 50, 410, 30);

        lblApellNomb.setText("  Apellidos y Nombres:");
        pnlIntDatosServ.add(lblApellNomb);
        lblApellNomb.setBounds(100, 20, 160, 30);
        pnlIntDatosServ.add(txtApellidosNombres);
        txtApellidosNombres.setBounds(270, 20, 410, 30);

        lblTituloProf.setText("   Título o Profesion:");
        pnlIntDatosServ.add(lblTituloProf);
        lblTituloProf.setBounds(110, 80, 160, 30);
        pnlIntDatosServ.add(txttituloProf);
        txttituloProf.setBounds(270, 80, 410, 30);

        lblApellNombJefe.setText("Apellidos y Nombres Jefe Inmediato:");
        pnlIntDatosServ.add(lblApellNombJefe);
        lblApellNombJefe.setBounds(20, 110, 240, 30);
        pnlIntDatosServ.add(cbJefeInmediato);
        cbJefeInmediato.setBounds(270, 110, 410, 30);

        pnlDatosServidor.add(pnlIntDatosServ);
        pnlIntDatosServ.setBounds(20, 150, 710, 160);

        btnGenerar.setText("Generar");
        pnlDatosServidor.add(btnGenerar);
        btnGenerar.setBounds(310, 360, 140, 40);

        getContentPane().add(pnlDatosServidor);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEvalOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEvalOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEvalOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEvalOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmEvalOld dialog = new FrmEvalOld(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox cbJefeInmediato;
    public static javax.swing.JComboBox cbServidores;
    private javax.swing.JLabel lblApellNomb;
    private javax.swing.JLabel lblApellNombJefe;
    private javax.swing.JLabel lblEscServid;
    private javax.swing.JLabel lblPuestoDesemp;
    private javax.swing.JLabel lblTituloProf;
    private javax.swing.JPanel pnlDatosServidor;
    private javax.swing.JPanel pnlIntDatosServ;
    private javax.swing.JTextField txtApellidosNombres;
    private javax.swing.JTextField txtPuestoDesemp;
    private javax.swing.JTextField txttituloProf;
    // End of variables declaration//GEN-END:variables
}
