/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.evaluacion;

import controlador.acciones.evaluaciones.ControladorTest;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JTextField;
import modelo.pregunta.Pregunta;

/**
 *
 * @author francisco
 */
public class FrmTests extends javax.swing.JDialog {

    private JTextField text;
    private ArrayList<Pregunta> preguntas;
    private ControladorTest ct;
    private GestorControladorTest gct;

    public FrmTests() {
        initComponents();
    }

    public FrmTests(ArrayList<Pregunta> preg) {
        initComponents();
        preguntas = preg;
        ct = new ControladorTest(this);
        gct = new GestorControladorTest();
        ct.ponePreguntas();
        ct.llenaPaneles();
        btnAnterior.addActionListener(gct);
        btnSiguiente.addActionListener(gct);
        btnCalificar.addActionListener(gct);
        btnCerrar.addActionListener(gct);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        pnlMedio = new javax.swing.JPanel();
        pnlUno = new javax.swing.JPanel();
        pnlDos = new javax.swing.JPanel();
        pnlTres = new javax.swing.JPanel();
        pnlCuatro = new javax.swing.JPanel();
        pnlCinco = new javax.swing.JPanel();
        pnlSeis = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnCalificar = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jLabel1.setText("POR FAVOR RESPONDA A LAS SIGUIENTES PREGUNTAS:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 640, 20);

        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlMedio.setLayout(new java.awt.CardLayout());

        pnlUno.setLayout(new java.awt.GridLayout(10, 0));
        pnlMedio.add(pnlUno, "pnlUno");

        pnlDos.setLayout(new java.awt.GridLayout(10, 0));
        pnlMedio.add(pnlDos, "pnlDos");

        pnlTres.setLayout(new java.awt.GridLayout(10, 0));
        pnlMedio.add(pnlTres, "pnlTres");

        pnlCuatro.setLayout(new java.awt.GridLayout(10, 0));
        pnlMedio.add(pnlCuatro, "pnlCuatro");

        pnlCinco.setLayout(new java.awt.GridLayout(10, 0));
        pnlMedio.add(pnlCinco, "pnlCinco");
        pnlMedio.add(pnlSeis, "pnlSeis");

        pnlPrincipal.add(pnlMedio, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlPrincipal);
        pnlPrincipal.setBounds(10, 50, 1000, 440);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/salir_1.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(910, 500, 100, 40);

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/agt_back.png"))); // NOI18N
        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnterior);
        btnAnterior.setBounds(390, 500, 110, 41);

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/agt_forward.png"))); // NOI18N
        btnSiguiente.setText("Siguiente");
        getContentPane().add(btnSiguiente);
        btnSiguiente.setBounds(530, 500, 120, 41);

        btnCalificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/business.png"))); // NOI18N
        btnCalificar.setText("Calificar");
        getContentPane().add(btnCalificar);
        btnCalificar.setBounds(660, 500, 110, 41);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1028)/2, (screenSize.height-579)/2, 1028, 579);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnteriorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCalificar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlCinco;
    private javax.swing.JPanel pnlCuatro;
    private javax.swing.JPanel pnlDos;
    private javax.swing.JPanel pnlMedio;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSeis;
    private javax.swing.JPanel pnlTres;
    private javax.swing.JPanel pnlUno;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the preguntas
     */
    public ArrayList<Pregunta> getPreguntas() {
        return preguntas;
    }

    /**
     * @return the pnlMedio
     */
    public javax.swing.JPanel getPnlMedio() {
        return pnlMedio;
    }

    /**
     * @return the btnCalificar
     */
    public javax.swing.JButton getBtnCalificar() {
        return btnCalificar;
    }

    /**
     * @return the btnAnterior
     */
    public javax.swing.JButton getBtnAnterior() {
        return btnAnterior;
    }

    /**
     * @return the btnSiguiente
     */
    public javax.swing.JButton getBtnSiguiente() {
        return btnSiguiente;
    }

    /**
     * @return the pnlCinco
     */
    public javax.swing.JPanel getPnlCinco() {
        return pnlCinco;
    }

    /**
     * @return the pnlCuatro
     */
    public javax.swing.JPanel getPnlCuatro() {
        return pnlCuatro;
    }

    /**
     * @return the pnlDos
     */
    public javax.swing.JPanel getPnlDos() {
        return pnlDos;
    }

    /**
     * @return the pnlSeis
     */
    public javax.swing.JPanel getPnlSeis() {
        return pnlSeis;
    }

    /**
     * @return the pnlTres
     */
    public javax.swing.JPanel getPnlTres() {
        return pnlTres;
    }

    /**
     * @return the pnlUno
     */
    public javax.swing.JPanel getPnlUno() {
        return pnlUno;
    }

    class GestorControladorTest implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == btnAnterior) {
                ct.anteriorPanel();
            } else if (e.getSource() == btnSiguiente) {
                ct.siguientePanel();
            } else if (e.getSource() == btnCerrar) {
                dispose();
            } else if (e.getSource() == btnCalificar) {
                ct.califica();
            }
        }
    }
    //aciertos * 5 /numPreguntas

    /*
     *5 sobresaliente
     *4 muy buena
     *3 buena
     *2 regular
     *1 insuficiente
     */
}
