/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.evaluacion;

import controlador.acciones.evaluaciones.ControladorCompUniv;
import controlador.acciones.evaluaciones.ControladorEvaluacion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import modelo.operaciones.CompetenciaUniversal;

/**
 *
 * @author jenny
 */
public class PnlCompUniv extends javax.swing.JPanel {

    private CompetenciaUniversal cu;
    private ControladorCompUniv ccu;
    private GestorControladorCompUniv gccu;

    /**
     * Creates new form PnlCompUniv
     */
    public PnlCompUniv(CompetenciaUniversal cu) {
        initComponents();
        this.cu = cu;
        txtCompUniv.setText(cu.getNombreDestrezaUniv());
        txtCompObserv.setText(cu.getAltaUniv());
        ccu = new ControladorCompUniv(this);
        gccu = new GestorControladorCompUniv();
        cbRelev.addActionListener(gccu);
        cbFrecuenciaAplic.addActionListener(gccu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCompObserv = new javax.swing.JTextField();
        cbRelev = new javax.swing.JComboBox();
        txtCompUniv = new javax.swing.JTextField();
        cbFrecuenciaAplic = new javax.swing.JComboBox();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(902, 33));
        setLayout(null);

        txtCompObserv.setEditable(false);
        add(txtCompObserv);
        txtCompObserv.setBounds(460, 0, 290, 30);

        cbRelev.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alta", "Media", "Baja" }));
        add(cbRelev);
        cbRelev.setBounds(290, 0, 170, 30);

        txtCompUniv.setEditable(false);
        add(txtCompUniv);
        txtCompUniv.setBounds(0, 0, 290, 30);

        cbFrecuenciaAplic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Siempre", "Frecuentemente", "Alguna vez", "Rara vez", "Nunca" }));
        add(cbFrecuenciaAplic);
        cbFrecuenciaAplic.setBounds(750, 0, 150, 30);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbFrecuenciaAplic;
    private javax.swing.JComboBox cbRelev;
    private javax.swing.JTextField txtCompObserv;
    private javax.swing.JTextField txtCompUniv;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the cbFrecuenciaAplic
     */
    public javax.swing.JComboBox getCbFrecuenciaAplic() {
        return cbFrecuenciaAplic;
    }

    /**
     * @return the cbRelev
     */
    public javax.swing.JComboBox getCbRelev() {
        return cbRelev;
    }

    /**
     * @return the txtCompObserv
     */
    public javax.swing.JTextField getTxtCompObserv() {
        return txtCompObserv;
    }

    /**
     * @return the txtCompUniv
     */
    public javax.swing.JTextField getTxtCompUniv() {
        return txtCompUniv;
    }

    class GestorControladorCompUniv implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == cbRelev) {
                ccu.frecuenciaAplic(cbRelev.getSelectedIndex(), cu);
            } else if (e.getSource() == cbFrecuenciaAplic) {
                if (ControladorEvaluacion.facCompUniv > 0) {
                    ccu.actualizaResCompUniv();
                } else {
                    JOptionPane.showMessageDialog(null, "Debe llenar el campo de factor de competencia universal con valores mayores a cero");
                }
            }
        }
    }
}
