/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.evaluacion;

import controlador.acciones.Constantes;
import controlador.acciones.evaluaciones.ControladorEvaluacion;
import controlador.basedatos.OperacionesBD;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import modelo.evaluacion.Efectos;
import modelo.evaluacion.PeriodoEvaluacion;
import modelo.usuario.Usuario;
import vista.FrmPrincipal;
import vista.modelo.ImagenJPanel;
import vista.modelo.Mensaje;

/**
 *
 * @author jenny
 */
public class PnlEvaluacion extends javax.swing.JPanel {

    private ControladorEvaluacion ce;
    private GestorControladorEvaluacion gce;
    private ArrayList<Usuario> servidoresDisp;
    private ArrayList<Usuario> servidoresPlanif;
    private Efectos efec;
    private ArrayList<Efectos> efectos;
    private String nombreEf;//nombre efecto

    /**
     * Creates new form PnlEvaluacion
     */
    public PnlEvaluacion() {
        initComponents();
        ce = new ControladorEvaluacion(this);
        gce = new GestorControladorEvaluacion();
        btnAnterior.setEnabled(false);
        btnResultados.setEnabled(false);
//        ce.llenaCbServidores();
        ce.llenaServidorEscogido();
        poneEventos();
        llenaCombo();
        poneTabs();

    }

    private void poneTabs() {
        if (FrmPrincipal.userLogueado.getRol().getTipo().equals(Constantes.SERVIDOR)) {
            //remover todos los tabs menos el primero y el segundo
            for (int i = 0; i <= tabbedEvaluacion.getTabCount(); i++) {
                int ultimo = tabbedEvaluacion.getTabCount() - 1;
                tabbedEvaluacion.removeTabAt(ultimo);
            }
        } else if (FrmPrincipal.userLogueado.getRol().getTipo().equals(Constantes.RRHH)) {
            //remover los primeros 3 tabs
            for (int i = 0; i <= tabbedEvaluacion.getTabCount(); i++) {
                if (i < tabbedEvaluacion.getTabCount()) {
                    tabbedEvaluacion.removeTabAt(0);
                }
            }
            if (FrmPrincipal.estaEvalActiva) {
                tabbedEvaluacion.removeTabAt(0);
            }
        } else if (FrmPrincipal.userLogueado.getRol().getTipo().equals(Constantes.JEFE)) {
            //remover todos los tabs menos el primero y el segundo
            if (FrmPrincipal.userLogueado.isEvaluacionActivada() && FrmPrincipal.estaEvalActiva) {
                for (int i = 0; i <= tabbedEvaluacion.getTabCount(); i++) {
                    int ultimo = tabbedEvaluacion.getTabCount() - 1;
                    tabbedEvaluacion.removeTabAt(ultimo);
                }
            } else {
                for (int i = 0; i < 2; i++) {//remover los primeros dos tabs
                    tabbedEvaluacion.removeTabAt(0);
                }
            }
        }
        listarServidores();
        llenaListaDisponibles();
        llenaListaAsignados();
    }

    private void poneEventos() {
        getBtnAnterior().addActionListener(gce);
        getBtnSiguiente().addActionListener(gce);
////        getBtnResultados().addActionListener(gce);
////        cbServidores.addActionListener(gce);
        btnGenerar.addActionListener(gce);
        btnResultados.addActionListener(gce);
        txtFactorConoc.addKeyListener(gce);
        txtFactorCompTec.addKeyListener(gce);
        txtFactorUniv.addKeyListener(gce);
        txtFactorTrab.addKeyListener(gce);
        tabbedEvaluacion.addChangeListener(gce);
        btnIr.addActionListener(gce);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedEvaluacion = new javax.swing.JTabbedPane();
        pnlUno = new javax.swing.JPanel();
        pnlDatosServidor = new javax.swing.JPanel();
        btnGenerar = new javax.swing.JButton();
        lblTituloProf = new javax.swing.JLabel();
        lblPuestoDesemp = new javax.swing.JLabel();
        lblApellNomb = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtNombreApellidos = new javax.swing.JTextField();
        txtPuesto = new javax.swing.JTextField();
        pnlDos = new javax.swing.JPanel();
        pnlEvalServ = new javax.swing.JPanel();
        pnlArriba = new javax.swing.JPanel();
        lblPuesto = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblNombreEvaluado = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        pnlMedio = new javax.swing.JPanel();
        pnlIndicGestionPuesto = new javax.swing.JPanel();
        pnlCabeceras = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlDatosInf = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblTotActivEscen = new javax.swing.JLabel();
        txtTotActEsc = new javax.swing.JTextField();
        pnlInfoIndic = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        scrollDatosIndic = new javax.swing.JScrollPane();
        pnlDatosIndic = new javax.swing.JPanel();
        lblActividades = new javax.swing.JLabel();
        txtNroActividades = new javax.swing.JTextField();
        lblFactor = new javax.swing.JLabel();
        txtFactorIndic = new javax.swing.JTextField();
        lblFactor1 = new javax.swing.JLabel();
        dpDesde = new org.jdesktop.swingx.JXDatePicker();
        dpHasta = new org.jdesktop.swingx.JXDatePicker();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        btnIr = new javax.swing.JButton();
        pnlConocimientos = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTotalConocimientos = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        scrollDatosConoc = new javax.swing.JScrollPane();
        pnlDatosConoc = new javax.swing.JPanel();
        lblFactorConoc = new javax.swing.JLabel();
        txtFactorConoc = new javax.swing.JTextField();
        txtNroConocimientos = new javax.swing.JTextField();
        lblConocimientos = new javax.swing.JLabel();
        lblFactor2 = new javax.swing.JLabel();
        pnlCompetTecnicas = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTotalCompTec = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        scrollDatosComp = new javax.swing.JScrollPane();
        pnlDatosComp = new javax.swing.JPanel();
        lblCompetTec = new javax.swing.JLabel();
        txtNroCompetTecnic = new javax.swing.JTextField();
        lblFactCompTec = new javax.swing.JLabel();
        txtFactorCompTec = new javax.swing.JTextField();
        lblFactor3 = new javax.swing.JLabel();
        pnlCompetUniver = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtTotalCompUniv = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        scrollDatosCompUnivers = new javax.swing.JScrollPane();
        pnlDatosCompUnivers = new javax.swing.JPanel();
        lblCompetUniv = new javax.swing.JLabel();
        txtNroCompetUniv = new javax.swing.JTextField();
        lblFactorUniv = new javax.swing.JLabel();
        txtFactorUniv = new javax.swing.JTextField();
        lblFactor4 = new javax.swing.JLabel();
        pnlTrabEquipo = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtTotalTrabEquip = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        scrollDatosTrabEquipo = new javax.swing.JScrollPane();
        pnlDatosTrabEquipo = new javax.swing.JPanel();
        lblFactorTrab = new javax.swing.JLabel();
        txtFactorTrab = new javax.swing.JTextField();
        lblFactor5 = new javax.swing.JLabel();
        pnlQuejas = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        scrollDatosQuejas = new javax.swing.JScrollPane();
        pnlDatosQuejas = new javax.swing.JPanel();
        txtTotalQuejas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pnlAbajo = new javax.swing.JPanel();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnResultados = new javax.swing.JButton();
        pnlCinco = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIneficienteCalificacion = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtBuenaCalificacion = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDeficienteCalificacion = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        cbNombres = new javax.swing.JComboBox();
        btnNuevoNombre = new javax.swing.JButton();
        pnlTres = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btnAplicar = new javax.swing.JButton();
        lblHasta = new javax.swing.JLabel();
        dateHasta = new org.jdesktop.swingx.JXDatePicker();
        dateDesde = new org.jdesktop.swingx.JXDatePicker();
        lblDesde = new javax.swing.JLabel();
        txtMinDesde = new javax.swing.JTextField();
        txtHoraDesde = new javax.swing.JTextField();
        txtMinHasta = new javax.swing.JTextField();
        txtHoraHasta = new javax.swing.JTextField();
        lblSepHasta = new javax.swing.JLabel();
        lblSepDesde = new javax.swing.JLabel();
        pnlCuatro = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstDisponibleParaEval = new javax.swing.JList();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstParaEvaluar = new javax.swing.JList();
        btnAceptar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnlUno  = new  ImagenJPanel ("zzz.jpg");

        pnlDatosServidor.setOpaque(false);
        pnlDatosServidor.setPreferredSize(new java.awt.Dimension(750, 500));
        pnlDatosServidor.setLayout(null);

        btnGenerar.setText("Generar");
        pnlDatosServidor.add(btnGenerar);
        btnGenerar.setBounds(310, 360, 140, 40);

        lblTituloProf.setText("   Título o Profesion:");
        pnlDatosServidor.add(lblTituloProf);
        lblTituloProf.setBounds(190, 220, 160, 30);

        lblPuestoDesemp.setText("  Puesto que desempeña:");
        pnlDatosServidor.add(lblPuestoDesemp);
        lblPuestoDesemp.setBounds(160, 190, 200, 30);

        lblApellNomb.setText("  Apellidos y Nombres:");
        pnlDatosServidor.add(lblApellNomb);
        lblApellNomb.setBounds(180, 160, 160, 30);

        txtTitulo.setEditable(false);
        pnlDatosServidor.add(txtTitulo);
        txtTitulo.setBounds(340, 220, 250, 30);

        txtNombreApellidos.setEditable(false);
        pnlDatosServidor.add(txtNombreApellidos);
        txtNombreApellidos.setBounds(340, 160, 250, 30);

        txtPuesto.setEditable(false);
        pnlDatosServidor.add(txtPuesto);
        txtPuesto.setBounds(340, 190, 250, 30);

        pnlUno.add(pnlDatosServidor);

        tabbedEvaluacion.addTab("DATOS DEL SERVIDOR", pnlUno);

        pnlDos.setOpaque(false);
        pnlDos  = new  ImagenJPanel ("zzz.jpg");

        pnlEvalServ.setOpaque(false);
        pnlEvalServ.setPreferredSize(new java.awt.Dimension(930, 550));
        pnlEvalServ.setLayout(new java.awt.BorderLayout());

        pnlArriba.setOpaque(false);

        lblPuesto.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N

        jLabel29.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel29.setText("Nombre Evaluado:");

        jLabel31.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel31.setText("Puesto:");

        javax.swing.GroupLayout pnlArribaLayout = new javax.swing.GroupLayout(pnlArriba);
        pnlArriba.setLayout(pnlArribaLayout);
        pnlArribaLayout.setHorizontalGroup(
            pnlArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArribaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lblNombreEvaluado, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlArribaLayout.setVerticalGroup(
            pnlArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArribaLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(lblNombreEvaluado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnlEvalServ.add(pnlArriba, java.awt.BorderLayout.PAGE_START);

        pnlMedio.setOpaque(false);
        pnlMedio.setLayout(new java.awt.CardLayout());

        pnlIndicGestionPuesto.setOpaque(false);
        pnlIndicGestionPuesto.setLayout(null);

        pnlCabeceras.setOpaque(false);
        pnlCabeceras.setLayout(null);

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html>         Nivel de<br>Cumplimiento</html>");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCabeceras.add(jLabel7);
        jLabel7.setBounds(800, 0, 110, 50);

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("% Cumplimiento");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCabeceras.add(jLabel6);
        jLabel6.setBounds(690, 0, 110, 50);

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cumplidos");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCabeceras.add(jLabel5);
        jLabel5.setBounds(580, 0, 110, 50);

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html>Meta del<br>Periodo<br>Evaluado</html>");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCabeceras.add(jLabel4);
        jLabel4.setBounds(460, 0, 120, 50);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Indicador");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCabeceras.add(jLabel2);
        jLabel2.setBounds(270, 0, 190, 50);

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Descripcion de Actividades");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCabeceras.add(jLabel3);
        jLabel3.setBounds(0, 0, 270, 50);

        pnlIndicGestionPuesto.add(pnlCabeceras);
        pnlCabeceras.setBounds(10, 70, 910, 50);

        pnlDatosInf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDatosInf.setOpaque(false);
        pnlDatosInf.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>¿A más del cumplimiento de la totalidad de metas y objetivos se adelanto <br> y cumplio con objetivos y metas previstas para el siguiente periodo de evaluacion</html> ");
        pnlDatosInf.add(jLabel1);
        jLabel1.setBounds(24, 2, 443, 64);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("APLICA EL 4%");
        pnlDatosInf.add(jLabel8);
        jLabel8.setBounds(473, 2, 223, 26);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("% DE AUMENTO");
        pnlDatosInf.add(jLabel9);
        jLabel9.setBounds(708, 2, 200, 26);
        pnlDatosInf.add(jTextField1);
        jTextField1.setBounds(708, 34, 200, 32);

        pnlIndicGestionPuesto.add(pnlDatosInf);
        pnlDatosInf.setBounds(10, 330, 910, 70);

        lblTotActivEscen.setText("Total Actividades Esenciales:");
        pnlIndicGestionPuesto.add(lblTotActivEscen);
        lblTotActivEscen.setBounds(540, 410, 190, 17);
        pnlIndicGestionPuesto.add(txtTotActEsc);
        txtTotActEsc.setBounds(720, 400, 200, 30);

        pnlInfoIndic.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlInfoIndic.setOpaque(false);
        pnlInfoIndic.setLayout(null);

        jLabel30.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel30.setText("INDICADORES DE GESTIÓN DEL PUESTO");
        pnlInfoIndic.add(jLabel30);
        jLabel30.setBounds(10, 0, 310, 30);

        pnlIndicGestionPuesto.add(pnlInfoIndic);
        pnlInfoIndic.setBounds(10, 40, 910, 30);

        scrollDatosIndic.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollDatosIndic.setOpaque(false);

        pnlDatosIndic.setOpaque(false);
        pnlDatosIndic.setVerifyInputWhenFocusTarget(false);
        pnlDatosIndic.setLayout(new javax.swing.BoxLayout(pnlDatosIndic, javax.swing.BoxLayout.Y_AXIS));
        scrollDatosIndic.setViewportView(pnlDatosIndic);

        pnlIndicGestionPuesto.add(scrollDatosIndic);
        scrollDatosIndic.setBounds(10, 120, 910, 210);

        lblActividades.setText("# Actividades: ");
        pnlIndicGestionPuesto.add(lblActividades);
        lblActividades.setBounds(10, 10, 100, 20);

        txtNroActividades.setEditable(false);
        pnlIndicGestionPuesto.add(txtNroActividades);
        txtNroActividades.setBounds(130, 10, 60, 27);

        lblFactor.setText("%");
        pnlIndicGestionPuesto.add(lblFactor);
        lblFactor.setBounds(400, 10, 20, 20);
        pnlIndicGestionPuesto.add(txtFactorIndic);
        txtFactorIndic.setBounds(330, 10, 60, 27);

        lblFactor1.setText("# Factor: ");
        pnlIndicGestionPuesto.add(lblFactor1);
        lblFactor1.setBounds(260, 10, 70, 20);
        pnlIndicGestionPuesto.add(dpDesde);
        dpDesde.setBounds(480, 10, 140, 27);
        pnlIndicGestionPuesto.add(dpHasta);
        dpHasta.setBounds(700, 10, 140, 27);

        jLabel47.setText("Hasta:");
        pnlIndicGestionPuesto.add(jLabel47);
        jLabel47.setBounds(640, 10, 60, 30);

        jLabel48.setText("Desde:");
        pnlIndicGestionPuesto.add(jLabel48);
        jLabel48.setBounds(420, 10, 60, 30);

        btnIr.setText("Ir");
        pnlIndicGestionPuesto.add(btnIr);
        btnIr.setBounds(850, 10, 19, 29);

        pnlMedio.add(pnlIndicGestionPuesto, "pnlIndicGestionPuesto");

        pnlConocimientos.setOpaque(false);
        pnlConocimientos.setLayout(null);

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Nivel de Conocimiento");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlConocimientos.add(jLabel11);
        jLabel11.setBounds(550, 70, 370, 50);

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CONOCIMIENTOS");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlConocimientos.add(jLabel12);
        jLabel12.setBounds(10, 70, 540, 50);

        jLabel13.setText("Total Conocimientos:");
        pnlConocimientos.add(jLabel13);
        jLabel13.setBounds(560, 350, 180, 17);
        pnlConocimientos.add(txtTotalConocimientos);
        txtTotalConocimientos.setBounds(720, 340, 200, 30);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        jLabel32.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel32.setText("CONOCIMIENTOS");
        jPanel4.add(jLabel32);
        jLabel32.setBounds(10, 0, 310, 30);

        pnlConocimientos.add(jPanel4);
        jPanel4.setBounds(10, 40, 910, 30);

        scrollDatosConoc.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollDatosConoc.setOpaque(false);

        pnlDatosConoc.setOpaque(false);
        pnlDatosConoc.setLayout(new javax.swing.BoxLayout(pnlDatosConoc, javax.swing.BoxLayout.Y_AXIS));
        scrollDatosConoc.setViewportView(pnlDatosConoc);

        pnlConocimientos.add(scrollDatosConoc);
        scrollDatosConoc.setBounds(10, 120, 910, 210);

        lblFactorConoc.setText("# Factor: ");
        pnlConocimientos.add(lblFactorConoc);
        lblFactorConoc.setBounds(260, 10, 70, 20);
        pnlConocimientos.add(txtFactorConoc);
        txtFactorConoc.setBounds(330, 10, 60, 27);

        txtNroConocimientos.setEditable(false);
        pnlConocimientos.add(txtNroConocimientos);
        txtNroConocimientos.setBounds(130, 10, 60, 27);

        lblConocimientos.setText("# Conocimientos: ");
        pnlConocimientos.add(lblConocimientos);
        lblConocimientos.setBounds(10, 10, 120, 20);

        lblFactor2.setText("%");
        pnlConocimientos.add(lblFactor2);
        lblFactor2.setBounds(400, 10, 20, 20);

        pnlMedio.add(pnlConocimientos, "pnlConocimientos");

        pnlCompetTecnicas.setOpaque(false);
        pnlCompetTecnicas.setLayout(null);

        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("DESTREZAS");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCompetTecnicas.add(jLabel14);
        jLabel14.setBounds(10, 70, 290, 50);

        jLabel15.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Relevancia");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCompetTecnicas.add(jLabel15);
        jLabel15.setBounds(300, 70, 170, 50);

        jLabel17.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Comportamiento Observable");
        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCompetTecnicas.add(jLabel17);
        jLabel17.setBounds(470, 70, 290, 50);

        jLabel19.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("<html>Nivel de<br>Desarrollo</html>");
        jLabel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCompetTecnicas.add(jLabel19);
        jLabel19.setBounds(760, 70, 160, 50);

        jLabel16.setText("Total Competencias Tecnicas del Puesto:");
        pnlCompetTecnicas.add(jLabel16);
        jLabel16.setBounds(450, 340, 270, 17);
        pnlCompetTecnicas.add(txtTotalCompTec);
        txtTotalCompTec.setBounds(720, 330, 200, 30);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setOpaque(false);
        jPanel5.setLayout(null);

        jLabel33.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel33.setText("COMPETENCIAS TÉCNICAS DEL PUESTO");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(10, 0, 500, 30);

        pnlCompetTecnicas.add(jPanel5);
        jPanel5.setBounds(10, 40, 910, 30);

        scrollDatosComp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollDatosComp.setWheelScrollingEnabled(false);

        pnlDatosComp.setOpaque(false);
        pnlDatosComp.setLayout(new javax.swing.BoxLayout(pnlDatosComp, javax.swing.BoxLayout.Y_AXIS));
        scrollDatosComp.setViewportView(pnlDatosComp);

        pnlCompetTecnicas.add(scrollDatosComp);
        scrollDatosComp.setBounds(10, 120, 910, 210);

        lblCompetTec.setText("# Competencias: ");
        pnlCompetTecnicas.add(lblCompetTec);
        lblCompetTec.setBounds(10, 10, 120, 20);

        txtNroCompetTecnic.setEditable(false);
        pnlCompetTecnicas.add(txtNroCompetTecnic);
        txtNroCompetTecnic.setBounds(130, 10, 60, 27);

        lblFactCompTec.setText("# Factor: ");
        pnlCompetTecnicas.add(lblFactCompTec);
        lblFactCompTec.setBounds(260, 10, 70, 20);
        pnlCompetTecnicas.add(txtFactorCompTec);
        txtFactorCompTec.setBounds(330, 10, 60, 27);

        lblFactor3.setText("%");
        pnlCompetTecnicas.add(lblFactor3);
        lblFactor3.setBounds(400, 10, 20, 20);

        pnlMedio.add(pnlCompetTecnicas, "pnlCompetTecnicas");

        pnlCompetUniver.setOpaque(false);
        pnlCompetUniver.setLayout(null);

        jLabel18.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("DESTREZAS");
        jLabel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCompetUniver.add(jLabel18);
        jLabel18.setBounds(10, 70, 290, 50);

        jLabel20.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Relevancia");
        jLabel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCompetUniver.add(jLabel20);
        jLabel20.setBounds(300, 70, 170, 50);

        jLabel21.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Comportamiento Observable");
        jLabel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCompetUniver.add(jLabel21);
        jLabel21.setBounds(470, 70, 290, 50);

        jLabel22.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("<html>Frecuencia de<br>     Aplicacion</html>");
        jLabel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCompetUniver.add(jLabel22);
        jLabel22.setBounds(760, 70, 160, 50);

        jLabel23.setText("Total Competencias Universales:");
        pnlCompetUniver.add(jLabel23);
        jLabel23.setBounds(450, 340, 270, 17);
        pnlCompetUniver.add(txtTotalCompUniv);
        txtTotalCompUniv.setBounds(720, 330, 200, 30);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setOpaque(false);
        jPanel6.setLayout(null);

        jLabel34.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel34.setText("COMPETENCIAS UNIVERSALES");
        jPanel6.add(jLabel34);
        jLabel34.setBounds(10, 0, 500, 30);

        pnlCompetUniver.add(jPanel6);
        jPanel6.setBounds(10, 40, 910, 30);

        scrollDatosCompUnivers.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollDatosCompUnivers.setOpaque(false);

        pnlDatosCompUnivers.setOpaque(false);
        pnlDatosCompUnivers.setLayout(new javax.swing.BoxLayout(pnlDatosCompUnivers, javax.swing.BoxLayout.Y_AXIS));
        scrollDatosCompUnivers.setViewportView(pnlDatosCompUnivers);

        pnlCompetUniver.add(scrollDatosCompUnivers);
        scrollDatosCompUnivers.setBounds(10, 120, 910, 210);

        lblCompetUniv.setText("# Competencias: ");
        pnlCompetUniver.add(lblCompetUniv);
        lblCompetUniv.setBounds(10, 10, 120, 20);

        txtNroCompetUniv.setEditable(false);
        pnlCompetUniver.add(txtNroCompetUniv);
        txtNroCompetUniv.setBounds(130, 10, 60, 27);

        lblFactorUniv.setText("# Factor: ");
        pnlCompetUniver.add(lblFactorUniv);
        lblFactorUniv.setBounds(260, 10, 70, 20);
        pnlCompetUniver.add(txtFactorUniv);
        txtFactorUniv.setBounds(330, 10, 60, 27);

        lblFactor4.setText("%");
        pnlCompetUniver.add(lblFactor4);
        lblFactor4.setBounds(400, 10, 20, 20);

        pnlMedio.add(pnlCompetUniver, "pnlCompetUniver");

        pnlTrabEquipo.setOpaque(false);
        pnlTrabEquipo.setLayout(null);

        jLabel24.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("DESCRIPCION");
        jLabel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTrabEquipo.add(jLabel24);
        jLabel24.setBounds(10, 70, 180, 50);

        jLabel25.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("RELEVANCIA");
        jLabel25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTrabEquipo.add(jLabel25);
        jLabel25.setBounds(190, 70, 120, 50);

        jLabel26.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("COMPORTAMIENTO OBSERVABLE");
        jLabel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTrabEquipo.add(jLabel26);
        jLabel26.setBounds(310, 70, 440, 50);

        jLabel27.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("<html>Frecuencia de<br>     Aplicacion</html>");
        jLabel27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTrabEquipo.add(jLabel27);
        jLabel27.setBounds(750, 70, 170, 50);

        jLabel28.setText("Trabajo en equipo iniciativa y liderazgo:");
        pnlTrabEquipo.add(jLabel28);
        jLabel28.setBounds(450, 340, 280, 17);
        pnlTrabEquipo.add(txtTotalTrabEquip);
        txtTotalTrabEquip.setBounds(720, 330, 200, 30);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setOpaque(false);
        jPanel7.setLayout(null);

        jLabel35.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel35.setText("TRABAJO EN EQUIPO, INICIATIVA Y LIDERAZGO");
        jPanel7.add(jLabel35);
        jLabel35.setBounds(10, 0, 500, 30);

        pnlTrabEquipo.add(jPanel7);
        jPanel7.setBounds(10, 40, 910, 30);

        scrollDatosTrabEquipo.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollDatosTrabEquipo.setOpaque(false);

        pnlDatosTrabEquipo.setOpaque(false);
        pnlDatosTrabEquipo.setLayout(new javax.swing.BoxLayout(pnlDatosTrabEquipo, javax.swing.BoxLayout.Y_AXIS));
        scrollDatosTrabEquipo.setViewportView(pnlDatosTrabEquipo);

        pnlTrabEquipo.add(scrollDatosTrabEquipo);
        scrollDatosTrabEquipo.setBounds(10, 120, 910, 210);

        lblFactorTrab.setText("# Factor: ");
        pnlTrabEquipo.add(lblFactorTrab);
        lblFactorTrab.setBounds(10, 10, 70, 20);
        pnlTrabEquipo.add(txtFactorTrab);
        txtFactorTrab.setBounds(80, 10, 60, 27);

        lblFactor5.setText("  %");
        pnlTrabEquipo.add(lblFactor5);
        lblFactor5.setBounds(140, 10, 20, 30);

        pnlMedio.add(pnlTrabEquipo, "pnlTrabEquipo");

        pnlQuejas.setOpaque(false);
        pnlQuejas.setLayout(null);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel36.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("QUEJAS DEL CIUDADANO");
        jPanel8.add(jLabel36, java.awt.BorderLayout.CENTER);

        pnlQuejas.add(jPanel8);
        jPanel8.setBounds(10, 40, 910, 30);

        jLabel37.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("DESCRIPCIÓN");
        jLabel37.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlQuejas.add(jLabel37);
        jLabel37.setBounds(190, 70, 350, 50);

        jLabel40.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("<html>NRO. DE<br>FORMULARIO</html>");
        jLabel40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlQuejas.add(jLabel40);
        jLabel40.setBounds(540, 70, 90, 50);

        jLabel41.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("<html>NOMBRE DE LA PERSONA<br>QUE REALIZA LA QUEJA</html>");
        jLabel41.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlQuejas.add(jLabel41);
        jLabel41.setBounds(10, 70, 180, 50);

        jLabel42.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("<html>APLICA DESCUENTO A<br>LA EVALUACIÓN<br>DE DESEMPEÑO</html>");
        jLabel42.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlQuejas.add(jLabel42);
        jLabel42.setBounds(630, 70, 170, 50);

        jLabel43.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("<html>% DE<br>REDUCCIÓN</html>");
        jLabel43.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlQuejas.add(jLabel43);
        jLabel43.setBounds(800, 70, 120, 50);

        scrollDatosQuejas.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollDatosQuejas.setOpaque(false);

        pnlDatosQuejas.setOpaque(false);
        pnlDatosQuejas.setLayout(new javax.swing.BoxLayout(pnlDatosQuejas, javax.swing.BoxLayout.Y_AXIS));
        scrollDatosQuejas.setViewportView(pnlDatosQuejas);

        pnlQuejas.add(scrollDatosQuejas);
        scrollDatosQuejas.setBounds(10, 120, 910, 210);

        txtTotalQuejas.setEditable(false);
        pnlQuejas.add(txtTotalQuejas);
        txtTotalQuejas.setBounds(830, 337, 90, 30);

        jLabel10.setText("Total:");
        pnlQuejas.add(jLabel10);
        jLabel10.setBounds(780, 340, 50, 20);

        pnlMedio.add(pnlQuejas, "card7");

        pnlEvalServ.add(pnlMedio, java.awt.BorderLayout.CENTER);

        pnlAbajo.setOpaque(false);

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/agt_forward.png"))); // NOI18N
        btnSiguiente.setText("Siguiente");

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/agt_back.png"))); // NOI18N
        btnAnterior.setText("Anterior");

        btnResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/business.png"))); // NOI18N
        btnResultados.setText("Resultados");
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAbajoLayout = new javax.swing.GroupLayout(pnlAbajo);
        pnlAbajo.setLayout(pnlAbajoLayout);
        pnlAbajoLayout.setHorizontalGroup(
            pnlAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAbajoLayout.createSequentialGroup()
                .addContainerGap(313, Short.MAX_VALUE)
                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );
        pnlAbajoLayout.setVerticalGroup(
            pnlAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEvalServ.add(pnlAbajo, java.awt.BorderLayout.PAGE_END);

        pnlDos.add(pnlEvalServ);

        tabbedEvaluacion.addTab("EVALUACION AL SERVIDOR", pnlDos);

        jPanel11.setPreferredSize(new java.awt.Dimension(400, 480));
        jPanel11.setLayout(null);

        jLabel38.setText("INEFICIENTE CALIFICACIÓN:");
        jPanel11.add(jLabel38);
        jLabel38.setBounds(10, 310, 170, 17);

        jLabel39.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        jLabel39.setText("EFECTOS EVALUACIÓN");
        jPanel11.add(jLabel39);
        jLabel39.setBounds(130, 10, 140, 17);

        jLabel44.setText("BUENA CALIFICACIÓN:");
        jPanel11.add(jLabel44);
        jLabel44.setBounds(10, 90, 140, 17);

        jLabel45.setText("DEFICIENTE CALIFICACIÓN:");
        jPanel11.add(jLabel45);
        jLabel45.setBounds(10, 200, 170, 17);

        txtIneficienteCalificacion.setColumns(20);
        txtIneficienteCalificacion.setRows(5);
        jScrollPane1.setViewportView(txtIneficienteCalificacion);

        jPanel11.add(jScrollPane1);
        jScrollPane1.setBounds(10, 330, 380, 87);

        txtBuenaCalificacion.setColumns(20);
        txtBuenaCalificacion.setRows(5);
        jScrollPane4.setViewportView(txtBuenaCalificacion);

        jPanel11.add(jScrollPane4);
        jScrollPane4.setBounds(10, 110, 380, 87);

        txtDeficienteCalificacion.setColumns(20);
        txtDeficienteCalificacion.setRows(5);
        jScrollPane5.setViewportView(txtDeficienteCalificacion);

        jPanel11.add(jScrollPane5);
        jScrollPane5.setBounds(10, 220, 380, 87);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel11.add(btnGuardar);
        btnGuardar.setBounds(150, 430, 100, 40);

        jLabel46.setText("NOMBRE:");
        jPanel11.add(jLabel46);
        jLabel46.setBounds(9, 37, 70, 30);

        cbNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNombresActionPerformed(evt);
            }
        });
        jPanel11.add(cbNombres);
        cbNombres.setBounds(80, 40, 220, 30);

        btnNuevoNombre.setText("Nuevo");
        btnNuevoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoNombreActionPerformed(evt);
            }
        });
        jPanel11.add(btnNuevoNombre);
        btnNuevoNombre.setBounds(310, 40, 80, 30);

        pnlCinco.add(jPanel11);

        tabbedEvaluacion.addTab("EFECTOS EVALUACIÓN", pnlCinco);

        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel9.setLayout(null);

        btnAplicar.setText("Aplicar");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });
        jPanel9.add(btnAplicar);
        btnAplicar.setBounds(150, 230, 110, 40);

        lblHasta.setText("Hasta:");
        jPanel9.add(lblHasta);
        lblHasta.setBounds(10, 140, 70, 30);
        jPanel9.add(dateHasta);
        dateHasta.setBounds(80, 140, 180, 30);
        jPanel9.add(dateDesde);
        dateDesde.setBounds(80, 100, 180, 30);

        lblDesde.setText("Desde:");
        jPanel9.add(lblDesde);
        lblDesde.setBounds(10, 100, 60, 30);
        jPanel9.add(txtMinDesde);
        txtMinDesde.setBounds(330, 100, 50, 27);
        jPanel9.add(txtHoraDesde);
        txtHoraDesde.setBounds(270, 100, 50, 27);
        jPanel9.add(txtMinHasta);
        txtMinHasta.setBounds(330, 140, 50, 27);
        jPanel9.add(txtHoraHasta);
        txtHoraHasta.setBounds(270, 140, 50, 27);

        lblSepHasta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSepHasta.setText(":");
        jPanel9.add(lblSepHasta);
        lblSepHasta.setBounds(320, 140, 10, 30);

        lblSepDesde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSepDesde.setText(":");
        jPanel9.add(lblSepDesde);
        lblSepDesde.setBounds(320, 100, 10, 30);

        pnlTres.add(jPanel9);

        tabbedEvaluacion.addTab("FECHA EVALUACIÓN", pnlTres);

        jPanel10.setPreferredSize(new java.awt.Dimension(550, 350));
        jPanel10.setLayout(null);

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("ACTIVACIÓN DE EVALUACIÓN");
        jPanel10.add(lblTitulo);
        lblTitulo.setBounds(180, 20, 200, 30);

        jScrollPane3.setViewportView(lstDisponibleParaEval);

        jPanel10.add(jScrollPane3);
        jScrollPane3.setBounds(40, 60, 200, 200);

        btnAgregar.setText(">");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel10.add(btnAgregar);
        btnAgregar.setBounds(250, 110, 50, 29);

        btnQuitar.setText("<");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });
        jPanel10.add(btnQuitar);
        btnQuitar.setBounds(250, 160, 50, 29);

        jScrollPane2.setViewportView(lstParaEvaluar);

        jPanel10.add(jScrollPane2);
        jScrollPane2.setBounds(310, 60, 200, 200);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel10.add(btnAceptar);
        btnAceptar.setBounds(220, 290, 100, 40);

        pnlCuatro.add(jPanel10);

        tabbedEvaluacion.addTab("ACTIVAR EVALUACIÓN", pnlCuatro);

        add(tabbedEvaluacion, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        Calendar actual = Calendar.getInstance();
        Calendar inicio = Calendar.getInstance();
        Calendar fin = Calendar.getInstance();

        inicio.setTime(dateDesde.getDate());
        inicio.set(Calendar.HOUR_OF_DAY, Integer.parseInt(txtHoraDesde.getText()));
        inicio.set(Calendar.MINUTE, Integer.parseInt(txtMinDesde.getText()));
//        System.out.println(inicio.getTime().toString());

        fin.setTime(dateHasta.getDate());
        fin.set(Calendar.HOUR_OF_DAY, Integer.parseInt(txtHoraHasta.getText()));
        fin.set(Calendar.MINUTE, Integer.parseInt(txtMinHasta.getText()));
//        System.out.println(fin.getTime().toString());

        if (fin.after(inicio)) {
            if ((inicio.after(actual) || inicio.equals(actual))
                    && (fin.after(actual))) {
                PeriodoEvaluacion pe = new PeriodoEvaluacion(inicio, fin);
                if (OperacionesBD.guardar(pe)) {
                    JOptionPane.showMessageDialog(null, "Periodo asignado correctamente");
                } else {
                    JOptionPane.showMessageDialog(null, "Hubo un error al asignar el periodo");
                }
            } else {
                JOptionPane.showMessageDialog(null, "No puede asignar a una fecha anterior");
            }
        } else {
            JOptionPane.showMessageDialog(null, "La fecha de fin debe ser posterior a la de inicio");
        }
    }//GEN-LAST:event_btnAplicarActionPerformed

    private void listarServidores() {
        servidoresDisp = new ArrayList<>();
        servidoresPlanif = new ArrayList<>();
        ArrayList<Usuario> serv = (ArrayList<Usuario>) OperacionesBD.listar("Usuario");
        String actual = FrmPrincipal.userLogueado.getRol().getTipo();//tipo Servidor, jefe o rrhh
        for (Usuario s : serv) {
            if ((!s.getRol().getTipo().equals(actual)) && !s.isEvaluacionActivada()) {// si es de recursos humanos no se listaran los de rrhh por ejemplo
                if (actual.equals(Constantes.JEFE)
                        && !s.getRol().getTipo().equals(Constantes.RRHH)) {
                    servidoresDisp.add(s);
                } else if (actual.equals(Constantes.RRHH)
                        && !s.getRol().getTipo().equals(Constantes.SERVIDOR)) {
                    servidoresDisp.add(s);
                }
            } else if ((!s.getRol().getTipo().equals(actual)) && s.isEvaluacionActivada()) {
                if ((actual.equals(Constantes.JEFE) && !s.getRol().getTipo().equals(Constantes.RRHH)) || (actual.equals(Constantes.RRHH)
                        && !s.getRol().getTipo().equals(Constantes.SERVIDOR))) {
                    servidoresPlanif.add(s);
                }
            }
        }

    }

    private void llenaListaDisponibles() {
        DefaultListModel dlm = new DefaultListModel();
        lstDisponibleParaEval.removeAll();
        if (servidoresDisp != null) {
            dlm.removeAllElements();
            for (Usuario u : servidoresDisp) {
                dlm.addElement(u.getNombre() + " " + u.getApellidos());
            }
        }
        lstDisponibleParaEval.setModel(dlm);
    }

    private void llenaListaAsignados() {
        DefaultListModel dlm = new DefaultListModel();
        lstParaEvaluar.removeAll();
        if (servidoresPlanif != null) {
            dlm.removeAllElements();
            for (Usuario u : servidoresPlanif) {
                dlm.addElement(u.getNombre() + " " + u.getApellidos());
            }
        }
        lstParaEvaluar.setModel(dlm);
    }

    private void addToList(Usuario u) {
        servidoresDisp.remove(u);
        servidoresPlanif.add(u);
        llenaListaAsignados();
        llenaListaDisponibles();
    }

    private void removeToList(Usuario u) {
        servidoresPlanif.remove(u);
        servidoresDisp.add(u);
        llenaListaAsignados();
        llenaListaDisponibles();
    }

    private void llenaCombo() {
        efectos = (ArrayList<Efectos>) OperacionesBD.listar("Efectos");
        cbNombres.removeAllItems();
        cbNombres.addItem("Sin Efecto");
        if (!efectos.isEmpty()) {
            for (Efectos e : efectos) {
                cbNombres.addItem(e.getNombre());
            }
        }
    }

    private boolean hayVacios() {
        if (txtBuenaCalificacion.getText().isEmpty()
                || txtDeficienteCalificacion.getText().isEmpty()
                || txtIneficienteCalificacion.getText().isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean nombreEscogido() {
        if (cbNombres.getSelectedIndex() == 0) {
            return false;
        }
        return true;
    }
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (lstDisponibleParaEval.getSelectedIndex() != -1) {
            Usuario u = servidoresDisp.get(lstDisponibleParaEval.getSelectedIndex());
            addToList(u);
        } else {
            if (servidoresDisp.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Lista de Servidores Disponibles vacia");
            } else {
                Mensaje.filaNoSeleccionada();
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        if (lstParaEvaluar.getSelectedIndex() != -1) {
            Usuario u = servidoresPlanif.get(lstParaEvaluar.getSelectedIndex());
            removeToList(u);
        } else {
            if (servidoresPlanif.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Lista de Servidores Planificados vacia");
            } else {
                Mensaje.filaNoSeleccionada();
            }
        }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (nombreEscogido()) {
            if (!hayVacios()) {
                int opc = JOptionPane.showConfirmDialog(null, "¿Desea guardar el Efecto?", "Guardar", JOptionPane.YES_NO_OPTION);
                if (opc == JOptionPane.YES_OPTION) {
                    if (!OperacionesBD.existe("Efecto", "nombre", nombreEf)) {
                        efec = new Efectos();
                        efec.setNombre(nombreEf);
                        efec.setBueno(txtBuenaCalificacion.getText());
                        efec.setDeficiente(txtDeficienteCalificacion.getText());
                        efec.setIneficiente(txtIneficienteCalificacion.getText());
                        if (OperacionesBD.guardar(efec)) {
                            Mensaje.datosGuardados();
                            limpiaCampos();
                        }
                    } else {
                        efec = efectos.get(cbNombres.getSelectedIndex());
                        efec.setNombre(nombreEf);
                        efec.setBueno(txtBuenaCalificacion.getText());
                        efec.setDeficiente(txtDeficienteCalificacion.getText());
                        efec.setIneficiente(txtIneficienteCalificacion.getText());
                        if (OperacionesBD.modificar(efec)) {
                            Mensaje.datosGuardados();
                        }
                    }
                }
            } else {
                Mensaje.camposVacios();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe escoger el nombre del Efecto");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void limpiaCampos() {
        txtBuenaCalificacion.setText("");
        txtDeficienteCalificacion.setText("");
        txtIneficienteCalificacion.setText("");
    }

    private void cbNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNombresActionPerformed
        if (cbNombres.getSelectedIndex() != -1) {
            nombreEf = cbNombres.getSelectedItem().toString();
        }
    }//GEN-LAST:event_cbNombresActionPerformed

    private void btnNuevoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoNombreActionPerformed
        nombreEf = JOptionPane.showInputDialog("Ingrese el nombre del Efecto");
        cbNombres.addItem(nombreEf);
    }//GEN-LAST:event_btnNuevoNombreActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        boolean oper = false;
        if (!servidoresPlanif.isEmpty()) {
            for (Usuario u : servidoresPlanif) {
                u.setEvaluacionActivada(true);
                if (OperacionesBD.modificar(u)) {
                    System.out.println("Evaluacion activada a: " + u.getNombre());
                }
            }
            oper = true;
        }
        if (!servidoresDisp.isEmpty()) {
            for (Usuario u : servidoresDisp) {
                u.setEvaluacionActivada(false);
                if (OperacionesBD.modificar(u)) {
                    System.out.println("Evaluacion desactivada a: " + u.getNombre());
                }
            }
            oper = true;
        }
        if (oper) {
            JOptionPane.showMessageDialog(null, "Operacion realizada correctamente ");
        } else {
            JOptionPane.showMessageDialog(null, "Error al realizar la operación");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResultadosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIr;
    private javax.swing.JButton btnNuevoNombre;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnResultados;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox cbNombres;
    private org.jdesktop.swingx.JXDatePicker dateDesde;
    private org.jdesktop.swingx.JXDatePicker dateHasta;
    private org.jdesktop.swingx.JXDatePicker dpDesde;
    private org.jdesktop.swingx.JXDatePicker dpHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblActividades;
    private javax.swing.JLabel lblApellNomb;
    private javax.swing.JLabel lblCompetTec;
    private javax.swing.JLabel lblCompetUniv;
    private javax.swing.JLabel lblConocimientos;
    private javax.swing.JLabel lblDesde;
    private javax.swing.JLabel lblFactCompTec;
    private javax.swing.JLabel lblFactor;
    private javax.swing.JLabel lblFactor1;
    private javax.swing.JLabel lblFactor2;
    private javax.swing.JLabel lblFactor3;
    private javax.swing.JLabel lblFactor4;
    private javax.swing.JLabel lblFactor5;
    private javax.swing.JLabel lblFactorConoc;
    private javax.swing.JLabel lblFactorTrab;
    private javax.swing.JLabel lblFactorUniv;
    private javax.swing.JLabel lblHasta;
    private javax.swing.JLabel lblNombreEvaluado;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JLabel lblPuestoDesemp;
    private javax.swing.JLabel lblSepDesde;
    private javax.swing.JLabel lblSepHasta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloProf;
    private javax.swing.JLabel lblTotActivEscen;
    private javax.swing.JList lstDisponibleParaEval;
    private javax.swing.JList lstParaEvaluar;
    private javax.swing.JPanel pnlAbajo;
    private javax.swing.JPanel pnlArriba;
    private javax.swing.JPanel pnlCabeceras;
    private javax.swing.JPanel pnlCinco;
    private javax.swing.JPanel pnlCompetTecnicas;
    private javax.swing.JPanel pnlCompetUniver;
    private javax.swing.JPanel pnlConocimientos;
    private javax.swing.JPanel pnlCuatro;
    private javax.swing.JPanel pnlDatosComp;
    private javax.swing.JPanel pnlDatosCompUnivers;
    private javax.swing.JPanel pnlDatosConoc;
    private javax.swing.JPanel pnlDatosIndic;
    private javax.swing.JPanel pnlDatosInf;
    private javax.swing.JPanel pnlDatosQuejas;
    private javax.swing.JPanel pnlDatosServidor;
    private javax.swing.JPanel pnlDatosTrabEquipo;
    private javax.swing.JPanel pnlDos;
    private javax.swing.JPanel pnlEvalServ;
    private javax.swing.JPanel pnlIndicGestionPuesto;
    private javax.swing.JPanel pnlInfoIndic;
    private javax.swing.JPanel pnlMedio;
    private javax.swing.JPanel pnlQuejas;
    private javax.swing.JPanel pnlTrabEquipo;
    private javax.swing.JPanel pnlTres;
    private javax.swing.JPanel pnlUno;
    private javax.swing.JScrollPane scrollDatosComp;
    private javax.swing.JScrollPane scrollDatosCompUnivers;
    private javax.swing.JScrollPane scrollDatosConoc;
    private javax.swing.JScrollPane scrollDatosIndic;
    private javax.swing.JScrollPane scrollDatosQuejas;
    private javax.swing.JScrollPane scrollDatosTrabEquipo;
    private javax.swing.JTabbedPane tabbedEvaluacion;
    private javax.swing.JTextArea txtBuenaCalificacion;
    private javax.swing.JTextArea txtDeficienteCalificacion;
    private javax.swing.JTextField txtFactorCompTec;
    private javax.swing.JTextField txtFactorConoc;
    private javax.swing.JTextField txtFactorIndic;
    private javax.swing.JTextField txtFactorTrab;
    private javax.swing.JTextField txtFactorUniv;
    private javax.swing.JTextField txtHoraDesde;
    private javax.swing.JTextField txtHoraHasta;
    private javax.swing.JTextArea txtIneficienteCalificacion;
    private javax.swing.JTextField txtMinDesde;
    private javax.swing.JTextField txtMinHasta;
    private javax.swing.JTextField txtNombreApellidos;
    private javax.swing.JTextField txtNroActividades;
    private javax.swing.JTextField txtNroCompetTecnic;
    private javax.swing.JTextField txtNroCompetUniv;
    private javax.swing.JTextField txtNroConocimientos;
    private javax.swing.JTextField txtPuesto;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTotActEsc;
    private javax.swing.JTextField txtTotalCompTec;
    private javax.swing.JTextField txtTotalCompUniv;
    private javax.swing.JTextField txtTotalConocimientos;
    private javax.swing.JTextField txtTotalQuejas;
    private javax.swing.JTextField txtTotalTrabEquip;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the pnlMedio
     */
    public javax.swing.JPanel getPnlMedio() {
        return pnlMedio;
    }

//    /**
//     * @return the cbServidores
//     */
//    public javax.swing.JComboBox getCbServidores() {
//        return cbServidores;
//    }
    /**
     * @return the btnAnterior
     */
    public javax.swing.JButton getBtnAnterior() {
        return btnAnterior;
    }

    /**
     * @return the btnSiguiente
     */
    public javax.swing.JButton getBtnSiguiente() {
        return btnSiguiente;
    }

    /**
     * @return the pnlDatosIndic
     */
    public javax.swing.JPanel getPnlDatosIndic() {
        return pnlDatosIndic;
    }

    /**
     * @return the pnlDatosConoc
     */
    public javax.swing.JPanel getPnlDatosConoc() {
        return pnlDatosConoc;
    }

    /**
     * @return the pnlDatosComp
     */
    public javax.swing.JPanel getPnlDatosComp() {
        return pnlDatosComp;
    }

    /**
     * @return the pnlDatosCompUnivers
     */
    public javax.swing.JPanel getPnlDatosCompUnivers() {
        return pnlDatosCompUnivers;
    }

    /**
     * @return the pnlDatosTrabEquipo
     */
    public javax.swing.JPanel getPnlDatosTrabEquipo() {
        return pnlDatosTrabEquipo;
    }

    /**
     * @return the btnResultados
     */
    public javax.swing.JButton getBtnResultados() {
        return btnResultados;
    }

//    /**
//     * @return the txtApellidosNombres
//     */
//    public javax.swing.JTextField getTxtApellidosNombres() {
//        return txtApellidosNombres;
//    }
//
//    /**
//     * @return the txtPuestoDesemp
//     */
//    public javax.swing.JTextField getTxtPuestoDesemp() {
//        return txtPuestoDesemp;
//    }
//
//    /**
//     * @return the txttituloProf
//     */
//    public javax.swing.JTextField getTxttituloProf() {
//        return txttituloProf;
//    }
    /**
     * @return the txtNombreApellidos
     */
    public javax.swing.JTextField getTxtNombreApellidos() {
        return txtNombreApellidos;
    }

    /**
     * @return the txtPuesto
     */
    public javax.swing.JTextField getTxtPuesto() {
        return txtPuesto;
    }

    /**
     * @return the txtTitulo
     */
    public javax.swing.JTextField getTxtTitulo() {
        return txtTitulo;
    }

    /**
     * @return the txtTotalConocimientos
     */
    public javax.swing.JTextField getTxtTotalConocimientos() {
        return txtTotalConocimientos;
    }

    /**
     * @return the txtNroActividades
     */
    public javax.swing.JTextField getTxtNroActividades() {
        return txtNroActividades;
    }

    /**
     * @return the txtNroConocimientos
     */
    public javax.swing.JTextField getTxtNroConocimientos() {
        return txtNroConocimientos;
    }

    /**
     * @return the txtNroCompetTecnic
     */
    public javax.swing.JTextField getTxtNroCompetTecnic() {
        return txtNroCompetTecnic;
    }

    /**
     * @return the txtNroCompetUniv
     */
    public javax.swing.JTextField getTxtNroCompetUniv() {
        return txtNroCompetUniv;
    }

    /**
     * @return the txtTotalCompTec
     */
    public javax.swing.JTextField getTxtTotalCompTec() {
        return txtTotalCompTec;
    }

    /**
     * @return the txtTotalCompUniv
     */
    public javax.swing.JTextField getTxtTotalCompUniv() {
        return txtTotalCompUniv;
    }

    /**
     * @return the txtTotalTrabEquip
     */
    public javax.swing.JTextField getTxtTotalTrabEquip() {
        return txtTotalTrabEquip;
    }

    /**
     * @return the pnlDatosQuejas
     */
    public javax.swing.JPanel getPnlDatosQuejas() {
        return pnlDatosQuejas;
    }

    /**
     * @return the txtTotalQuejas
     */
    public javax.swing.JTextField getTxtTotalQuejas() {
        return txtTotalQuejas;
    }

    class GestorControladorEvaluacion extends KeyAdapter implements ActionListener, ChangeListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == getBtnSiguiente()) {
                ce.siguientePanel();
            } else if (e.getSource() == getBtnAnterior()) {
                ce.anteriorPanel();
            } else if (e.getSource() == getBtnResultados()) {
                ce.resultadosFinales();
            } //            else if (e.getSource() == cbServidores) {
            //                ce.llenaServidorEscogido();
            //            } 
            else if (e.getSource() == btnGenerar) {
                generacionEval();
            } else if (e.getSource() == btnIr) {
                Date desde = dpDesde.getDate();
                Date hasta = dpHasta.getDate();
                ce.listarMetas(desde, hasta);
            }
        }

        public void generacionEval() {
            tabbedEvaluacion.setSelectedIndex(1);
//            ce.listarMetas();
            ce.listarSeccion();
            ce.listarCompetenciasTecnicas();
            ce.listarCompetenciasUniversales();
            ce.listarTrabajoEquipo();
            ce.listarQuejas();
            ControladorEvaluacion.txtTotalConoc = getTxtTotalConocimientos();
            ControladorEvaluacion.totConoc = 0;
        }

        @Override
        public void keyReleased(KeyEvent e) {
            if (e.getSource() == txtFactorConoc) {
                try {
                    ControladorEvaluacion.facConoc = Double.parseDouble(txtFactorConoc.getText()) / ControladorEvaluacion.secciones.size();
//                    System.out.println("Factor conocimiento: "+ControladorEvaluacion.facConoc);
                } catch (NumberFormatException nfe) {
                }
            } else if (e.getSource() == txtFactorCompTec) {
                try {
                    ControladorEvaluacion.facCompTec = Double.parseDouble(txtFactorCompTec.getText()) / ControladorEvaluacion.compTecnicas.size();
                    //System.out.println("Factor comp tec: "+ControladorEvaluacion.facCompTec+" "+ControladorEvaluacion.compTecnicas.size());
                } catch (NumberFormatException nfe) {
                }
            } else if (e.getSource() == txtFactorUniv) {
                try {
                    ControladorEvaluacion.facCompUniv = Double.parseDouble(txtFactorUniv.getText()) / ControladorEvaluacion.compUniversales.size();
                } catch (NumberFormatException nfe) {
                }
            } else if (e.getSource() == txtFactorTrab) {
                try {
                    if (FrmPrincipal.userLogueado.getRol().getTipo().equals(Constantes.JEFE)) {
                        ControladorEvaluacion.facTrabEquip = Double.parseDouble(txtFactorTrab.getText()) / ControladorEvaluacion.trabequip.size();
                    } else {
                        ControladorEvaluacion.facTrabEquip = Double.parseDouble(txtFactorTrab.getText()) / (ControladorEvaluacion.trabequip.size() - 1);
                    }
                } catch (NumberFormatException nfe) {
                }
            }
        }

        @Override
        public void stateChanged(ChangeEvent e) {
            if (tabbedEvaluacion.getSelectedIndex() == 1) {
                generacionEval();
            }
        }
    }
}
