/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.evaluacion;

/**
 *
 * @author francisco
 */
public class PnlIndic extends javax.swing.JPanel {

    /**
     * Creates new form PnlIndic
     */
    public PnlIndic(String texto) {
        initComponents();
        txtActividad.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMeta = new javax.swing.JTextField();
        txtCumplidos = new javax.swing.JTextField();
        txtPorcentaje = new javax.swing.JTextField();
        txtNivel = new javax.swing.JTextField();
        txtIndicador = new javax.swing.JTextField();
        txtActividad = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(902, 0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(902, 33));
        setRequestFocusEnabled(false);
        setLayout(null);

        txtMeta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtMeta);
        txtMeta.setBounds(460, 0, 120, 30);

        txtCumplidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtCumplidos);
        txtCumplidos.setBounds(580, 0, 110, 30);

        txtPorcentaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtPorcentaje);
        txtPorcentaje.setBounds(690, 0, 110, 30);

        txtNivel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtNivel);
        txtNivel.setBounds(800, 0, 100, 30);
        add(txtIndicador);
        txtIndicador.setBounds(270, 0, 190, 30);

        txtActividad.setEditable(false);
        add(txtActividad);
        txtActividad.setBounds(10, 0, 250, 30);
    }// </editor-fold>//GEN-END:initComponents
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtActividad;
    private javax.swing.JTextField txtCumplidos;
    private javax.swing.JTextField txtIndicador;
    private javax.swing.JTextField txtMeta;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtPorcentaje;
    // End of variables declaration//GEN-END:variables


    /**
     * @return the txtCumplidos
     */
    public javax.swing.JTextField getTxtCumplidos() {
        return txtCumplidos;
    }

    /**
     * @return the txtIndicador
     */
    public javax.swing.JTextField getTxtIndicador() {
        return txtIndicador;
    }

    /**
     * @return the txtMeta
     */
    public javax.swing.JTextField getTxtMeta() {
        return txtMeta;
    }

    /**
     * @return the txtNivel
     */
    public javax.swing.JTextField getTxtNivel() {
        return txtNivel;
    }

    /**
     * @return the txtPorcentaje
     */
    public javax.swing.JTextField getTxtPorcentaje() {
        return txtPorcentaje;
    }

    /**
     * @return the txtActividad
     */
    public javax.swing.JTextField getTxtActividad() {
        return txtActividad;
    }

    
    
}
