/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.evaluacion;

import controlador.acciones.agenda.ControladorItemAgenda;
import controlador.acciones.evaluaciones.ControladorEvaluacion;
import controlador.experto.BaseConocimiento;
import java.util.Date;
import modelo.agenda.Meta;
import vista.FrmPrincipal;
import vista.modelo.OperacionesVarias;

/**
 *
 * @author jenny
 */
public class PnlIndic extends javax.swing.JPanel {
 private ClassLoader cload = PnlIndic.class.getClassLoader();//para hacer referencia a archivos dentro del programa
    private String dirArchivo = cload.getResource("controlador/experto/evaluacion.pl").getPath();
    /**
     * Creates new form PnlIndic
     */
    public PnlIndic(Meta meta, Date desde, Date hasta) {
        initComponents();
        txtActividad.setText(meta.getActividad().getDescripcion());
        txtIndicador.setText(meta.getIndicador());
        txtMeta.setText(String.valueOf(meta.getValor()));
        int cumplidos = ControladorItemAgenda.searchItemAgendaTotalCumplido(
                meta.getActividad().getIdActividad(), desde, hasta,
                FrmPrincipal.userLogueado.getLogin());
        txtCumplidos.setText(String.valueOf(cumplidos));
        double per = calcPorcentaje(meta.getValor(), cumplidos);
        txtPorcentaje.setText(String.valueOf(per));
        txtNivel.setText(rptaTexto(per));
    }

    private double calcPorcentaje(int meta, int cumplidos) {
        double percent = (cumplidos * 100) / meta;
        if (percent > 100) {
            percent = 100;
        }
        return percent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMeta = new javax.swing.JTextField();
        txtCumplidos = new javax.swing.JTextField();
        txtPorcentaje = new javax.swing.JTextField();
        txtNivel = new javax.swing.JTextField();
        txtIndicador = new javax.swing.JTextField();
        txtActividad = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(902, 0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(902, 33));
        setRequestFocusEnabled(false);
        setLayout(null);

        txtMeta.setEditable(false);
        txtMeta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtMeta);
        txtMeta.setBounds(460, 0, 120, 30);

        txtCumplidos.setEditable(false);
        txtCumplidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtCumplidos);
        txtCumplidos.setBounds(580, 0, 110, 30);

        txtPorcentaje.setEditable(false);
        txtPorcentaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtPorcentaje);
        txtPorcentaje.setBounds(690, 0, 110, 30);

        txtNivel.setEditable(false);
        txtNivel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtNivel);
        txtNivel.setBounds(800, 0, 100, 30);

        txtIndicador.setEditable(false);
        add(txtIndicador);
        txtIndicador.setBounds(260, 0, 200, 30);

        txtActividad.setEditable(false);
        add(txtActividad);
        txtActividad.setBounds(10, 0, 250, 30);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtActividad;
    private javax.swing.JTextField txtCumplidos;
    private javax.swing.JTextField txtIndicador;
    private javax.swing.JTextField txtMeta;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtPorcentaje;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the txtCumplidos
     */
    public javax.swing.JTextField getTxtCumplidos() {
        return txtCumplidos;
    }

    /**
     * @return the txtIndicador
     */
    public javax.swing.JTextField getTxtIndicador() {
        return txtIndicador;
    }

    /**
     * @return the txtMeta
     */
    public javax.swing.JTextField getTxtMeta() {
        return txtMeta;
    }

    /**
     * @return the txtNivel
     */
    public javax.swing.JTextField getTxtNivel() {
        return txtNivel;
    }

    /**
     * @return the txtPorcentaje
     */
    public javax.swing.JTextField getTxtPorcentaje() {
        return txtPorcentaje;
    }

    /**
     * @return the txtActividad
     */
    public javax.swing.JTextField getTxtActividad() {
        return txtActividad;
    }

    public String rptaTexto(double porcentaje) {
        String s;
        BaseConocimiento bc = new BaseConocimiento();
        double r = OperacionesVarias.redondeaDosCifras(porcentaje);
        if (bc.compilaArchivo(dirArchivo)) {
            return bc.consultaSegundoElemento("indic(" + r + ",X)");
        }
        return null;
    }
}
