/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.evaluacion;

/**
 *
 * @author jenny
 */
public class PnlTextoResult extends javax.swing.JPanel {

    /**
     * Creates new form PnlTexto
     */
    public PnlTextoResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTexto = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(902, 0));
        setPreferredSize(new java.awt.Dimension(902, 35));
        setLayout(null);

        lblTexto.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        add(lblTexto);
        lblTexto.setBounds(10, 0, 890, 30);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTexto;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the lblTexto
     */
    public javax.swing.JLabel getLblTexto() {
        return lblTexto;
    }

    /**
     * @param lblTexto the lblTexto to set
     */
    public void setLblTexto(javax.swing.JLabel lblTexto) {
        this.lblTexto = lblTexto;
    }

}
