/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelSemana.java
 *
 * Created on 10/11/2012, 09:03:35 PM
 */

package vista.modelo.paneles.agenda;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import java.util.Vector;
import modelo.agenda.Agenda;
import modelo.proceso.Actividad;
import modelo.usuario.Usuario;
import vista.modelo.Fecha;

/**
 *
 * @author alf
 */
public class PanelSemana extends javax.swing.JPanel {

    /** Creates new form PanelSemana */
    private Calendar calendar;
    private Agenda agenda;
    private Actividad actividad;
    private Usuario usuario;
   
    public PanelSemana(Calendar calendar,Agenda agenda,Actividad actividad, Usuario usuario) {
        initComponents();
        this.usuario=usuario;
        this.agenda=agenda;
        this.calendar=calendar;
        this.actividad=actividad;
        iniciarSemana(usuario);
    }
    
    private void iniciarSemana(Usuario usuario){

        for (int i =0; i <7; i++) {
            PanelDiaHoras dia=new PanelDiaHoras(calendar,agenda,actividad, usuario);
            dia.setNombreDia(Fecha.getNombreDia(calendar.get(Calendar.DAY_OF_WEEK)));
            dia.setNumeroDia(calendar.get(Calendar.DAY_OF_MONTH));
            dia.setPreferredSize(new Dimension(550,dia.getPreferredSize().height));
            this.add(dia);
            calendar.add(Calendar.DATE, 1);
        }
        calendar.add(Calendar.DATE, -7);

    }
    public void refreshTareas(Calendar calendar){
       this.removeAll();
       this.calendar=calendar;
       iniciarSemana(usuario);
    }

    public Vector<PanelDiaHoras> getDias(){
        Vector<PanelDiaHoras> dias=new Vector<PanelDiaHoras>();
        Component []componentes=this.getComponents();
        for (int i = 0; i < componentes.length; i++) {
            Component component = componentes[i];
            if(component instanceof PanelDiaHoras){
                PanelDiaHoras panelDia=(PanelDiaHoras)component;
                dias.add(panelDia);
            }
        }
        return dias;
    }
    
    public PanelDiaHoras getDia(int diaMes){
        Component []componentes=this.getComponents();
        for (int i = 0; i < componentes.length; i++) {
            Component component = componentes[i];
            if(component instanceof PanelDiaHoras){
                PanelDiaHoras diaAux=(PanelDiaHoras)component;
               //System.out.println(diaAux.getNumeroDia()+":"+diaMes);
                if(diaAux.getNumeroDia()==diaMes){
                    return  diaAux;
                }else{
                    diaAux.getPanelContenedorTareas().setBackground(Color.darkGray);
                }
            }
        }
        return null;
    }
    public void marcarDiaActual(Date fechaActual){
        int diaMes=Integer.parseInt(Fecha.getFechaFormateada(fechaActual,"dd"));
        PanelDiaHoras diaActual=getDia(diaMes);
        if(diaActual!=null)
            diaActual.getPanelContenedorTareas().setBackground(Color.green);
        Vector<PanelDiaHoras> dias=getDias();
        for (Iterator<PanelDiaHoras> it = dias.iterator(); it.hasNext();) {
            PanelDiaHoras panelDia = it.next();
            panelDia.marcarHoraActual(fechaActual.getHours());
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents



    public Actividad getActividad() {
        return actividad;
    }

    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
        Vector<PanelDiaHoras> panelesDias =getDias();
        for (Iterator<PanelDiaHoras> it = panelesDias.iterator(); it.hasNext();) {
            PanelDiaHoras panelDiaHoras = it.next();
            panelDiaHoras.setActividad(actividad);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
