/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelHora.java
 *
 * Created on 10/11/2012, 03:46:59 PM
 */

package vista.modelo.paneles.agenda;

import controlador.acciones.servicios.ControladorAgenda;

import java.awt.Color;
import java.awt.Dimension;


/**
 *
 * @author alf
 */
public class PanelHora extends javax.swing.JPanel {

    /** Creates new form PanelHora */
    private int hora;
    public PanelHora(int hora) {
        initComponents();
        this.hora=hora;
        setHora(hora);
        this.setPreferredSize(new Dimension(
                                            (int)ControladorAgenda.CONSTATE_ESPACIO_TIEMPO,
                                            (int)ControladorAgenda.CONSTATE_ESPACIO_TIEMPO
                                            )
                             );
    }

    public int getHora() {
        return hora;
    }

    public void setHora(int hora) {
       this.hora=hora;
       lblHora.setText("Hora:"+hora+":00");
    }


    public Color getColorFondo() {
        return this.getBackground();
    }

    public void setColorFondo(Color color) {
        this.setBackground(color);
    }

     public Color getColorFuente() {
        return this.lblHora.getForeground();
    }

    public void setColorFuente(Color color) {
        this.lblHora.setForeground(color);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHora = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setMinimumSize(new java.awt.Dimension(60, 60));
        setPreferredSize(new java.awt.Dimension(200, 200));
        setLayout(new java.awt.BorderLayout());

        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("Hora");
        lblHora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHora.setPreferredSize(new java.awt.Dimension(100, 100));
        add(lblHora, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public boolean equals(Object obj) {
        if(obj instanceof PanelHora ){
            PanelHora panelH=(PanelHora)obj;
            if(panelH.getHora()==this.hora){
                return true;
            }
        }

        return false;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblHora;
    // End of variables declaration//GEN-END:variables

}
