/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelAgenda.java
 *
 * Created on 10/11/2012, 02:31:04 PM
 */

package vista.modelo.paneles.agenda;
import controlador.acciones.agenda.ControladorActividades;
import controlador.acciones.agenda.ControladorAgenda;
import controlador.acciones.agenda.ControladorDiasFeriados;


import controlador.acciones.agenda.ControladorItemAgenda;
import controlador.acciones.agenda.ControladorMeta;
import controlador.basedatos.Conexion;
import datechooser.beans.DateChooserPanel;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import modelo.agenda.Agenda;
import modelo.agenda.DiaFeriado;
import modelo.agenda.ItemAgenda;
import modelo.agenda.Meta;
import modelo.proceso.Actividad;
import modelo.usuario.Usuario;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
import vista.DialogDiasFeriados;
import vista.modelo.Fecha;
import vista.modelo.ImagenJPanel;
import vista.modelo.ModeloComboBoxActividad;
import vista.modelo.ModeloTablaItemInforme;
import vista.modelo.ModeloTablaMeta;
import vista.modelo.Reloj;

/**
 *
 * @author alf
 */
public class PanelAgenda extends ImagenJPanel {

    /** Creates new form PanelAgenda */
    private Date fechaActual;
    private String infoFecha;
    private String formatoFecha ;

    private PanelDiaHoras panelDia;
    private PanelSemana panelSemana;
    private PanelMes panelMes;
    private PanelTodasLasActividades panelTodasActividades;
    private PanelRecordatorio panelRecordatorio;
    private Thread hiloReloj;
    private Agenda agendaActual;
    public  static boolean guardar;
    private Usuario usuario;
    private LinkedList<Actividad>listaActividades;
    private ModeloTablaItemInforme modeloTablaInforme;
    public PanelAgenda(String dirImagen, Usuario usuario) {
        super(dirImagen);
        this.usuario=usuario;
        fechaActual=new Date();
        formatoFecha="yyyy/MM/dd HH:mm:ss";
        infoFecha="Fecha Seleccionada: ";
        modeloTablaInforme=new ModeloTablaItemInforme();
        modeloTablaInforme.setLoginUsuario(usuario.getLogin());
        initComponents();
//        panelAddActividad.setVisible(false);
        lblFechaSeleccionada.setText(infoFecha+Fecha.getFechaFormateada(fechaActual,"yyyy/MM/dd"));
        lblUsuario.setText("Usuario:"+usuario.getNombre()+" "+usuario.getApellidos());
        iniciarAgenda();
        iniciarServidores();
        hiloReloj=new Thread(new Reloj(this));
        hiloReloj.setDaemon(true);
        hiloReloj.start();
        guardar=false;
        seleccionarFecha();
    }
    private void iniciarServidores(){
       listaActividades=ControladorActividades.getAllActividades(usuario.getRol().getIdRol());
       cmbServidor.setModel(new ModeloComboBoxActividad(listaActividades));
    }
    private void iniciarAgenda(){
        // cargar agenda
        agendaActual=ControladorAgenda.getAgendaActual();
        Calendar c = Calendar.getInstance();
        if(agendaActual==null){
            JOptionPane.showMessageDialog(this,"No se ha encontrado una agenda para el año:"+c.get(Calendar.YEAR)+" se creara una nueva");
            agendaActual=ControladorAgenda.getInstance();
            agendaActual.setNombre(""+c.get(Calendar.YEAR));
        }
        //iniciar paneles agenda    
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentro = new javax.swing.JPanel();
        tabPane = new javax.swing.JTabbedPane();
        scPanelDia = new javax.swing.JScrollPane();
        scPanelSemana = new javax.swing.JScrollPane();
        scPanelMes = new javax.swing.JScrollPane();
        scPanelAgenda = new javax.swing.JScrollPane();
        scPanelRecordatorio = new javax.swing.JScrollPane();
        panelInforme = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInforme = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        fechaDesde = new datechooser.beans.DateChooserCombo();
        jLabel12 = new javax.swing.JLabel();
        fechaHasta = new datechooser.beans.DateChooserCombo();
        btnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bntImprimir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        panelNorte = new javax.swing.JPanel();
        lblFechaActual = new javax.swing.JLabel();
        panelSur = new javax.swing.JPanel();
        panelIzquierdo = new javax.swing.JPanel();
        lblFechaSeleccionada = new javax.swing.JLabel();
        dateChooserPanel1 = new datechooser.beans.DateChooserPanel();
        btGuardarAgenda = new javax.swing.JButton();
        panelAddActividad = new javax.swing.JPanel();
        lblHoraInicio = new javax.swing.JLabel();
        lblHpraTermina = new javax.swing.JLabel();
        spHoraInicio = new javax.swing.JSpinner();
        spMinutosInicio = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spHoraFinal = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        spMinutosFinal = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chbRecordar = new javax.swing.JCheckBox();
        cmbServidor = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnAddActividad = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblProceso = new javax.swing.JLabel();
        btnFeriado = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelCentro.setLayout(new java.awt.BorderLayout());

        tabPane.setName("tabs"); // NOI18N
        tabPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabPaneStateChanged(evt);
            }
        });

        scPanelDia.setMaximumSize(new java.awt.Dimension(600, 400));
        scPanelDia.setName("dia"); // NOI18N
        tabPane.addTab("Día", scPanelDia);

        scPanelSemana.setName("semana"); // NOI18N
        tabPane.addTab("Semana", scPanelSemana);

        scPanelMes.setName("mes"); // NOI18N
        tabPane.addTab("Mes", scPanelMes);

        scPanelAgenda.setName("agenda"); // NOI18N
        tabPane.addTab("Agenda", scPanelAgenda);

        scPanelRecordatorio.setName("recordatorio"); // NOI18N
        tabPane.addTab("Recordar", scPanelRecordatorio);

        panelInforme.setName("informe"); // NOI18N
        panelInforme.setLayout(new java.awt.BorderLayout());

        tablaInforme.setModel(modeloTablaInforme);
        jScrollPane1.setViewportView(tablaInforme);

        panelInforme.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel11.setText("Fecha desde:");
        jPanel1.add(jLabel11);
        jPanel1.add(fechaDesde);

        jLabel12.setText("Fecha hasta:");
        jPanel1.add(jLabel12);
        jPanel1.add(fechaHasta);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar);

        panelInforme.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        bntImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/printer1.png"))); // NOI18N
        bntImprimir.setText("Imprimir");
        bntImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntImprimirActionPerformed(evt);
            }
        });
        jPanel2.add(bntImprimir);

        panelInforme.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        tabPane.addTab("Informe", panelInforme);

        panelCentro.add(tabPane, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblUsuario.setText("Usuario:");
        jPanel3.add(lblUsuario);

        panelCentro.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        add(panelCentro, java.awt.BorderLayout.CENTER);

        panelNorte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelNorte.setOpaque(false);

        lblFechaActual.setText("Fecha Actual:");
        panelNorte.add(lblFechaActual);

        add(panelNorte, java.awt.BorderLayout.PAGE_START);

        panelSur.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelSur.setOpaque(false);
        add(panelSur, java.awt.BorderLayout.PAGE_END);

        panelIzquierdo.setOpaque(false);
        panelIzquierdo.setPreferredSize(new java.awt.Dimension(340, 437));

        lblFechaSeleccionada.setText("Fecha Seleccionada:");

        dateChooserPanel1.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                dateChooserPanel1OnSelectionChange(evt);
            }
        });

        btGuardarAgenda.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btGuardarAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Save.png"))); // NOI18N
        btGuardarAgenda.setText("Guardar");
        btGuardarAgenda.setToolTipText("Guardar la información de las actividades ingresadas en la Agenda");
        btGuardarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarAgendaActionPerformed(evt);
            }
        });

        panelAddActividad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblHoraInicio.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblHoraInicio.setText("Inicia:");

        lblHpraTermina.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblHpraTermina.setText("Termina:");

        spHoraInicio.setModel(new javax.swing.SpinnerNumberModel(8, 0, 23, 1));

        spMinutosInicio.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel2.setText(":");

        jLabel3.setText("H");

        jLabel4.setText("min");

        spHoraFinal.setModel(new javax.swing.SpinnerNumberModel(9, 0, 23, 1));

        jLabel5.setText("H");

        spMinutosFinal.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel7.setText("min");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/bell.png"))); // NOI18N

        chbRecordar.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        chbRecordar.setText("Recordar");
        chbRecordar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chbRecordar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        cmbServidor.setPreferredSize(new java.awt.Dimension(200, 24));
        cmbServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbServidorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel1.setText("Actividad:");

        btnAddActividad.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnAddActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/list-add.png"))); // NOI18N
        btnAddActividad.setText("Agregar");
        btnAddActividad.setToolTipText("Agregar actividad");
        btnAddActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActividadActionPerformed(evt);
            }
        });

        jLabel9.setText(":");

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel10.setText("Proceso:");

        lblProceso.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblProceso.setText("Proceso");

        javax.swing.GroupLayout panelAddActividadLayout = new javax.swing.GroupLayout(panelAddActividad);
        panelAddActividad.setLayout(panelAddActividadLayout);
        panelAddActividadLayout.setHorizontalGroup(
            panelAddActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddActividadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddActividadLayout.createSequentialGroup()
                        .addGroup(panelAddActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAddActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAddActividadLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(chbRecordar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddActividad))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAddActividadLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(5, 5, 5)
                                    .addComponent(cmbServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelAddActividadLayout.createSequentialGroup()
                                .addComponent(lblHpraTermina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spMinutosFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(panelAddActividadLayout.createSequentialGroup()
                                .addComponent(lblHoraInicio)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2)
                                .addGap(1, 1, 1)
                                .addComponent(spMinutosInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelAddActividadLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblProceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAddActividadLayout.setVerticalGroup(
            panelAddActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddActividadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddActividadLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))
                    .addComponent(cmbServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddActividadLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addComponent(lblProceso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraInicio)
                    .addComponent(spHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spMinutosInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(panelAddActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHpraTermina)
                    .addComponent(spHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spMinutosFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(19, 19, 19)
                .addGroup(panelAddActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(panelAddActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chbRecordar)
                        .addComponent(btnAddActividad)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFeriado.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnFeriado.setText("Feriado");
        btnFeriado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeriadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIzquierdoLayout = new javax.swing.GroupLayout(panelIzquierdo);
        panelIzquierdo.setLayout(panelIzquierdoLayout);
        panelIzquierdoLayout.setHorizontalGroup(
            panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooserPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelIzquierdoLayout.createSequentialGroup()
                        .addComponent(lblFechaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFeriado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panelIzquierdoLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btGuardarAgenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAddActividad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelIzquierdoLayout.setVerticalGroup(
            panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaSeleccionada)
                    .addComponent(btnFeriado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateChooserPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelAddActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGuardarAgenda)
                .addContainerGap())
        );

        add(panelIzquierdo, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void dateChooserPanel1OnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dateChooserPanel1OnSelectionChange
        // TODO add your handling code here:
//        if(cmbServidor.getSelectedIndex()>-1){
            seleccionarFecha();
}//GEN-LAST:event_dateChooserPanel1OnSelectionChange
private void seleccionarFecha(){
    Calendar calendario=dateChooserPanel1.getSelectedDate();
            //ControladorAgenda.changeAgenda(""+calendario.getTime().getYear());
            lblFechaSeleccionada.setText(infoFecha+Fecha.getFechaFormateada(calendario.getTime(), "yyyy/MM/dd"));
            //Actividad actividad=new Actividad();//listaActividades.get(cmbServidor.getSelectedIndex());
           
                panelTodasActividades=new PanelTodasLasActividades(calendario,agendaActual,usuario);
                panelDia=new PanelDiaHoras(calendario,agendaActual,null,usuario);
                panelSemana=new PanelSemana(calendario,agendaActual,null,usuario);
                panelMes=new PanelMes(calendario,agendaActual,usuario);
                panelRecordatorio=new PanelRecordatorio(calendario,agendaActual,usuario);
         
            scPanelDia.getVerticalScrollBar().setValue(panelDia.getHeight()/2);
            loadPanel(scPanelDia, panelDia);
            loadPanel(scPanelSemana, panelSemana);
            loadPanel(scPanelMes, panelMes);
            loadPanel(scPanelAgenda, panelTodasActividades);
            loadPanel(scPanelRecordatorio, panelRecordatorio);
            
            scPanelDia.getVerticalScrollBar().setValue(scPanelDia.getHeight()/3);
            scPanelSemana.getVerticalScrollBar().setValue(scPanelSemana.getHeight()/3);
}
    private void btGuardarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarAgendaActionPerformed
        // TODO add your handling code here:
        if(guardar){
            ControladorAgenda.updateAgenda();
            guardar=false;
        }else{
            JOptionPane.showMessageDialog(panelSemana,"No se han agrgado nuevas actividades ni se han hecho modificaciones");
        } 
    }//GEN-LAST:event_btGuardarAgendaActionPerformed

    private void tabPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPaneStateChanged
        // TODO add your handling code here:
        Calendar calendario=dateChooserPanel1.getSelectedDate();
        refrescarGUIAgenda(calendario);
    }//GEN-LAST:event_tabPaneStateChanged
    public void refrescarGUIAgenda(Calendar calendario){
         if(tabPane.getSelectedComponent().getName().equals("dia")){
            if(panelDia!=null)
                panelDia.refreshTareas(calendario);
        }else if(tabPane.getSelectedComponent().getName().equals("semana")){
             if(panelSemana!=null)
                panelSemana.refreshTareas(calendario);
        }else if(tabPane.getSelectedComponent().getName().equals("mes")){
            if(panelMes!=null)
                panelMes.refreshTareas(calendario);
        }else if(tabPane.getSelectedComponent().getName().equals("recordatorio")){
            if(panelRecordatorio!=null)
                panelRecordatorio.refreshTareas(calendario);
        }else if(tabPane.getSelectedComponent().getName().equals("agenda")){
             if(panelTodasActividades!=null)
                panelTodasActividades.refreshTareas(calendario);
        }
    }
    private void btnAddActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActividadActionPerformed
        // TODO add your handling code here:
        if(panelDia==null){
            JOptionPane.showMessageDialog(panelSemana,"Error primero tiene que seleccionar un dia del calendario");
            return;
        }    
         Calendar calendario=dateChooserPanel1.getSelectedDate();
         Calendar calendarioActual=Calendar.getInstance();
        if(calendario.getInstance().getTime().getTime()<calendarioActual.getTime().getTime()){
            JOptionPane.showMessageDialog(panelSemana,"Error no se pueden crear actividades en fechas pasadas");
            return ;
        } 
        if(cmbServidor.getSelectedIndex()>-1){
            if (calendario!=null) {
                  ItemAgenda itemAgenda=new ItemAgenda();
                  Actividad actividad= ((ModeloComboBoxActividad)cmbServidor.getModel()).getSelectedActividad();
                  itemAgenda.setActividad(actividad);
                  itemAgenda.setNombre_actividad(actividad.getNombreActividad());

                  String nombreDia=Fecha.getNombreDia(calendario.get(Calendar.DAY_OF_WEEK));
                  int numeroDia=calendario.get(Calendar.DATE);
                  int numeroMes=calendario.get(Calendar.MONTH);
                  
                  List<DiaFeriado> dias=ControladorDiasFeriados.searchDiaFeriado(nombreDia, Fecha.getNombreMes(numeroMes), numeroDia, agendaActual.getId());
                  if(dias!=null){
                      if(dias.size()>0){
                          JOptionPane.showMessageDialog(this,"Exepción no se puede crear actividades en dias feriados");
                          return;
                      }
                  }
                  
                  Date fecha=new Date();
                  itemAgenda.setActividad(actividad);
                  if(actividad!=null)
                      itemAgenda.setNombre_actividad(actividad.getNombreActividad());
                      itemAgenda.setMes(Fecha.getNombreMes(numeroMes));
                      itemAgenda.setDia_del_mes(numeroDia+"");
                      itemAgenda.setDia(nombreDia);
                      itemAgenda.setFecha(new Date());
                      itemAgenda.setAgenda(agendaActual);
                      itemAgenda.setHoraInicio(new Date(fecha.getYear(),
                                                     numeroMes,
                                                     numeroDia,
                                                     Integer.parseInt(spHoraInicio.getValue().toString()),
                                                     Integer.parseInt(spMinutosInicio.getValue().toString())
                                                     ));

                      itemAgenda.setHoraFin(new Date(fecha.getYear(),
                                                     numeroMes,
                                                     numeroDia,
                                                     Integer.parseInt(spHoraFinal.getValue().toString()),
                                                     Integer.parseInt(spMinutosFinal.getValue().toString())
                                                     ));
                    itemAgenda.setTiempoDuracion(fecha);
                    double h=Integer.parseInt(spHoraFinal.getValue().toString())-Integer.parseInt(spHoraInicio.getValue().toString());
                    double m=Integer.parseInt(spMinutosFinal.getValue().toString())-Integer.parseInt(spMinutosInicio.getValue().toString());
                    m=h*60+m;
                    h=m/60;
                    m=(h-(int)h)*60;
                    m=Math.round(m);
                    ControladorItemAgenda.setTiempoDuracion(itemAgenda,
                                                            (int)h,
                                                            (int)m);
                    if(agendaActual.getItemsAgenda().contains(itemAgenda)){
                        JOptionPane.showMessageDialog(panelSemana,"Error no se pudo agregar la actividad ya existe");
                        return;
                    }
                      agendaActual.getItemsAgenda().add(itemAgenda);
                      refrescarGUIAgenda(calendario);
                      spHoraInicio.setValue(8);
                      spHoraFinal.setValue(9);
                      PanelAgenda.guardar=true;
                      scPanelDia.repaint();
            }else{
                JOptionPane.showMessageDialog(panelSemana,"Error primero tiene que seleccionar fecha del calendario");
            }
        }else{
            JOptionPane.showMessageDialog(panelSemana,"Error primero tiene que seleccionar una actividad");
        }
    }//GEN-LAST:event_btnAddActividadActionPerformed

    private void btnFeriadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeriadoActionPerformed
        // TODO add your handling code here:
        DialogDiasFeriados dialogoAgenda = new DialogDiasFeriados(new JFrame(),agendaActual, true);
        dialogoAgenda.setLocationRelativeTo(null);
        dialogoAgenda.setVisible(true);
    }//GEN-LAST:event_btnFeriadoActionPerformed

    private void cmbServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbServidorActionPerformed
        // TODO add your handling code here:
         Actividad actividad= ((ModeloComboBoxActividad)cmbServidor.getModel()).getSelectedActividad();
        if(actividad!=null)
            lblProceso.setText(actividad.getProcesito().getNombreProceso());
    }//GEN-LAST:event_cmbServidorActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Date fDesde=fechaDesde.getSelectedDate().getTime();
        Date fHasta=fechaHasta.getSelectedDate().getTime();
        modeloTablaInforme.setFechaInicio(fDesde);
        modeloTablaInforme.setFechFin(fHasta);
        //item.getActividad().getRol().getUsuario().equals(usuario)
        modeloTablaInforme.setMetas(new LinkedList<Meta>(ControladorMeta.searchMetas(fDesde,
                                                                                     fHasta,
                                                                                     usuario.getLogin()
                                                                                      )
                                                         ));  
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void bntImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntImprimirActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            JRTableModelDataSource datos = new JRTableModelDataSource(tablaInforme.getModel());
            String dirReporte = "./reportes/reporteInforme.jrxml";
            JasperReport report = JasperCompileManager.compileReport(dirReporte);
            Map<String, Object> parametros = new HashMap<String, Object>();
            parametros.put("Titulo 1", "Titulo 1");
            parametros.put("prm_fecha_desde", Fecha.getFechaFormateada(fechaDesde.getSelectedDate().getTime(), "yyyy/MM/dd"));
            parametros.put("prm_fecha_hasta", Fecha.getFechaFormateada(fechaHasta.getSelectedDate().getTime(), "yyyy/MM/dd"));
            //JasperPrint jp = JasperFillManager.fillReport(report, parametros, Conexion.conectate());
            JasperPrint jp = JasperFillManager.fillReport(report, parametros, datos); //datos
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(PanelAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bntImprimirActionPerformed
public void loadPanel(JScrollPane panelScroll, JPanel panel){
        panelScroll.getViewport().removeAll();
        panelScroll.setViewportView(panel);
        panelScroll.validate();
}

    public JLabel getLblFechaActual() {
        return lblFechaActual;
    }

    public void setLblFechaActual(JLabel lblFechaActual) {
        this.lblFechaActual = lblFechaActual;
    }

    public PanelDiaHoras getPanelDia() {
        return panelDia;
    }

    public void setPanelDia(PanelDiaHoras panelDia) {
        this.panelDia = panelDia;
    }

    public PanelMes getPanelMes() {
        return panelMes;
    }

    public void setPanelMes(PanelMes panelMes) {
        this.panelMes = panelMes;
    }

    public PanelSemana getPanelSemana() {
        return panelSemana;
    }

    public void setPanelSemana(PanelSemana panelSemana) {
        this.panelSemana = panelSemana;
    }

    public String getFormatoFecha() {
        return formatoFecha;
    }

    public void setFormatoFecha(String formatoFecha) {
        this.formatoFecha = formatoFecha;
    }

    public DateChooserPanel getDateChooserPanel1() {
        return dateChooserPanel1;
    }

    public void setDateChooserPanel1(DateChooserPanel dateChooserPanel1) {
        this.dateChooserPanel1 = dateChooserPanel1;
    }

    public JLabel getLblFechaSeleccionada() {
        return lblFechaSeleccionada;
    }

    public void setLblFechaSeleccionada(JLabel lblFechaSeleccionada) {
        this.lblFechaSeleccionada = lblFechaSeleccionada;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntImprimir;
    private javax.swing.JButton btGuardarAgenda;
    private javax.swing.JButton btnAddActividad;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnFeriado;
    private javax.swing.JCheckBox chbRecordar;
    private javax.swing.JComboBox cmbServidor;
    private datechooser.beans.DateChooserPanel dateChooserPanel1;
    private datechooser.beans.DateChooserCombo fechaDesde;
    private datechooser.beans.DateChooserCombo fechaHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFechaActual;
    private javax.swing.JLabel lblFechaSeleccionada;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblHpraTermina;
    private javax.swing.JLabel lblProceso;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelAddActividad;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelInforme;
    private javax.swing.JPanel panelIzquierdo;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelSur;
    private javax.swing.JScrollPane scPanelAgenda;
    private javax.swing.JScrollPane scPanelDia;
    private javax.swing.JScrollPane scPanelMes;
    private javax.swing.JScrollPane scPanelRecordatorio;
    private javax.swing.JScrollPane scPanelSemana;
    private javax.swing.JSpinner spHoraFinal;
    private javax.swing.JSpinner spHoraInicio;
    private javax.swing.JSpinner spMinutosFinal;
    private javax.swing.JSpinner spMinutosInicio;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tablaInforme;
    // End of variables declaration//GEN-END:variables

    public Agenda getAgendaActual() {
        return agendaActual;
    }

    public void setAgendaActual(Agenda agendaActual) {
        this.agendaActual = agendaActual;
    }



}
