/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelTodasLasActividades.java
 *
 * Created on 02/12/2012, 01:00:38 PM
 */

package vista.modelo.paneles.agenda;

import java.awt.Color;
import java.util.Calendar;
import java.util.Iterator;
import modelo.agenda.Agenda;
import modelo.agenda.ItemAgenda;
import modelo.usuario.Usuario;
import vista.modelo.Fecha;

/**
 *
 * @author alf
 */
public class PanelTodasLasActividades extends javax.swing.JPanel {

    /** Creates new form PanelTodasLasActividades */
    private Calendar calendario;
    private Agenda agenda;
    private Usuario usuario;
    public PanelTodasLasActividades(Calendar calendar, Agenda agenda) {
        initComponents();
        this.calendario=calendar;
        this.agenda=agenda;
        iniciarTareas();
    }
    public PanelTodasLasActividades(Calendar calendar, Agenda agenda,Usuario usuario) {
        initComponents();
        this.usuario=usuario;
        this.calendario=calendar;
        this.agenda=agenda;
        iniciarTareas(usuario);
    }
    private void iniciarTareas(){
         //calendario.add(Calendar.DATE, -1);// Regresar mes anterior         
        for (Iterator<ItemAgenda> it = agenda.getItemsAgenda().iterator(); it.hasNext();) {
            ItemAgenda item = it.next();
            //System.out.println(item.getMes()+"="+Fecha.getNombreMes(calendario.get(Calendar.MONTH)));
             if(item.getMes().equals(Fecha.getNombreMes(calendario.get(Calendar.MONTH)))){
                //System.out.println("Agregado--------");
                PanelActividad panelActividad=new PanelActividad(true,item,panelContenedor);
                if(item.getActividad()!=null){
                    panelActividad.setTxtActividad(item.getActividad().getTipoActividad());
                     if(item.getActividad().getRol()!=null){
                        panelActividad.setTxtEncargado(item.getActividad().getRol().getUsuario().getNombre()+" "+item.getActividad().getRol().getUsuario().getApellidos());
                        panelActividad.setTxtCargo(item.getActividad().getRol().getCargo());
                    }
                 }
                panelActividad.setTxtFecha(item.getDia()+" "+item.getDia_del_mes()+" "+item.getMes());
                panelActividad.setTxtHoraInicia(item.getHoraInicio());
                panelActividad.setTxtHoraTermina(item.getHoraFin());
                panelActividad.setTiempoDuracion(item.getTiempoDuracion());

//                panelActividad.setBackground(Color.orange);
                panelContenedor.add(panelActividad);
                panelContenedor.revalidate();
            }

        }
    }
     private void iniciarTareas(Usuario usuario){
         //calendario.add(Calendar.DATE, -1);// Regresar mes anterior
        for (Iterator<ItemAgenda> it = agenda.getItemsAgenda().iterator(); it.hasNext();) {
            ItemAgenda item = it.next();
            //System.out.println(item.getMes()+"="+Fecha.getNombreMes(calendario.get(Calendar.MONTH)));
             if(item.getMes().equals(Fecha.getNombreMes(calendario.get(Calendar.MONTH)))&& item.getActividad()!=null){
                //System.out.println("Agregado--------");
                if(item.getActividad().getRol().getUsuario().equals(usuario)){
                 PanelActividad panelActividad=new PanelActividad(true,item,panelContenedor);
                 panelActividad.setTxtActividad(item.getActividad().getTipoActividad());
                     if(item.getActividad().getRol()!=null){
                        panelActividad.setTxtEncargado(item.getActividad().getRol().getUsuario().getNombre()+" "+item.getActividad().getRol().getUsuario().getApellidos());
                        panelActividad.setTxtCargo(item.getActividad().getRol().getCargo());
                    }

                    panelActividad.setTxtFecha(item.getDia()+" "+item.getDia_del_mes()+" "+item.getMes());
                    panelActividad.setTxtHoraInicia(item.getHoraInicio());
                    panelActividad.setTxtHoraTermina(item.getHoraFin());
                    panelActividad.setTiempoDuracion(item.getTiempoDuracion());
    //                panelActividad.setBackground(Color.orange);
                    panelContenedor.add(panelActividad);
                    panelContenedor.revalidate();
                 }


            }

        }
    }
    public void refreshTareas(Calendar calendar){
        panelContenedor.removeAll();
        this.calendario=calendar;
        if(usuario==null)
            iniciarTareas();
        else 
            iniciarTareas(usuario);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        panelContenedor = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(new java.awt.BorderLayout());

        panelContenedor.setLayout(new javax.swing.BoxLayout(panelContenedor, javax.swing.BoxLayout.Y_AXIS));
        scrollPane.setViewportView(panelContenedor);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

}
