/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.basedatos.OperacionesBD;
import controlador.reportes.EvaluacionResultados;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.evaluacion.Evaluacion;

/**
 *
 * @author francisco
 */
public class DialogoImprimeAnalisisEval extends javax.swing.JDialog {
private static DialogoImprimeAnalisisEval dia = null;
    /**
     * Creates new form DialogoImprimeAnalisisEval
     */
    private DialogoImprimeAnalisisEval(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public static final DialogoImprimeAnalisisEval getInstance(Frame parent, boolean modal){
        if(dia == null){
            dia = new DialogoImprimeAnalisisEval(parent, modal);
        }
        return dia;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dpHasta = new org.jdesktop.swingx.JXDatePicker();
        dpDesde = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRepAnalisis = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REPORTE ANALISIS EVALUACIÓN DE RESULTADOS");
        getContentPane().setLayout(null);

        jLabel1.setText("Hasta:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 20, 70, 30);

        jLabel2.setText("Desde:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 70, 30);
        getContentPane().add(dpHasta);
        dpHasta.setBounds(310, 20, 170, 30);
        getContentPane().add(dpDesde);
        dpDesde.setBounds(70, 20, 170, 30);

        tblRepAnalisis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblRepAnalisis);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 660, 220);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(370, 300, 100, 40);

        btnImprimir.setText("Imprimir");
        getContentPane().add(btnImprimir);
        btnImprimir.setBounds(260, 300, 100, 40);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(500, 20, 80, 30);

        setSize(new java.awt.Dimension(716, 384));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        actualizaTabla();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnImprimir;
    private org.jdesktop.swingx.JXDatePicker dpDesde;
    private org.jdesktop.swingx.JXDatePicker dpHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRepAnalisis;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Evaluacion> evals;
    private ArrayList<EvaluacionResultados> evres;

    private void listarEvaluaciones() {
        if (dpDesde.getDate() != null && dpHasta.getDate() != null) {
            Date desde = dpDesde.getDate();
            Date hasta = dpHasta.getDate();
            evals = new ArrayList<>();
            ArrayList<Evaluacion> evaluaciones = (ArrayList<Evaluacion>) OperacionesBD.listar("Evaluacion");
            for (Evaluacion e : evaluaciones) {
                if ((e.getFechaEvaluacion().getTime().after(desde)
                        && e.getFechaEvaluacion().getTime().before(hasta))
                        ||e.getFechaEvaluacion().getTime().equals(desde)) {
                    evals.add(e);
                }
            }
            evres = new ArrayList<>();
            for(Evaluacion e: evals){
                EvaluacionResultados er = new EvaluacionResultados();
                er.setApellidos(e.getUsuarioEval().getApellidos());
                er.setNombres(e.getUsuarioEval().getNombre());
                er.setCedula(e.getUsuarioEval().getCedula());
                er.setPuesto(e.getUsuarioEval().getRol().getCargo());
                er.setCalifJefe(String.valueOf(e.getTotalEval()-e.getEvalciud()));
                er.setCalifCiud(String.valueOf(e.getEvalciud()));
                er.setCalifTotal(String.valueOf(e.getTotalEval()));
                evres.add(er);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese las fechas de las que quiere la evaluacion");
        }
    }
    
    private void poneTabla(){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Apellidos");
        dtm.addColumn("Nombres");
        dtm.addColumn("Puesto");
        dtm.addColumn("Calificacion Jefe");
        dtm.addColumn("Calificacion Ciud");
        dtm.addColumn("Calificacion Total");
                
        for(EvaluacionResultados er : evres){
            Object[] r = new Object[6];
            r[0]= er.getApellidos();
            r[1]= er.getNombres();
            r[2]= er.getPuesto();
            r[3]= er.getCalifJefe();
            r[4]= er.getCalifCiud();
            r[5]= er.getCalifTotal();
            dtm.addRow(r);
        }
        tblRepAnalisis.setModel(dtm);
    }
    
    private void actualizaTabla(){
        listarEvaluaciones();
        poneTabla();
    }
    
}
