/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.acciones.Constantes;
import controlador.acciones.ControladorPrincipal;
import controlador.basedatos.OperacionesBD;
import java.util.ArrayList;
import modelo.usuario.Usuario;

/**
 *
 * @author jenny
 */
public class DialogUsuaroisInforme extends javax.swing.JDialog {
    
    private ArrayList<Usuario> servidores;

    /**
     * Creates new form DialogUsuaroisInforme
     */
    public DialogUsuaroisInforme(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listaServidores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbServidores = new javax.swing.JComboBox();
        btnAceptar = new javax.swing.JButton();
        dateChooserPanel1 = new datechooser.beans.DateChooserPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(cbServidores);
        cbServidores.setBounds(40, 30, 310, 30);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(150, 300, 110, 40);
        getContentPane().add(dateChooserPanel1);
        dateChooserPanel1.setBounds(10, 70, 380, 220);

        setSize(new java.awt.Dimension(410, 382));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        ControladorPrincipal.rol = servidores.get(cbServidores.getSelectedIndex()).getRol();
        ControladorPrincipal.abreInformeActividades();
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox cbServidores;
    private datechooser.beans.DateChooserPanel dateChooserPanel1;
    // End of variables declaration//GEN-END:variables

    private void listaServidores() {
        ArrayList<Usuario> us = (ArrayList<Usuario>) OperacionesBD.listar("Usuario");
        servidores = new ArrayList<>();
        for (Usuario u : us) {
            if (u.getRol().getTipo().equals(Constantes.SERVIDOR)) {
                servidores.add(u);
            }
        }
        for (Usuario u : servidores) {
            cbServidores.addItem(u.getNombre() + " " + u.getApellidos());
        }
    }
}
