/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogoEditarItemAgenda.java
 *
 * Created on 20/01/2013, 04:38:43 AM
 */

package vista;

import controlador.acciones.agenda.ControladorActividades;
import controlador.acciones.agenda.ControladorItemAgenda;
import java.util.LinkedList;
import javax.swing.JDialog;
import modelo.agenda.ItemAgenda;
import modelo.proceso.Actividad;
import vista.modelo.ModeloComboBoxActividad;


/**
 *
 * @author alf
 */
public class DialogoEditarItemAgenda extends javax.swing.JDialog {

    /** Creates new form DialogoEditarItemAgenda */
    private ItemAgenda itemAgenda;
    private LinkedList<Actividad>listaActividades;
    public DialogoEditarItemAgenda(java.awt.Frame parent, boolean modal,ItemAgenda itemAgenda) {
        super(parent, modal);
        this.itemAgenda=itemAgenda;
        initComponents();
        iniciarServidores();
        iniciarItem();
        setLocationRelativeTo(parent);
    }
    public DialogoEditarItemAgenda(JDialog parent, boolean modal,ItemAgenda itemAgenda) {
        super(parent, modal);
        this.itemAgenda=itemAgenda;
        initComponents();
        iniciarServidores();
        iniciarItem();
        setLocationRelativeTo(parent);
    }
    private void iniciarItem(){
           spHoraInicio.setValue(itemAgenda.getHoraInicio().getHours());
           spMinutosInicio.setValue(itemAgenda.getHoraInicio().getMinutes());
           spHoraFinal.setValue(itemAgenda.getHoraFin().getHours());
           spMinutosFinal.setValue(itemAgenda.getHoraFin().getMinutes());
           chbRecordar.setSelected(itemAgenda.isRecordar());
        if(itemAgenda.getActividad()!=null){
           int index=((ModeloComboBoxActividad)cmbServidor.getModel()).getIndex(itemAgenda.getActividad());
           if(index>-1)
                cmbServidor.setSelectedIndex(index);
        }
    }
    private void iniciarServidores(){
       listaActividades=ControladorActividades.getAllActividades();
       cmbServidor.setModel(new ModeloComboBoxActividad(listaActividades));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentro = new javax.swing.JPanel();
        lblHoraInicio = new javax.swing.JLabel();
        lblHpraTermina = new javax.swing.JLabel();
        spHoraInicio = new javax.swing.JSpinner();
        spMinutosInicio = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spHoraFinal = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spMinutosFinal = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chbRecordar = new javax.swing.JCheckBox();
        panelNorte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbServidor = new javax.swing.JComboBox();
        panelSur = new javax.swing.JPanel();
        btAceptar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EDITAR");

        lblHoraInicio.setText("Inicia:");

        lblHpraTermina.setText("Termina:");

        spHoraInicio.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        spMinutosInicio.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));

        jLabel2.setText(":");

        jLabel3.setText("H");

        jLabel4.setText("min");

        spHoraFinal.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jLabel5.setText("H");

        jLabel6.setText(":");

        spMinutosFinal.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));

        jLabel7.setText("min");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/bell.png"))); // NOI18N

        chbRecordar.setText("Recordar");
        chbRecordar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chbRecordar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout panelCentroLayout = new javax.swing.GroupLayout(panelCentro);
        panelCentro.setLayout(panelCentroLayout);
        panelCentroLayout.setHorizontalGroup(
            panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCentroLayout.createSequentialGroup()
                        .addComponent(lblHoraInicio)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(spMinutosInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(panelCentroLayout.createSequentialGroup()
                        .addComponent(lblHpraTermina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6)
                        .addGap(1, 1, 1)
                        .addComponent(spMinutosFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(panelCentroLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbRecordar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        panelCentroLayout.setVerticalGroup(
            panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentroLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraInicio)
                    .addComponent(spHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spMinutosInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHpraTermina)
                    .addComponent(spHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spMinutosFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(19, 19, 19)
                .addGroup(panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(chbRecordar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

        panelNorte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Actividad:");
        panelNorte.add(jLabel1);

        cmbServidor.setPreferredSize(new java.awt.Dimension(200, 24));
        panelNorte.add(cmbServidor);

        getContentPane().add(panelNorte, java.awt.BorderLayout.PAGE_START);

        panelSur.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelSur.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/acepta.png"))); // NOI18N
        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });
        panelSur.add(btAceptar);

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/SALIR.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        panelSur.add(btCancelar);

        getContentPane().add(panelSur, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        // TODO add your handling code here:
        if(cmbServidor.getSelectedIndex()>-1){
            Actividad actividad= ((ModeloComboBoxActividad)cmbServidor.getModel()).getSelectedServidor();
            itemAgenda.setActividad(actividad);
            itemAgenda.setNombre_actividad(actividad.getNombreActividad());
        }
        itemAgenda.getHoraInicio().setHours(Integer.parseInt(spHoraInicio.getValue().toString()));
        itemAgenda.getHoraInicio().setMinutes(Integer.parseInt(spMinutosInicio.getValue().toString()));

        itemAgenda.getHoraFin().setHours(Integer.parseInt(spHoraFinal.getValue().toString()));
        itemAgenda.getHoraFin().setMinutes(Integer.parseInt(spMinutosFinal.getValue().toString()));

        double h=Integer.parseInt(spHoraFinal.getValue().toString())-Integer.parseInt(spHoraInicio.getValue().toString());
        double m=Integer.parseInt(spMinutosFinal.getValue().toString())-Integer.parseInt(spMinutosInicio.getValue().toString());
        m=h*60+m;

        h=m/60;
        m=(h-(int)h)*60;
        m=Math.round(m);
        ControladorItemAgenda.setTiempoDuracion(itemAgenda,
                                                (int)h,
                                                (int)m);

        itemAgenda.setRecordar(chbRecordar.isSelected());
        dispose();
    }//GEN-LAST:event_btAceptarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DialogoEditarItemAgenda dialog = new DialogoEditarItemAgenda(new javax.swing.JFrame(), true,null);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JCheckBox chbRecordar;
    private javax.swing.JComboBox cmbServidor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblHpraTermina;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelSur;
    private javax.swing.JSpinner spHoraFinal;
    private javax.swing.JSpinner spHoraInicio;
    private javax.swing.JSpinner spMinutosFinal;
    private javax.swing.JSpinner spMinutosInicio;
    // End of variables declaration//GEN-END:variables

}
