/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogoExpertoAgenda.java
 *
 * Created on 16/12/2012, 12:23:13 PM
 */

package vista;


import controlador.acciones.agenda.ControladorItemAgenda;
import controlador.acciones.servicios.ControladorAgenda;
import controlador.experto.ExpertoAgenda;
import java.util.Date;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.agenda.Agenda;
import modelo.agenda.ItemAgenda;
import vista.modelo.ModeloTablaItemAgenda;

public class DialogoExpertoAgenda extends javax.swing.JDialog {

    /** Creates new form DialogoExpertoAgenda */
    private ExpertoAgenda expertoAgenda;
    private Agenda agendaActual;
    private ModeloTablaItemAgenda modeloTablaItemAgenda;
    public DialogoExpertoAgenda(java.awt.Frame parent,boolean modal) {
        super(parent, modal);
        expertoAgenda=new ExpertoAgenda();
        this.modeloTablaItemAgenda=new ModeloTablaItemAgenda();
        iniciarAgenda();
        initComponents();
    }
     private void iniciarAgenda(){
        // cargar agenda
        agendaActual=ControladorAgenda.getAgendaActual();
        if(agendaActual==null){
            JOptionPane.showMessageDialog(this,"No se ha encontrado una agenda para el año:"+new Date().getYear()+" se creara una nueva");
            agendaActual=ControladorAgenda.getInstance();
            agendaActual.setNombre(""+new Date().getYear());
        }
        //iniciar paneles agenda
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItemsResultados = new javax.swing.JTable();
        panelNoerte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbDia = new javax.swing.JComboBox();
        btnGenerar = new javax.swing.JButton();
        panelSur = new javax.swing.JPanel();
        btGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EXPERTO");

        panelCentro.setLayout(new java.awt.BorderLayout());

        tbItemsResultados.setModel(modeloTablaItemAgenda);
        tbItemsResultados.setEnabled(false);
        tbItemsResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbItemsResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbItemsResultados);

        panelCentro.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

        panelNoerte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText("MES:");
        panelNoerte.add(jLabel1);

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero ", "Marzo", "Abril", "Mayo", "Junio", "Julio ", "Agosto ", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cmbMes.setPreferredSize(new java.awt.Dimension(250, 25));
        panelNoerte.add(cmbMes);

        jLabel2.setText("Día:");
        panelNoerte.add(jLabel2);

        cmbDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" }));
        cmbDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDiaActionPerformed(evt);
            }
        });
        panelNoerte.add(cmbDia);

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        panelNoerte.add(btnGenerar);

        getContentPane().add(panelNoerte, java.awt.BorderLayout.PAGE_START);

        panelSur.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelSur.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        panelSur.add(btGuardar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelSur.add(btnCancelar);

        getContentPane().add(panelSur, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        Vector<String> actividades=new Vector<String>();
        String mes=cmbMes.getSelectedItem().toString();
        String dia=cmbDia.getSelectedItem().toString();
        List<ItemAgenda> itemsAgenda=ControladorItemAgenda.searchItemsAgenda(mes,dia);
//        System.out.print(itemsAgenda);
        for (Iterator<ItemAgenda> it = itemsAgenda.iterator(); it.hasNext();) {
            ItemAgenda itemAgenda = it.next();
            if (itemAgenda.getMes().equals(mes)) {
                try {
                    Object obj=expertoAgenda.getResultado(itemAgenda,mes,dia);
                    if (obj!=null) {
                        actividades.add(obj.toString());
                    }
                    System.out.println("Resultado:"+obj);
                } catch (Exception ex) {
                    Logger.getLogger(DialogoExpertoAgenda.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        cargarTablaDeResultados(actividades);
    }//GEN-LAST:event_btnGenerarActionPerformed
    public void cargarTablaDeResultados(Vector<String> idActividades){
        System.out.println(idActividades);
        LinkedList<ItemAgenda>items=new LinkedList<ItemAgenda>();
        for (Iterator<String> it = idActividades.iterator(); it.hasNext();) {
            String nombre = it.next();
            ItemAgenda itemAgenda= ControladorItemAgenda.searchItemAgenda(nombre);
            if(itemAgenda!=null){
               items.add(itemAgenda);
            }
        }
        modeloTablaItemAgenda.setItemsAgenda(items);
        tbItemsResultados.revalidate();
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        // TODO add your handling code here:
      List<ItemAgenda> listaItemsAgenda=  modeloTablaItemAgenda.getItemsAgenda();
        for (Iterator<ItemAgenda> it = listaItemsAgenda.iterator(); it.hasNext();) {
            ItemAgenda itemAgenda = it.next();
            ItemAgenda newItemAgenda=new ItemAgenda();
            newItemAgenda.setActividad(itemAgenda.getActividad());
            newItemAgenda.setAgenda(itemAgenda.getAgenda());
            newItemAgenda.setDia(itemAgenda.getDia());
            newItemAgenda.setDia_del_mes(itemAgenda.getDia_del_mes());
            newItemAgenda.setFecha(new Date());
            newItemAgenda.setHoraFin(itemAgenda.getHoraFin());
            newItemAgenda.setHoraInicio(itemAgenda.getHoraInicio());
            newItemAgenda.setMes(itemAgenda.getMes());
            newItemAgenda.setNombre_actividad(itemAgenda.getNombre_actividad());
            newItemAgenda.setTiempoDuracion(itemAgenda.getTiempoDuracion());
            agendaActual.getItemsAgenda().add(newItemAgenda);
        }
      ControladorAgenda.updateAgenda();
      dispose();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void cmbDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDiaActionPerformed

    private void tbItemsResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbItemsResultadosMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
           int index=tbItemsResultados.getSelectedRow();
           if(index>-1){
               DialogoEditarItemAgenda dialogoEditar=new DialogoEditarItemAgenda(this,true,modeloTablaItemAgenda.getItemAgenda(index));
               dialogoEditar.setLocationRelativeTo(this);
               dialogoEditar.setVisible(true);
           }
        }
    }//GEN-LAST:event_tbItemsResultadosMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoExpertoAgenda dialog = new DialogoExpertoAgenda(new javax.swing.JFrame(),true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox cmbDia;
    private javax.swing.JComboBox cmbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelNoerte;
    private javax.swing.JPanel panelSur;
    private javax.swing.JTable tbItemsResultados;
    // End of variables declaration//GEN-END:variables

}
