/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.basedatos.Conexion;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import vista.modelo.Fecha;

/**
 *
 * @author alf
 */
public class DialogoReportes extends javax.swing.JDialog {

    /**
     * Creates new form DialogoReportes
     */
    public DialogoReportes(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbReportes = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        fechaDesde = new datechooser.beans.DateChooserCombo();
        jLabel4 = new javax.swing.JLabel();
        fechaHasta = new datechooser.beans.DateChooserCombo();
        btnGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Reporte ");
        jPanel2.add(jLabel1);

        jLabel2.setText("Tareas:");
        jPanel2.add(jLabel2);

        cmbReportes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Terminadas", " Pendientes" }));
        cmbReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbReportesActionPerformed(evt);
            }
        });
        jPanel2.add(cmbReportes);

        jLabel3.setText("Desde:");
        jPanel2.add(jLabel3);
        jPanel2.add(fechaDesde);

        jLabel4.setText("Hasta:");
        jPanel2.add(jLabel4);
        jPanel2.add(fechaHasta);

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGenerar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbReportesActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cmbReportesActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        if(fechaDesde.getSelectedDate().get(Calendar.YEAR)==fechaHasta.getSelectedDate().get(Calendar.YEAR)){
                if(cmbReportes.getSelectedIndex()==0){
                    try {
                       // TODO add your handling code here:
                       String anio=""+fechaDesde.getSelectedDate().get(Calendar.YEAR);
                       String dirReporte = "./reportes/ReporteActividades.jrxml";
                       JasperReport report = JasperCompileManager.compileReport(dirReporte);
                       Map<String, Object> parametros = new HashMap<String, Object>();
                       parametros.put("prm_agenda", anio);
                       parametros.put("prm_completada", 1);
                       parametros.put("prm_desde", Fecha.getFechaFormateada(fechaDesde.getSelectedDate().getTime(), "yyyy/MM/dd"));
                       parametros.put("prm_hasta", Fecha.getFechaFormateada(fechaHasta.getSelectedDate().getTime(), "yyyy/MM/dd"));
                       JasperPrint jp = JasperFillManager.fillReport(report, parametros, Conexion.conectate()); //datos
                       JasperViewer.viewReport(jp, false);
                   } catch (JRException ex) {
                       Logger.getLogger(DialogoReportes.class.getName()).log(Level.SEVERE, null, ex);
                   }
               }else if(cmbReportes.getSelectedIndex()==1){
                   try {
                       // TODO add your handling code here:
                       String anio=""+fechaDesde.getSelectedDate().get(Calendar.YEAR);
                       String dirReporte = "./reportes/ReporteActividades.jrxml";
                       JasperReport report = JasperCompileManager.compileReport(dirReporte);
                       Map<String, Object> parametros = new HashMap<String, Object>();
                       parametros.put("prm_agenda", anio);
                       parametros.put("prm_completada", 0);
                       parametros.put("prm_desde", Fecha.getFechaFormateada(fechaDesde.getSelectedDate().getTime(), "yyyy/MM/dd"));
                       parametros.put("prm_hasta", Fecha.getFechaFormateada(fechaHasta.getSelectedDate().getTime(), "yyyy/MM/dd"));
                       JasperPrint jp = JasperFillManager.fillReport(report, parametros,Conexion.conectate()); //datos
                       JasperViewer.viewReport(jp, false);
                   } catch (JRException ex) {
                       Logger.getLogger(DialogoReportes.class.getName()).log(Level.SEVERE, null, ex);
                   }
               }
        }else{
            JOptionPane.showMessageDialog(this,"Error el año de la fecha desde es diferente al año de la fecha hasta ");
        }
         
        dispose();
    }//GEN-LAST:event_btnGenerarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoReportes dialog = new DialogoReportes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox cmbReportes;
    private datechooser.beans.DateChooserCombo fechaDesde;
    private datechooser.beans.DateChooserCombo fechaHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
